li t0, 0x55bf5747
li t1, 0x7dfe525a
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
add t4, t1, t0
add t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x680b81b3
li t1, 0x92e0f53f
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sub t4, t1, t0
sub t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xe05242f9
li t1, 0xcf821987
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
xor t4, t1, t0
xor t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xd5701491
li t1, 0xb2e4369c
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
srl t4, t1, t0
srl t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x2f761fc5
li t1, 0xa4302cf0
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sra t4, t1, t0
sra t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x380262bf
li t1, 0x42dc39d0
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
or t4, t1, t0
or t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xb2a9a97f
li t1, 0x02990ecf
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
and t4, t1, t0
and t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x860036e1
li t1, 0xbf17b11b
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.adduNr t4, t1, t0
p.adduNr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xef0965b9
li t1, 0xce503979
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.addRNr t4, t1, t0
p.addRNr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xd13becc4
li t1, 0x840308a8
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.exths t4, t1
p.exths t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0235c0a4
li t1, 0x7bc80489
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.subNr t4, t1, t0
p.subNr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xdc96859d
li t1, 0x2b2ee7c3
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.subRNr t4, t1, t0
p.subRNr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x5195b500
li t1, 0xa2bf3842
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.subuRNr t4, t1, t0
p.subuRNr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x020d449e
li t1, 0x07d71acc
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.extractr t4, t1, t0
p.extractr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x16a2d74e
li t1, 0x4438bdbb
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.extractur t4, t1, t0
p.extractur t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x55a30d8c
li t1, 0x89fac796
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.insertr t4, t1, t0
p.insertr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xdbad9aa7
li t1, 0xe6a5edef
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.bclrr t4, t1, t0
p.bclrr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x65d16ae4
li t1, 0x75517260
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.bsetr t4, t1, t0
p.bsetr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xcd73fba6
li t1, 0xa1b8c194
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.ror t4, t1, t0
p.ror t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x1be40638
li t1, 0xbfbee530
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.slet t4, t1, t0
p.slet t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x5bb923c7
li t1, 0xe2f6c485
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.slet t4, t1, t0
p.slet t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xa9f066eb
li t1, 0x68e58a5b
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.sletu t4, t1, t0
p.sletu t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x2573924e
li t1, 0xa20c389b
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.min t4, t1, t0
p.min t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x61b5483c
li t1, 0xbb130b27
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.minu t4, t1, t0
p.minu t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x8223444f
li t1, 0x4cbd6103
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.max t4, t1, t0
p.max t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x456db822
li t1, 0x988f2572
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.insertr t4, t1, t0
p.insertr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x3f6a59e2
li t1, 0xc374aa90
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.bclrr t4, t1, t0
p.bclrr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x93d92b27
li t1, 0xa1d8d9a7
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.bsetr t4, t1, t0
p.bsetr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xcb3f93e1
li t1, 0x9f5076bf
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.ror t4, t1, t0
p.ror t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xa482cb58
li t1, 0x81a96802
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x56275096
li t1, 0xfd39ba96
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x5fc5a575
li t1, 0x57328130
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x3e3d0ca5
li t1, 0xe4da2af2
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xe45985c6
li t1, 0x87d897cc
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xf158a900
li t1, 0xbfa75263
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xc6587ce1
li t1, 0x7da09fb0
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x5747b5e7
li t1, 0x940197ec
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x94e4afec
li t1, 0xc2fc45d6
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x8925a579
li t1, 0x6ceabf97
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x58d50dc3
li t1, 0x5011168f
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x150bd260
li t1, 0x83af8e11
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xcffa18ee
li t1, 0xea6034b4
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.abs t4, t1
p.abs t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xe8d3c3df
li t1, 0x1dcb4aff
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.exths t4, t1
p.exths t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x73ca6188
li t1, 0x00a6675d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.exthz t4, t1
p.exthz t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x767f839a
li t1, 0x218869e0
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.extbs t4, t1
p.extbs t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xebba229a
li t1, 0x23e0198d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.extbz t4, t1
p.extbz t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xee083bab
li t1, 0x2379a600
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sll t4, t1, t0
sll t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xd601b3a8
li t1, 0x11613f83
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
slt t4, t1, t0
slt t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x883ce02b
li t1, 0xb54b7471
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sltu t4, t1, t0
sltu t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xfb9b1917
li t1, 0x0ae0a81b
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
div t4, t1, t0
div t5, t3, t2
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x936625ea
li t1, 0xb6ebd20f
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
divu t4, t1, t0
divu t5, t3, t2
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0d28b3c0
li t1, 0xc3460704
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.add.h t4, t1, t0
pv.add.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xf9b2ceb1
li t1, 0xfc50dcaf
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.add.sc.h t4, t1, t0
pv.add.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xb267489b
li t1, 0xe6047c8d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.add.sci.h t4, t1, 0x10
pv.add.sci.h t5, t2, 0x10
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xd1cbf2c4
li t1, 0xf228b691
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.add.b t4, t1, t0
pv.add.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xe6c2fe19
li t1, 0xdd9ae050
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.add.sc.b t4, t1, t0
pv.add.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x541a19a6
li t1, 0xf3e947b7
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.add.sci.b t4, t1, 0x0f
pv.add.sci.b t5, t2, 0x0f
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x5f608727
li t1, 0x2fe467b1
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sub.h t4, t1, t0
pv.sub.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x43c5bd8f
li t1, 0xe8cebe8d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sub.sc.h t4, t1, t0
pv.sub.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x7830e9ff
li t1, 0x48d7a215
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sub.sci.h t4, t1, 0x0b
pv.sub.sci.h t5, t2, 0x0b
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x2c18b599
li t1, 0xa5cd648a
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sub.b t4, t1, t0
pv.sub.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x819bbfb5
li t1, 0x83069365
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sub.sc.b t4, t1, t0
pv.sub.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x9c88bd7b
li t1, 0x1699dfcd
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sub.sci.b t4, t1, 0x1f
pv.sub.sci.b t5, t2, 0x1f
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x9ecca772
li t1, 0x5c28039d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avg.h t4, t1, t0
pv.avg.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x1844cd5d
li t1, 0x0729fad5
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avg.sc.h t4, t1, t0
pv.avg.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xd629da24
li t1, 0xca785710
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avg.sci.h t4, t1, 0x07
pv.avg.sci.h t5, t2, 0x07
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x4a222b6c
li t1, 0xc61a0033
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avg.b t4, t1, t0
pv.avg.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xd0645da4
li t1, 0xe549e475
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avg.sc.b t4, t1, t0
pv.avg.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x2f2b6886
li t1, 0x2d37bfd7
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avg.sci.b t4, t1, 0x0c
pv.avg.sci.b t5, t2, 0x0c
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x3050a126
li t1, 0xdbf8bfa1
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avgu.h t4, t1, t0
pv.avgu.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x2aac8ce5
li t1, 0x057e0419
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avgu.sc.h t4, t1, t0
pv.avgu.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x1cd1e04a
li t1, 0x64bbc1a7
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avgu.sci.h t4, t1, 0x09
pv.avgu.sci.h t5, t2, 0x09
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xc4ac0513
li t1, 0x5effaa73
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avgu.b t4, t1, t0
pv.avgu.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x632aec66
li t1, 0x6f000acc
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avgu.sc.b t4, t1, t0
pv.avgu.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x085eaa3c
li t1, 0x9a1a054c
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avgu.sci.b t4, t1, 0x04
pv.avgu.sci.b t5, t2, 0x04
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x877759bb
li t1, 0xbcf2c872
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.max.h t4, t1, t0
pv.max.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x042c0645
li t1, 0xdea54b25
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.max.sc.h t4, t1, t0
pv.max.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x2825614e
li t1, 0xbde1356d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.max.sci.h t4, t1, 0x1d
pv.max.sci.h t5, t2, 0x1d
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x619a04fe
li t1, 0x70609d77
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.max.b t4, t1, t0
pv.max.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x8c07d281
li t1, 0x67c29eff
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.max.sc.b t4, t1, t0
pv.max.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x9704e1f3
li t1, 0x4136140c
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.max.sci.b t4, t1, 0x08
pv.max.sci.b t5, t2, 0x08
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x374dcedc
li t1, 0x726ddc1f
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.maxu.h t4, t1, t0
pv.maxu.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xd1423b8b
li t1, 0x7ad36e6e
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.maxu.sc.h t4, t1, t0
pv.maxu.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xf0da4ecf
li t1, 0xc7f7d6db
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.maxu.sci.h t4, t1, 0x03
pv.maxu.sci.h t5, t2, 0x03
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x1a536ef6
li t1, 0x5794060e
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.maxu.b t4, t1, t0
pv.maxu.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x3f3d6382
li t1, 0x96db4a0a
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.maxu.sc.b t4, t1, t0
pv.maxu.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xbc62cc7c
li t1, 0x463c38ab
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.maxu.sci.b t4, t1, 0x1c
pv.maxu.sci.b t5, t2, 0x1c
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x41541d74
li t1, 0x7106d709
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.srl.h t4, t1, t0
pv.srl.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xd0538455
li t1, 0xc26c94cf
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.srl.sc.h t4, t1, t0
pv.srl.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x7050ae0f
li t1, 0x01e58c17
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.srl.sci.h t4, t1, 0x18
pv.srl.sci.h t5, t2, 0x18
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x22fc3179
li t1, 0x3261fca7
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.srl.b t4, t1, t0
pv.srl.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xe93f9794
li t1, 0x45400617
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.srl.sc.b t4, t1, t0
pv.srl.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x004e7a14
li t1, 0xc29ef4e4
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.srl.sci.b t4, t1, 0x05
pv.srl.sci.b t5, t2, 0x05
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x17b38f9f
li t1, 0x65169f50
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sra.h t4, t1, t0
pv.sra.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x1dc728ba
li t1, 0xb3c19e3c
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sra.sc.h t4, t1, t0
pv.sra.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x4f1bbcef
li t1, 0x44b8a679
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sra.sci.h t4, t1, 0x17
pv.sra.sci.h t5, t2, 0x17
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x5e830cb3
li t1, 0xcaae8202
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sra.b t4, t1, t0
pv.sra.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x52542fc1
li t1, 0x757023c6
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sra.sc.b t4, t1, t0
pv.sra.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x428b05b2
li t1, 0x9acb4c22
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sra.sci.b t4, t1, 0x1c
pv.sra.sci.b t5, t2, 0x1c
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x942a5153
li t1, 0x3c996975
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sll.h t4, t1, t0
pv.sll.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x60276fdd
li t1, 0x572aad10
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sll.sc.h t4, t1, t0
pv.sll.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x440f9256
li t1, 0xa913c452
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sll.sci.h t4, t1, 0x06
pv.sll.sci.h t5, t2, 0x06
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xf9b8d1ce
li t1, 0x17bc0091
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sll.b t4, t1, t0
pv.sll.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x09abdcde
li t1, 0xc591a8bb
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sll.sc.b t4, t1, t0
pv.sll.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xb503c958
li t1, 0xbf75c597
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sll.sci.b t4, t1, 0x07
pv.sll.sci.b t5, t2, 0x07
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xec269af6
li t1, 0x66469e34
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.or.h t4, t1, t0
pv.or.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xd79696c3
li t1, 0xd15537ab
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.or.sc.h t4, t1, t0
pv.or.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x61e31006
li t1, 0xe23df17a
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.or.sci.h t4, t1, 0x00
pv.or.sci.h t5, t2, 0x00
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xeb8189ea
li t1, 0x00dc7ee6
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.or.b t4, t1, t0
pv.or.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0994d476
li t1, 0xd210e02e
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.or.sc.b t4, t1, t0
pv.or.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x359a5d78
li t1, 0x560284ac
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.or.sci.b t4, t1, 0x05
pv.or.sci.b t5, t2, 0x05
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x06e62dea
li t1, 0x206f1ec1
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.xor.h t4, t1, t0
pv.xor.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x70590a55
li t1, 0xbf7f98a1
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.xor.sc.h t4, t1, t0
pv.xor.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xc1a5ea0a
li t1, 0x38848293
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.xor.sci.h t4, t1, 0x13
pv.xor.sci.h t5, t2, 0x13
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x5ed07ab7
li t1, 0x459f770d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.xor.b t4, t1, t0
pv.xor.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xe75e9e32
li t1, 0xcda88206
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.xor.sc.b t4, t1, t0
pv.xor.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x23166ba3
li t1, 0xe2c67aab
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.xor.sci.b t4, t1, 0x0c
pv.xor.sci.b t5, t2, 0x0c
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x717f119b
li t1, 0xf6588072
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.and.h t4, t1, t0
pv.and.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xdb39e1b1
li t1, 0x179fafb6
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.and.sc.h t4, t1, t0
pv.and.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x2c6c958f
li t1, 0xb69d4c1a
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.and.sci.h t4, t1, 0x1b
pv.and.sci.h t5, t2, 0x1b
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x3905dcb3
li t1, 0x75d7e5d8
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.and.b t4, t1, t0
pv.and.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x1c29f1bf
li t1, 0x9447bd71
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.and.sc.b t4, t1, t0
pv.and.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xb093286b
li t1, 0x3f523a1b
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.and.sci.b t4, t1, 0x10
pv.and.sci.b t5, t2, 0x10
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x047f934e
li t1, 0xba9136e7
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.abs.h t4, t1
pv.abs.b t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xb5c1b691
li t1, 0x2a71481e
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.shuffle.h t4, t1, t0
pv.shuffle.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x96a84b3f
li t1, 0xe9204ffa
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.shuffle.sci.h t4, t1, 0x01
pv.shuffle.sci.h t5, t2, 0x01
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xda0fda2d
li t1, 0xfc1828f1
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.shuffle.b t4, t1, t0
pv.shuffle.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xf4df6f8e
li t1, 0x69ea283c
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.pack.h t4, t1, t0
pv.pack.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xbdc7288a
li t1, 0x412795d2
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.packhi.b t4, t1, t0
pv.packhi.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x636be4e6
li t1, 0x122c5e3e
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.packlo.b t4, t1, t0
pv.packlo.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xd318fd5e
li t1, 0xfc8a9605
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.extract t4, t1, 0b01010, 0x0f
p.extract t5, t2, 0b01010, 0x0f
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x16d43c90
li t1, 0xf5bf13fc
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.insert t4, t1, 0b01010, 0x14
p.insert t5, t2, 0b01010, 0x14
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xcbe8dd7f
li t1, 0xf061c67d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.bclr t4, t1, 0b01010, 0x1c
p.bclr t5, t2, 0b01010, 0x1c
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x99888b34
li t1, 0x11fafe20
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.ff1 t4, t1
p.ff1 t5, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x7f812976
li t1, 0x48a0e896
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.fl1 t4, t1
p.fl1 t5, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0bb6768f
li t1, 0x739d964c
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.clb t4, t1
p.clb t5, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x49175972
li t1, 0x7794ca44
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.cnt t4, t1
p.cnt t5, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x8144151b
li t1, 0x8c78511a
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpeq.h t4, t1, t0
pv.cmpeq.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xbe89be80
li t1, 0x7c2532df
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpeq.sc.h t4, t1, t0
pv.cmpeq.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xe7e42a18
li t1, 0x3541973d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpeq.sci.h t4, t1, 0x0a
pv.cmpeq.sci.h t5, t2, 0x0a
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xfce5954e
li t1, 0xbccf1304
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpeq.b t4, t1, t0
pv.cmpeq.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x78032191
li t1, 0xed4d5e7e
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpeq.sc.b t4, t1, t0
pv.cmpeq.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x314b4cb3
li t1, 0x36baa73d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpeq.sci.b t4, t1, 0x03
pv.cmpeq.sci.b t5, t2, 0x03
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xff252227
li t1, 0x9dd05a5f
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpne.h t4, t1, t0
pv.cmpne.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x43de2a8d
li t1, 0x49dec026
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpne.sc.h t4, t1, t0
pv.cmpne.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xa5d9741f
li t1, 0xddf998b7
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x1b23587b
li t1, 0x5afc3040
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpne.sci.h t4, t1, 0x0b
pv.cmpne.sci.h t5, t2, 0x0b
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xbabdad34
li t1, 0x6902b8fb
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpne.b t4, t1, t0
pv.cmpne.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xaa6a692c
li t1, 0xccaca6a9
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpne.sc.b t4, t1, t0
pv.cmpne.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x9a2f1c3d
li t1, 0x9e3827ee
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpne.sci.b t4, t1, 0x1c
pv.cmpne.sci.b t5, t2, 0x1c
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xfa553006
li t1, 0xe5f3dddc
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgt.h t4, t1, t0
pv.cmpgt.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xa7092e50
li t1, 0x29d5c460
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgt.sc.h t4, t1, t0
pv.cmpgt.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xcd3de498
li t1, 0x5333ced5
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgt.sci.h t4, t1, 0x18
pv.cmpgt.sci.h t5, t2, 0x18
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x2929db59
li t1, 0xfbc8936f
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgt.b t4, t1, t0
pv.cmpgt.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x6bcdf5a5
li t1, 0xd47ac543
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgt.sc.b t4, t1, t0
pv.cmpgt.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x88b3e249
li t1, 0xba7a935e
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgt.sci.b t4, t1, 0x1a
pv.cmpgt.sci.b t5, t2, 0x1a
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xb671b7d2
li t1, 0xffa895b7
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpge.h t4, t1, t0
pv.cmpge.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xba4f2c59
li t1, 0x3cb5939a
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpge.sc.h t4, t1, t0
pv.cmpge.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x6d618088
li t1, 0x12ca5811
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpge.sci.h t4, t1, 0x09
pv.cmpge.sci.h t5, t2, 0x09
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xb05604b6
li t1, 0x3ec497f4
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpge.b t4, t1, t0
pv.cmpge.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x07f102ed
li t1, 0xe1f800a4
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpge.sc.b t4, t1, t0
pv.cmpge.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x03f3556b
li t1, 0x857085ae
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpge.sci.b t4, t1, 0x1f
pv.cmpge.sci.b t5, t2, 0x1f
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x7b2bd591
li t1, 0xf3eed437
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmplt.h t4, t1, t0
pv.cmplt.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xe9c1aa81
li t1, 0xdcabfd07
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmplt.sc.h t4, t1, t0
pv.cmplt.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x981253cc
li t1, 0x71103bdc
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmplt.sci.h t4, t1, 0x03
pv.cmplt.sci.h t5, t2, 0x03
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x8851fd9b
li t1, 0x2c22b4db
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmplt.b t4, t1, t0
pv.cmplt.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x126fdc23
li t1, 0xa1826661
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmplt.sc.b t4, t1, t0
pv.cmplt.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xb146849c
li t1, 0x7842eea3
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmplt.sci.b t4, t1, 0x1b
pv.cmplt.sci.b t5, t2, 0x1b
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x63dfce25
li t1, 0x470b231a
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmple.h t4, t1, t0
pv.cmple.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xbbdc2064
li t1, 0x2342e102
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmple.sc.h t4, t1, t0
pv.cmple.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xe796e8c2
li t1, 0xd5c87136
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmple.sci.h t4, t1, 0x16
pv.cmple.sci.h t5, t2, 0x16
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xb07d8cb3
li t1, 0xf0891cc5
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmple.b t4, t1, t0
pv.cmple.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x4df37bf6
li t1, 0xf57fe789
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmple.sc.b t4, t1, t0
pv.cmple.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x54801f2c
li t1, 0x81dd62e8
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmple.sci.b t4, t1, 0x0c
pv.cmple.sci.b t5, t2, 0x0c
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xb17506e8
li t1, 0x8a9c2acf
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgtu.h t4, t1, t0
pv.cmpgtu.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x12319a70
li t1, 0x004b7106
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgtu.sc.h t4, t1, t0
pv.cmpgtu.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xa083e8f7
li t1, 0x9ec5051c
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgtu.sci.h t4, t1, 0x16
pv.cmpgtu.sci.h t5, t2, 0x16
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xa098aec2
li t1, 0x240efbda
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgtu.b t4, t1, t0
pv.cmpgtu.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x1f8d8eec
li t1, 0xe7ef8a57
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgtu.sc.b t4, t1, t0
pv.cmpgtu.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x77104a97
li t1, 0xbfd31da7
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgtu.sci.b t4, t1, 0x0d
pv.cmpgtu.sci.b t5, t2, 0x0d
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x72b93443
li t1, 0x0609d1d3
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgeu.h t4, t1, t0
pv.cmpgeu.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x607be2fb
li t1, 0x215fbc8d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgeu.sc.h t4, t1, t0
pv.cmpgeu.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x518676c1
li t1, 0x02f72a49
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgeu.sci.h t4, t1, 0x04
pv.cmpgeu.sci.h t5, t2, 0x04
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x42b8ea4c
li t1, 0x7f586bd3
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgeu.b t4, t1, t0
pv.cmpgeu.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x508cc646
li t1, 0xf984bab9
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgeu.sc.b t4, t1, t0
pv.cmpgeu.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xe0af1d2d
li t1, 0x90eb4156
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgeu.sci.b t4, t1, 0x13
pv.cmpgeu.sci.b t5, t2, 0x13
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xa11b9cd5
li t1, 0xb4994b0e
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpltu.h t4, t1, t0
pv.cmpltu.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x2e557c38
li t1, 0xc7a6446b
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpltu.sc.h t4, t1, t0
pv.cmpltu.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x060c61e7
li t1, 0x1f533ca7
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpltu.sci.h t4, t1, 0x0c
pv.cmpltu.sci.h t5, t2, 0x0c
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xbe791db4
li t1, 0x68666c30
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpltu.b t4, t1, t0
pv.cmpltu.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x3e08eb91
li t1, 0xc7e2d000
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpltu.sc.b t4, t1, t0
pv.cmpltu.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x4e27f2eb
li t1, 0x71e1a519
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpltu.sci.b t4, t1, 0x09
pv.cmpltu.sci.b t5, t2, 0x09
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x5c3b9bcb
li t1, 0xa01e172d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpleu.h t4, t1, t0
pv.cmpleu.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xb6fd0faa
li t1, 0x6d60627c
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpleu.sc.h t4, t1, t0
pv.cmpleu.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x52962381
li t1, 0x3039ba3e
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpleu.sci.h t4, t1, 0x06
pv.cmpleu.sci.h t5, t2, 0x06
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x5e093b89
li t1, 0x73070d9e
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpleu.b t4, t1, t0
pv.cmpleu.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x598c80d9
li t1, 0x8255e228
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpleu.sc.b t4, t1, t0
pv.cmpleu.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x40ef9593
li t1, 0xcdbf4c6b
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpleu.sci.b t4, t1, 0x1a
pv.cmpleu.sci.b t5, t2, 0x1a
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xa5a5a5a5
li t1, 0x5a5a5a5a
add t4, t1, t0
sw t4, 4(sp)
li t0, 0xc3c3c3c3
li t1, 0x3c3c3c3c
add t4, t1, t0
sw t4, 4(sp)
li t0, 0x18181818
li t1, 0x81818181
add t4, t1, t0
sw t4, 4(sp)
li t0, 0x00000000
li t1, 0x00000000
add t4, t1, t0
sw t4, 4(sp)
li t0, 0xffffffff
li t1, 0xffffffff
add t4, t1, t0
sw t4, 4(sp)
li t0, 0xffff0000
li t1, 0x0000ffff
add t4, t1, t0
sw t4, 4(sp)
li t0, 0xffff0000
li t1, 0x0000ffff
sub t4, t1, t0
sw t4, 4(sp)
li t0, 0x00000000
li t1, 0xffffffff
sub t4, t1, t0
sw t4, 4(sp)
li t1, 0x00000000
li t0, 0xffffffff
sub t4, t1, t0
sw t4, 4(sp)
li t0, 0x00000000
li t1, 0x00000001
li t4, 0x00000000
li t5, 0x00000020
LOOP1:
beq t1, t0, LB1
beq t0, t0, LB1
addi x0, x0, 0
LB1:
addi t4, t4, 0x1
slli t1, t1, 0x1
sw t4, 4(sp)
sw t0, 4(sp)
sw t1, 4(sp)
bne t4, t5, LOOP1
li t0, 0x0000735a
li t1, 0x0000bc32
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
add t4, t1, t0
add t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000718f
li t1, 0x0000a795
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sub t4, t1, t0
sub t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000a964
li t1, 0x0000053b
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
xor t4, t1, t0
xor t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00001798
li t1, 0x0000e6ba
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
srl t4, t1, t0
srl t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000a644
li t1, 0x00007b26
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sra t4, t1, t0
sra t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000a012
li t1, 0x0000d693
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
or t4, t1, t0
or t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000f162
li t1, 0x0000d048
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
and t4, t1, t0
and t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000d4b6
li t1, 0x00004cca
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.adduNr t4, t1, t0
p.adduNr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000d1a3
li t1, 0x0000b50d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.addRNr t4, t1, t0
p.addRNr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000c6ed
li t1, 0x000044bf
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.exths t4, t1
p.exths t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000014c6
li t1, 0x000000cb
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.subNr t4, t1, t0
p.subNr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000fca0
li t1, 0x000081fa
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.subRNr t4, t1, t0
p.subRNr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000b5cd
li t1, 0x0000f379
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.subuRNr t4, t1, t0
p.subuRNr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00004548
li t1, 0x0000aeb6
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.extractr t4, t1, t0
p.extractr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000e4e2
li t1, 0x0000eed7
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.extractur t4, t1, t0
p.extractur t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000bdb2
li t1, 0x0000972e
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.insertr t4, t1, t0
p.insertr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000062ec
li t1, 0x0000cf63
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.bclrr t4, t1, t0
p.bclrr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00004295
li t1, 0x0000fcd8
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.bsetr t4, t1, t0
p.bsetr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000ed28
li t1, 0x00001795
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.ror t4, t1, t0
p.ror t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000092aa
li t1, 0x00001101
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.slet t4, t1, t0
p.slet t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000af10
li t1, 0x0000c839
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.slet t4, t1, t0
p.slet t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00004141
li t1, 0x0000ba72
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.sletu t4, t1, t0
p.sletu t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000f6c3
li t1, 0x00006d3a
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.min t4, t1, t0
p.min t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000cc56
li t1, 0x000097f5
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.minu t4, t1, t0
p.minu t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00001fad
li t1, 0x0000ce8b
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.max t4, t1, t0
p.max t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000027be
li t1, 0x0000a12c
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.insertr t4, t1, t0
p.insertr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00001e02
li t1, 0x00004532
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.bclrr t4, t1, t0
p.bclrr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000059f7
li t1, 0x00001abf
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.bsetr t4, t1, t0
p.bsetr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000a582
li t1, 0x00001526
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.ror t4, t1, t0
p.ror t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000044e5
li t1, 0x0000a9fa
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00006583
li t1, 0x00003f70
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00002e33
li t1, 0x0000845d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000c2b4
li t1, 0x0000d159
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000009e
li t1, 0x00005ff9
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000b2bc
li t1, 0x00008e40
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000e9da
li t1, 0x0000f122
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000fe55
li t1, 0x0000c73f
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000ad15
li t1, 0x0000601d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000f705
li t1, 0x000080e5
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000b6d5
li t1, 0x0000c6fe
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000095ec
li t1, 0x0000f8a0
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000604b
li t1, 0x00002dca
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.abs t4, t1
p.abs t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000010c
li t1, 0x00007e7b
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.exths t4, t1
p.exths t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00005e68
li t1, 0x0000c1d8
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.exthz t4, t1
p.exthz t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000039a
li t1, 0x00007edf
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.extbs t4, t1
p.extbs t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000cd72
li t1, 0x0000e035
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.extbz t4, t1
p.extbz t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00009afb
li t1, 0x00008edb
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sll t4, t1, t0
sll t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00001b7c
li t1, 0x0000882c
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
slt t4, t1, t0
slt t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000bdad
li t1, 0x00008622
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sltu t4, t1, t0
sltu t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000032d
li t1, 0x0000d81a
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
div t4, t1, t0
div t5, t3, t2
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000d122
li t1, 0x00008c0d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
divu t4, t1, t0
divu t5, t3, t2
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000aecf
li t1, 0x0000f62b
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.add.h t4, t1, t0
pv.add.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00002128
li t1, 0x00009adf
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.add.sc.h t4, t1, t0
pv.add.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000093d
li t1, 0x000020c7
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.add.sci.h t4, t1, 0x01
pv.add.sci.h t5, t2, 0x01
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000d03a
li t1, 0x00001db2
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.add.b t4, t1, t0
pv.add.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00003017
li t1, 0x00000b1e
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.add.sc.b t4, t1, t0
pv.add.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000ba4c
li t1, 0x00000260
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.add.sci.b t4, t1, 0x03
pv.add.sci.b t5, t2, 0x03
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00005284
li t1, 0x0000a159
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sub.h t4, t1, t0
pv.sub.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000b5eb
li t1, 0x0000a453
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sub.sc.h t4, t1, t0
pv.sub.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000057d9
li t1, 0x0000c905
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sub.sci.h t4, t1, 0x03
pv.sub.sci.h t5, t2, 0x03
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000db7d
li t1, 0x0000c3c1
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sub.b t4, t1, t0
pv.sub.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000abd9
li t1, 0x0000b8cb
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sub.sc.b t4, t1, t0
pv.sub.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000ed0a
li t1, 0x0000e865
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sub.sci.b t4, t1, 0x03
pv.sub.sci.b t5, t2, 0x03
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000f629
li t1, 0x0000944a
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avg.h t4, t1, t0
pv.avg.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000633d
li t1, 0x0000bdf2
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avg.sc.h t4, t1, t0
pv.avg.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000ed74
li t1, 0x0000bded
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avg.sci.h t4, t1, 0x01
pv.avg.sci.h t5, t2, 0x01
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000a366
li t1, 0x000007e4
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avg.b t4, t1, t0
pv.avg.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000b8be
li t1, 0x00008b96
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avg.sc.b t4, t1, t0
pv.avg.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000f8b3
li t1, 0x0000ce63
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avg.sci.b t4, t1, 0x00
pv.avg.sci.b t5, t2, 0x00
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00001a33
li t1, 0x00006e3d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avgu.h t4, t1, t0
pv.avgu.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00007c60
li t1, 0x0000dabc
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avgu.sc.h t4, t1, t0
pv.avgu.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000092b9
li t1, 0x000031bb
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avgu.sci.h t4, t1, 0x01
pv.avgu.sci.h t5, t2, 0x01
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00005a15
li t1, 0x000060a6
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avgu.b t4, t1, t0
pv.avgu.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000088e5
li t1, 0x00007abb
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avgu.sc.b t4, t1, t0
pv.avgu.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000019fa
li t1, 0x0000bde4
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.avgu.sci.b t4, t1, 0x03
pv.avgu.sci.b t5, t2, 0x03
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00005d9d
li t1, 0x00005bea
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.max.h t4, t1, t0
pv.max.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000a971
li t1, 0x0000138d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.max.sc.h t4, t1, t0
pv.max.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000e002
li t1, 0x0000b1ee
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.max.sci.h t4, t1, 0x03
pv.max.sci.h t5, t2, 0x03
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00006431
li t1, 0x000075ea
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.max.b t4, t1, t0
pv.max.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000e538
li t1, 0x00006ad5
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.max.sc.b t4, t1, t0
pv.max.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00006785
li t1, 0x00007f06
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.max.sci.b t4, t1, 0x03
pv.max.sci.b t5, t2, 0x03
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00002222
li t1, 0x0000dc9b
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.maxu.h t4, t1, t0
pv.maxu.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000426
li t1, 0x000019b6
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.maxu.sc.h t4, t1, t0
pv.maxu.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00004d85
li t1, 0x0000510b
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.maxu.sci.h t4, t1, 0x03
pv.maxu.sci.h t5, t2, 0x03
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00007b8c
li t1, 0x0000646b
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.maxu.b t4, t1, t0
pv.maxu.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000036cb
li t1, 0x000064b2
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.maxu.sc.b t4, t1, t0
pv.maxu.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000b210
li t1, 0x0000ca71
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.maxu.sci.b t4, t1, 0x02
pv.maxu.sci.b t5, t2, 0x02
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00006906
li t1, 0x0000a125
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.srl.h t4, t1, t0
pv.srl.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000ae9d
li t1, 0x0000d27a
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.srl.sc.h t4, t1, t0
pv.srl.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000e3fc
li t1, 0x0000f33b
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.srl.sci.h t4, t1, 0x00
pv.srl.sci.h t5, t2, 0x00
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000041e0
li t1, 0x00005611
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.srl.b t4, t1, t0
pv.srl.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000755
li t1, 0x0000c8c7
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.srl.sc.b t4, t1, t0
pv.srl.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000f6b
li t1, 0x000041ad
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.srl.sci.b t4, t1, 0x00
pv.srl.sci.b t5, t2, 0x00
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00006f4c
li t1, 0x0000ecb9
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sra.h t4, t1, t0
pv.sra.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00009ed3
li t1, 0x00000764
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sra.sc.h t4, t1, t0
pv.sra.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000da7a
li t1, 0x000088f1
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sra.sci.h t4, t1, 0x01
pv.sra.sci.h t5, t2, 0x01
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000da21
li t1, 0x00001b24
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sra.b t4, t1, t0
pv.sra.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00007f78
li t1, 0x0000d467
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sra.sc.b t4, t1, t0
pv.sra.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00001cc7
li t1, 0x0000042d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sra.sci.b t4, t1, 0x02
pv.sra.sci.b t5, t2, 0x02
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00007c04
li t1, 0x0000b4b6
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sll.h t4, t1, t0
pv.sll.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000217a
li t1, 0x0000fdeb
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sll.sc.h t4, t1, t0
pv.sll.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000045bd
li t1, 0x0000a2c9
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sll.sci.h t4, t1, 0x02
pv.sll.sci.h t5, t2, 0x02
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00006610
li t1, 0x000099ab
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sll.b t4, t1, t0
pv.sll.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000ae5d
li t1, 0x00002704
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sll.sc.b t4, t1, t0
pv.sll.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00003c6d
li t1, 0x0000bdad
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.sll.sci.b t4, t1, 0x01
pv.sll.sci.b t5, t2, 0x01
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00005ca0
li t1, 0x0000c241
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.or.h t4, t1, t0
pv.or.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000f6ef
li t1, 0x00002ddc
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.or.sc.h t4, t1, t0
pv.or.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000d5b1
li t1, 0x0000a848
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.or.sci.h t4, t1, 0x03
pv.or.sci.h t5, t2, 0x03
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00002afd
li t1, 0x0000c8ce
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.or.b t4, t1, t0
pv.or.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000688
li t1, 0x00001144
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.or.sc.b t4, t1, t0
pv.or.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000e2f9
li t1, 0x00003037
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.or.sci.b t4, t1, 0x01
pv.or.sci.b t5, t2, 0x01
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00005e99
li t1, 0x0000830d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.xor.h t4, t1, t0
pv.xor.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00002237
li t1, 0x0000fd33
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.xor.sc.h t4, t1, t0
pv.xor.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000013af
li t1, 0x00008d3c
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.xor.sci.h t4, t1, 0x01
pv.xor.sci.h t5, t2, 0x01
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000be83
li t1, 0x0000635a
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.xor.b t4, t1, t0
pv.xor.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000fe4c
li t1, 0x0000c488
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.xor.sc.b t4, t1, t0
pv.xor.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00001a90
li t1, 0x00001139
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.xor.sci.b t4, t1, 0x00
pv.xor.sci.b t5, t2, 0x00
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00007925
li t1, 0x000083fa
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.and.h t4, t1, t0
pv.and.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000b314
li t1, 0x00001e32
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.and.sc.h t4, t1, t0
pv.and.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000b1d3
li t1, 0x0000eac4
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.and.sci.h t4, t1, 0x01
pv.and.sci.h t5, t2, 0x01
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00001acd
li t1, 0x0000a82c
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.and.b t4, t1, t0
pv.and.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000665c
li t1, 0x000042af
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.and.sc.b t4, t1, t0
pv.and.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000040c5
li t1, 0x00009f8c
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.and.sci.b t4, t1, 0x02
pv.and.sci.b t5, t2, 0x02
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000fc69
li t1, 0x00002702
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.abs.h t4, t1
pv.abs.b t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000a5d1
li t1, 0x0000a015
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.shuffle.h t4, t1, t0
pv.shuffle.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000e693
li t1, 0x0000c86e
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.shuffle.sci.h t4, t1, 0x01
pv.shuffle.sci.h t5, t2, 0x01
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000750d
li t1, 0x00007b52
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.shuffle.b t4, t1, t0
pv.shuffle.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000061f5
li t1, 0x0000fdec
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.pack.h t4, t1, t0
pv.pack.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000553a
li t1, 0x00002cc1
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.packhi.b t4, t1, t0
pv.packhi.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00001f47
li t1, 0x000025e3
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.packlo.b t4, t1, t0
pv.packlo.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000060da
li t1, 0x0000e938
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.extract t4, t1, 0b01010, 0x01
p.extract t5, t2, 0b01010, 0x01
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000c5ab
li t1, 0x00006fbb
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.insert t4, t1, 0b01010, 0x02
p.insert t5, t2, 0b01010, 0x02
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000b890
li t1, 0x00003c6e
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.bclr t4, t1, 0b01010, 0x03
p.bclr t5, t2, 0b01010, 0x03
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000b068
li t1, 0x0000f164
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.ff1 t4, t1
p.ff1 t5, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000089c0
li t1, 0x0000b8bd
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.fl1 t4, t1
p.fl1 t5, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00001fe3
li t1, 0x00002a34
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.clb t4, t1
p.clb t5, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000f8fb
li t1, 0x0000fa51
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
p.cnt t4, t1
p.cnt t5, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00006454
li t1, 0x000087f0
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpeq.h t4, t1, t0
pv.cmpeq.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000b3aa
li t1, 0x00007be8
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpeq.sc.h t4, t1, t0
pv.cmpeq.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000aef4
li t1, 0x0000f07d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpeq.sci.h t4, t1, 0x00
pv.cmpeq.sci.h t5, t2, 0x00
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000038a7
li t1, 0x0000b869
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpeq.b t4, t1, t0
pv.cmpeq.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000478a
li t1, 0x00006c65
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpeq.sc.b t4, t1, t0
pv.cmpeq.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000572c
li t1, 0x0000f7c8
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpeq.sci.b t4, t1, 0x02
pv.cmpeq.sci.b t5, t2, 0x02
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00002f0d
li t1, 0x00008933
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpne.h t4, t1, t0
pv.cmpne.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00001ba7
li t1, 0x0000038f
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpne.sc.h t4, t1, t0
pv.cmpne.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00002fbe
li t1, 0x0000a8ec
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000028f1
li t1, 0x0000d034
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpne.sci.h t4, t1, 0x02
pv.cmpne.sci.h t5, t2, 0x02
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000d815
li t1, 0x00003d1e
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpne.b t4, t1, t0
pv.cmpne.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000a99d
li t1, 0x0000f846
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpne.sc.b t4, t1, t0
pv.cmpne.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00001b8e
li t1, 0x0000fbd0
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpne.sci.b t4, t1, 0x03
pv.cmpne.sci.b t5, t2, 0x03
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000a9e2
li t1, 0x000088cf
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgt.h t4, t1, t0
pv.cmpgt.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00004184
li t1, 0x0000e081
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgt.sc.h t4, t1, t0
pv.cmpgt.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000eb1f
li t1, 0x0000af71
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgt.sci.h t4, t1, 0x03
pv.cmpgt.sci.h t5, t2, 0x03
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000c879
li t1, 0x0000a694
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgt.b t4, t1, t0
pv.cmpgt.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000d518
li t1, 0x00007480
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgt.sc.b t4, t1, t0
pv.cmpgt.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00001aac
li t1, 0x0000310c
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgt.sci.b t4, t1, 0x00
pv.cmpgt.sci.b t5, t2, 0x00
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000a660
li t1, 0x00006864
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpge.h t4, t1, t0
pv.cmpge.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000cf30
li t1, 0x00009647
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpge.sc.h t4, t1, t0
pv.cmpge.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000f858
li t1, 0x0000f362
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpge.sci.h t4, t1, 0x01
pv.cmpge.sci.h t5, t2, 0x01
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000014d5
li t1, 0x0000195a
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpge.b t4, t1, t0
pv.cmpge.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000f4a1
li t1, 0x0000ecd1
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpge.sc.b t4, t1, t0
pv.cmpge.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00003da2
li t1, 0x00009caa
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpge.sci.b t4, t1, 0x02
pv.cmpge.sci.b t5, t2, 0x02
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00003027
li t1, 0x00000513
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmplt.h t4, t1, t0
pv.cmplt.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000040ef
li t1, 0x0000e01d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmplt.sc.h t4, t1, t0
pv.cmplt.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000035af
li t1, 0x00001dc2
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmplt.sci.h t4, t1, 0x00
pv.cmplt.sci.h t5, t2, 0x00
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000076a8
li t1, 0x00005467
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmplt.b t4, t1, t0
pv.cmplt.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00007766
li t1, 0x00000e83
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmplt.sc.b t4, t1, t0
pv.cmplt.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000f09a
li t1, 0x0000ceb2
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmplt.sci.b t4, t1, 0x01
pv.cmplt.sci.b t5, t2, 0x01
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000225f
li t1, 0x0000206b
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmple.h t4, t1, t0
pv.cmple.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000a74d
li t1, 0x0000e9f9
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmple.sc.h t4, t1, t0
pv.cmple.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000f6ec
li t1, 0x000062b9
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmple.sci.h t4, t1, 0x02
pv.cmple.sci.h t5, t2, 0x02
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00007951
li t1, 0x00008c24
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmple.b t4, t1, t0
pv.cmple.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00002e0f
li t1, 0x000015ee
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmple.sc.b t4, t1, t0
pv.cmple.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000092f2
li t1, 0x0000842b
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmple.sci.b t4, t1, 0x02
pv.cmple.sci.b t5, t2, 0x02
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00006e62
li t1, 0x0000c07c
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgtu.h t4, t1, t0
pv.cmpgtu.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000f74e
li t1, 0x00001c22
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgtu.sc.h t4, t1, t0
pv.cmpgtu.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000d504
li t1, 0x00007771
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgtu.sci.h t4, t1, 0x02
pv.cmpgtu.sci.h t5, t2, 0x02
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00004d60
li t1, 0x00003eb8
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgtu.b t4, t1, t0
pv.cmpgtu.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000bd72
li t1, 0x00007807
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgtu.sc.b t4, t1, t0
pv.cmpgtu.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000b81c
li t1, 0x00002210
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgtu.sci.b t4, t1, 0x03
pv.cmpgtu.sci.b t5, t2, 0x03
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000e951
li t1, 0x0000cc2e
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgeu.h t4, t1, t0
pv.cmpgeu.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000a4f5
li t1, 0x0000a08b
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgeu.sc.h t4, t1, t0
pv.cmpgeu.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000d404
li t1, 0x0000cc8d
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgeu.sci.h t4, t1, 0x01
pv.cmpgeu.sci.h t5, t2, 0x01
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000ea98
li t1, 0x000041d7
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgeu.b t4, t1, t0
pv.cmpgeu.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00008a9f
li t1, 0x0000a3a0
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgeu.sc.b t4, t1, t0
pv.cmpgeu.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00002892
li t1, 0x0000ae20
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpgeu.sci.b t4, t1, 0x03
pv.cmpgeu.sci.b t5, t2, 0x03
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000ebea
li t1, 0x0000029f
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpltu.h t4, t1, t0
pv.cmpltu.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000158c
li t1, 0x0000bda8
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpltu.sc.h t4, t1, t0
pv.cmpltu.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000b10e
li t1, 0x0000f635
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpltu.sci.h t4, t1, 0x01
pv.cmpltu.sci.h t5, t2, 0x01
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00009375
li t1, 0x0000decd
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpltu.b t4, t1, t0
pv.cmpltu.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000f1ed
li t1, 0x00004ce0
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpltu.sc.b t4, t1, t0
pv.cmpltu.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000a4c
li t1, 0x00006004
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpltu.sci.b t4, t1, 0x00
pv.cmpltu.sci.b t5, t2, 0x00
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000dabb
li t1, 0x0000ba15
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpleu.h t4, t1, t0
pv.cmpleu.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00004863
li t1, 0x00008134
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpleu.sc.h t4, t1, t0
pv.cmpleu.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000ff5e
li t1, 0x0000dca9
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpleu.sci.h t4, t1, 0x03
pv.cmpleu.sci.h t5, t2, 0x03
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00001d28
li t1, 0x0000a8f3
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpleu.b t4, t1, t0
pv.cmpleu.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000f544
li t1, 0x0000c267
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpleu.sc.b t4, t1, t0
pv.cmpleu.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000b95c
li t1, 0x0000eb21
xori t2, t1, 0xffffffff
xori t3, t0, 0xffffffff
pv.cmpleu.sci.b t4, t1, 0x00
pv.cmpleu.sci.b t5, t2, 0x00
sw t4, 4(sp)
sw t5, 4(sp)
sw t4, 4(sp)
sw t5, 4(sp)
