li t0, 0x00000000
li t1, 0x00000ff0
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000000
li t1, 0x00000000
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x0f000f00
li t1, 0x00000000
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0xffffffff
li t1, 0xffffffff
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000001
li t1, 0x00000001
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000001
li t1, 0xffffffff
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000001
li t1, 0x00000010
li t0, 0x00000001
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000001
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000002
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000004
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000006
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000000a
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000000b
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000013
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000001e
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000020
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000003c
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000067
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000006f
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000075
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000085
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000000f9
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000001ba
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000344
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000003e5
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000001
li t1, 0x0000ffff
li t0, 0x00014631
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00027d90
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00047f03
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0005b827
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000acdd8
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x000be42f
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0017194d
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000001
li t1, 0xf0f0f0f0
li t0, 0x00000001
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000001
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000002
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000002
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000004
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000007
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000000c
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xca96c1bf
li t1, 0x360f3772
div t4, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
div t4, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xa8b57014
li t1, 0xce86497a
div t4, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
div t4, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x39240b3a
li t1, 0x0ba52ada
div t4, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
divu t4, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xf7dbe1ca
li t1, 0x722fc83e
divu t4, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
divu t4, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x86bee62f
li t1, 0x5d14e90e
divu t4, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
divu t4, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0000d5d5
li t1, 0x0000eb41
div t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
div t4, t1, t0
sw t4, 4(sp)
li t0, 0x00007114
li t1, 0x0000b110
div t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
div t4, t1, t0
sw t4, 4(sp)
li t0, 0x00008804
li t1, 0x0000471e
div t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
divu t4, t1, t0
sw t4, 4(sp)
li t0, 0x0000ea6c
li t1, 0x0000f6b2
divu t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
divu t4, t1, t0
sw t4, 4(sp)
li t0, 0x000036c3
li t1, 0x0000e8ce
divu t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
divu t4, t1, t0
sw t4, 4(sp)
li t0, 0x76923b1a
li t1, 0x030f124c
div t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
div t4, t1, t0
sw t4, 4(sp)
li t0, 0xa2092f1c
li t1, 0xe58efc85
div t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
div t4, t1, t0
sw t4, 4(sp)
li t0, 0x469f4c69
li t1, 0x891e652c
div t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
divu t4, t1, t0
sw t4, 4(sp)
li t0, 0xa5ca3e3d
li t1, 0x239fe308
divu t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
divu t4, t1, t0
sw t4, 4(sp)
li t0, 0x5e7ba308
li t1, 0x2382a92e
divu t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
divu t4, t1, t0
sw t4, 4(sp)
li t0, 0x2c94b428
li t1, 0x94747496
rem t4, t0, t1
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
rem t4, t0, t1
sw t4, 4(sp)
li t0, 0x9450f1d1
li t1, 0x966300db
rem t4, t0, t1
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
rem t4, t0, t1
sw t4, 4(sp)
li t0, 0xd5a5fbf3
li t1, 0xe50a0eb0
rem t4, t0, t1
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
remu t4, t0, t1
sw t4, 4(sp)
li t0, 0xc1296e8b
li t1, 0x3c3ec00e
remu t4, t0, t1
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
remu t4, t0, t1
sw t4, 4(sp)
li t0, 0x6bc586de
li t1, 0x88467e96
remu t4, t0, t1
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
remu t4, t0, t1
sw t4, 4(sp)
li t0, 0x0000d55a
li t1, 0x000049b1
rem t4, t0, t1
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
rem t4, t0, t1
sw t4, 4(sp)
li t0, 0x0000d178
li t1, 0x00003b42
rem t4, t0, t1
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
rem t4, t0, t1
sw t4, 4(sp)
li t0, 0x0000b55f
li t1, 0x00008b3a
rem t4, t0, t1
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
remu t4, t0, t1
sw t4, 4(sp)
li t0, 0x000030c2
li t1, 0x00007e11
remu t4, t0, t1
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
remu t4, t0, t1
sw t4, 4(sp)
li t0, 0x0000a20d
li t1, 0x0000329b
remu t4, t0, t1
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
remu t4, t0, t1
sw t4, 4(sp)
