li t2, 0x00000000
li t0, 0x4200cd35
li t1, 0xfa17864e
p.mac t2, t1, t0
sw t2, 4(sp)
li t0, 0x6008703f
li t1, 0xf1af43bf
p.mac t2, t1, t0
sw t2, 4(sp)
li t0, 0xac1c319f
li t1, 0xe8130ce3
p.mac t2, t1, t0
sw t2, 4(sp)
li t0, 0x30503008
li t1, 0x9e887302
p.mac t2, t1, t0
sw t2, 4(sp)
li t0, 0x92403077
li t1, 0xf0a353c1
p.mac t2, t1, t0
sw t2, 4(sp)
li t0, 0x659c840c
li t1, 0x2edffe83
p.mac t2, t1, t0
sw t2, 4(sp)
li t0, 0x8d0580e3
li t1, 0xe7e0e0f3
p.msu t2, t1, t0
sw t2, 4(sp)
li t0, 0xc2bcd63f
li t1, 0x1c17128f
p.msu t2, t1, t0
sw t2, 4(sp)
li t0, 0x900702ce
li t1, 0x10b15701
p.msu t2, t1, t0
sw t2, 4(sp)
li t0, 0x843e00c0
li t1, 0xc7961d0
p.msu t2, t1, t0
sw t2, 4(sp)
li t0, 0xc6902a67
li t1, 0xc147980
p.msu t2, t1, t0
sw t2, 4(sp)
li t0, 0xcc81fc83
li t1, 0xf9842166
p.macsN t2, t1, t0, 0x1e
sw t2, 4(sp)
li t0, 0x20f00520
li t1, 0x3038016a
p.macsN t2, t1, t0, 0x02
sw t2, 4(sp)
li t0, 0x91eb2c85
li t1, 0xd347d8f7
p.macsN t2, t1, t0, 0x1d
sw t2, 4(sp)
li t0, 0x9479c07f
li t1, 0xd5103e46
p.macsN t2, t1, t0, 0x1d
sw t2, 4(sp)
li t0, 0x5008c6c4
li t1, 0x1fd14c2b
p.macsN t2, t1, t0, 0x02
sw t2, 4(sp)
li t0, 0x9a085623
li t1, 0xfc340177
p.machhsN t2, t1, t0, 0x1e
sw t2, 4(sp)
li t0, 0xc0cb2c10
li t1, 0xe1ef0050
p.machhsN t2, t1, t0, 0x01
sw t2, 4(sp)
li t0, 0xca88002c
li t1, 0x2f36a8e7
p.machhsN t2, t1, t0, 0x16
sw t2, 4(sp)
li t0, 0x68000020
li t1, 0x15201e61
p.machhsN t2, t1, t0, 0x09
sw t2, 4(sp)
li t0, 0xe029a008
li t1, 0x7000400
p.machhsN t2, t1, t0, 0x04
sw t2, 4(sp)
li t0, 0xa10ffc9f
li t1, 0xce88ef86
p.macsRN t2, t1, t0, 0x1b
sw t2, 4(sp)
li t0, 0xb34414c1
li t1, 0x71c71f10
p.macsRN t2, t1, t0, 0x1f
sw t2, 4(sp)
li t0, 0xa01f0243
li t1, 0xdc1803c3
p.macsRN t2, t1, t0, 0x00
sw t2, 4(sp)
li t0, 0x90dd0070
li t1, 0xcb86e823
p.macsRN t2, t1, t0, 0x1c
sw t2, 4(sp)
li t0, 0xb2397d00
li t1, 0x12884b05
p.macsRN t2, t1, t0, 0x03
sw t2, 4(sp)
li t0, 0x50fefc02
li t1, 0x658b6e7e
p.machhsRN t2, t1, t0, 0x1d
sw t2, 4(sp)
li t0, 0x400e74bc
li t1, 0x2df0e38d
p.machhsRN t2, t1, t0, 0x02
sw t2, 4(sp)
li t0, 0x604e86bd
li t1, 0x7fc1130d
p.machhsRN t2, t1, t0, 0x08
sw t2, 4(sp)
li t0, 0xc130fce1
li t1, 0xf1c75e9c
p.machhsRN t2, t1, t0, 0x17
sw t2, 4(sp)
li t0, 0x291f8111
li t1, 0xf945c018
p.machhsRN t2, t1, t0, 0x19
sw t2, 4(sp)
li t0, 0x6bd100f0
li t1, 0x2bc2639
p.machhsRN t2, t1, t0, 0x06
sw t2, 4(sp)
li t0, 0xd8034604
li t1, 0x3f7ce0cd
p.macuN t2, t1, t0, 0x07
sw t2, 4(sp)
li t0, 0xdc72f3c5
li t1, 0xf4638b4e
p.macuN t2, t1, t0, 0x18
sw t2, 4(sp)
li t0, 0xb298f303
li t1, 0x87367910
p.macuN t2, t1, t0, 0x0d
sw t2, 4(sp)
li t0, 0x88222060
li t1, 0x805b0006
p.macuN t2, t1, t0, 0x12
sw t2, 4(sp)
li t0, 0x5940f45f
li t1, 0x4995c144
p.macuN t2, t1, t0, 0x11
sw t2, 4(sp)
li t0, 0xca1170f8
li t1, 0x787dc602
p.machhuN t2, t1, t0, 0x0e
sw t2, 4(sp)
li t0, 0x3fbdf4fc
li t1, 0xf22a000b
p.machhuN t2, t1, t0, 0x1a
sw t2, 4(sp)
li t0, 0xf01237dd
li t1, 0x3c2d198a
p.machhuN t2, t1, t0, 0x05
sw t2, 4(sp)
li t0, 0x8007e080
li t1, 0x8619e80
p.machhuN t2, t1, t0, 0x0f
sw t2, 4(sp)
li t0, 0x78b0651b
li t1, 0x2c98664e
p.machhuN t2, t1, t0, 0x10
sw t2, 4(sp)
li t0, 0xc41008d2
li t1, 0xc7c3e3cf
p.macuRN t2, t1, t0, 0x0d
sw t2, 4(sp)
li t0, 0x341c38db
li t1, 0x867c70e4
p.macuRN t2, t1, t0, 0x12
sw t2, 4(sp)
li t0, 0x37cb8607
li t1, 0x8f859794
p.macuRN t2, t1, t0, 0x06
sw t2, 4(sp)
li t0, 0x72ec0081
li t1, 0x99cf5a07
p.macuRN t2, t1, t0, 0x19
sw t2, 4(sp)
li t0, 0xca327fd4
li t1, 0x14064463
p.macuRN t2, t1, t0, 0x1d
sw t2, 4(sp)
li t0, 0x40842eff
li t1, 0xa7bd859a
p.machhuRN t2, t1, t0, 0x02
sw t2, 4(sp)
li t0, 0xb040a18b
li t1, 0x13864933
p.machhuRN t2, t1, t0, 0x05
sw t2, 4(sp)
li t0, 0x50003cee
li t1, 0xc63588cf
p.machhuRN t2, t1, t0, 0x1a
sw t2, 4(sp)
li t0, 0xd811de04
li t1, 0x191fde0
p.machhuRN t2, t1, t0, 0x0f
sw t2, 4(sp)
li t0, 0xa84b780a
li t1, 0x1eac81e7
p.machhuRN t2, t1, t0, 0x10
sw t2, 4(sp)
li t0, 0xcb771165
li t1, 0xcb771165
mul t2, t1, t0
sw t2, 4(sp)
li t0, 0x34881165
li t1, 0xcb77ee9a
mul t2, t1, t0
sw t2, 4(sp)
li t0, 0x34881165
li t1, 0xcb77ee9a
mul t2, t1, t0
sw t2, 4(sp)
li t0, 0x34881165
li t1, 0xcb77ee9a
mul t2, t1, t0
sw t2, 4(sp)
li t0, 0x34881165
li t1, 0xcb77ee9a
mul t2, t1, t0
sw t2, 4(sp)
li t0, 0x34881165
li t1, 0xcb77ee9a
mul t2, t1, t0
sw t2, 4(sp)
li t0, 0x34881165
li t1, 0xcb77ee9a
mul t2, t1, t0
sw t2, 4(sp)
li t0, 0x34881165
li t1, 0xcb77ee9a
mul t2, t1, t0
sw t2, 4(sp)
li t0, 0x34881165
li t1, 0xcb77ee9a
mul t2, t1, t0
sw t2, 4(sp)
li t0, 0x34881165
li t1, 0xcb77ee9a
mul t2, t1, t0
sw t2, 4(sp)
mulh t2, t1, t0
sw t2, 4(sp)
li t0, 0xdf4ac73d
li t1, 0xdf4ac73d
mulh t2, t1, t0
sw t2, 4(sp)
li t0, 0x20b5c73d
li t1, 0xdf4a38c2
mulh t2, t1, t0
sw t2, 4(sp)
li t0, 0x20b5c73d
li t1, 0xdf4a38c2
mulh t2, t1, t0
sw t2, 4(sp)
li t0, 0x20b5c73d
li t1, 0xdf4a38c2
mulh t2, t1, t0
sw t2, 4(sp)
li t0, 0x20b5c73d
li t1, 0xdf4a38c2
mulh t2, t1, t0
sw t2, 4(sp)
li t0, 0x20b5c73d
li t1, 0xdf4a38c2
mulh t2, t1, t0
sw t2, 4(sp)
li t0, 0x20b5c73d
li t1, 0xdf4a38c2
mulh t2, t1, t0
sw t2, 4(sp)
li t0, 0x20b5c73d
li t1, 0xdf4a38c2
mulh t2, t1, t0
sw t2, 4(sp)
li t0, 0x20b5c73d
li t1, 0xdf4a38c2
mulh t2, t1, t0
sw t2, 4(sp)
li t0, 0x20b5c73d
li t1, 0xdf4a38c2
mulhsu t2, t1, t0
sw t2, 4(sp)
mulhsu t2, t1, t0
sw t2, 4(sp)
li t0, 0xf251c711
li t1, 0xf251c711
mulhsu t2, t1, t0
sw t2, 4(sp)
li t0, 0x0daec711
li t1, 0xf25138ee
mulhsu t2, t1, t0
sw t2, 4(sp)
li t0, 0x0daec711
li t1, 0xf25138ee
mulhsu t2, t1, t0
sw t2, 4(sp)
li t0, 0x0daec711
li t1, 0xf25138ee
mulhsu t2, t1, t0
sw t2, 4(sp)
li t0, 0x0daec711
li t1, 0xf25138ee
mulhsu t2, t1, t0
sw t2, 4(sp)
li t0, 0x0daec711
li t1, 0xf25138ee
mulhsu t2, t1, t0
sw t2, 4(sp)
li t0, 0x0daec711
li t1, 0xf25138ee
mulhsu t2, t1, t0
sw t2, 4(sp)
li t0, 0x0daec711
li t1, 0xf25138ee
mulhsu t2, t1, t0
sw t2, 4(sp)
li t0, 0x0daec711
li t1, 0xf25138ee
mulhu t2, t1, t0
sw t2, 4(sp)
li t0, 0x0daec711
li t1, 0xf25138ee
mulhu t2, t1, t0
sw t2, 4(sp)
mulhu t2, t1, t0
sw t2, 4(sp)
li t0, 0x14312c99
li t1, 0x14312c99
mulhu t2, t1, t0
sw t2, 4(sp)
li t0, 0xebce2c99
li t1, 0x1431d366
mulhu t2, t1, t0
sw t2, 4(sp)
li t0, 0xebce2c99
li t1, 0x1431d366
mulhu t2, t1, t0
sw t2, 4(sp)
li t0, 0xebce2c99
li t1, 0x1431d366
mulhu t2, t1, t0
sw t2, 4(sp)
li t0, 0xebce2c99
li t1, 0x1431d366
mulhu t2, t1, t0
sw t2, 4(sp)
li t0, 0xebce2c99
li t1, 0x1431d366
mulhu t2, t1, t0
sw t2, 4(sp)
li t0, 0xebce2c99
li t1, 0x1431d366
mulhu t2, t1, t0
sw t2, 4(sp)
li t0, 0xa1737e52
li t1, 0xf2a93747
p.mulhhs t2, t1, t0
sw t2, 4(sp)
li t0, 0x9cc7b691
li t1, 0x9d917529
p.mulhhs t2, t1, t0
sw t2, 4(sp)
li t0, 0x592c21e8
li t1, 0x1c5001ea
p.mulhhs t2, t1, t0
sw t2, 4(sp)
li t0, 0x90f9d9a8
li t1, 0xd2d13f67
p.mulhhs t2, t1, t0
sw t2, 4(sp)
li t0, 0xd20e4303
li t1, 0x92538009
p.mulhhs t2, t1, t0
sw t2, 4(sp)
li t0, 0x4a75b1ca
li t1, 0x1ac9205e
p.muls t2, t1, t0
sw t2, 4(sp)
li t0, 0xef901100
li t1, 0x9bceea6b
p.muls t2, t1, t0
sw t2, 4(sp)
li t0, 0x4fbb3d6b
li t1, 0x586e7a48
p.muls t2, t1, t0
sw t2, 4(sp)
li t0, 0xeb050143
li t1, 0x69f73e97
p.muls t2, t1, t0
sw t2, 4(sp)
li t0, 0xb4bf0155
li t1, 0xa8dbb228
p.muls t2, t1, t0
sw t2, 4(sp)
li t0, 0x980849b4
li t1, 0xd57cfa0d
p.mulhhsN t2, t1, t0, 0x1d
sw t2, 4(sp)
li t0, 0x7d579bdc
li t1, 0xfeb44816
p.mulhhsN t2, t1, t0, 0x02
sw t2, 4(sp)
li t0, 0xdc7423b9
li t1, 0x3a538750
p.mulhhsN t2, t1, t0, 0x03
sw t2, 4(sp)
li t0, 0x74ebc1a3
li t1, 0x48f75008
p.mulhhsN t2, t1, t0, 0x1c
sw t2, 4(sp)
li t0, 0x4a040a4e
li t1, 0x91f831bd
p.mulhhsN t2, t1, t0, 0x1f
sw t2, 4(sp)
li t0, 0x466824bb
li t1, 0xe1a7fbfe
p.mulsN t2, t1, t0, 0x00
sw t2, 4(sp)
li t0, 0x5712c083
li t1, 0xd9b1dd5b
p.mulsN t2, t1, t0, 0x03
sw t2, 4(sp)
li t0, 0xda64ae3d
li t1, 0x23db984b
p.mulsN t2, t1, t0, 0x1c
sw t2, 4(sp)
li t0, 0x94c7b282
li t1, 0x63bdb469
p.mulsN t2, t1, t0, 0x11
sw t2, 4(sp)
li t0, 0x6236a582
li t1, 0x04b89c8d
p.mulsN t2, t1, t0, 0x0e
sw t2, 4(sp)
li t0, 0x7d88631f
li t1, 0x83a4051a
p.mulhhu t2, t1, t0
sw t2, 4(sp)
li t0, 0xd36a78d0
li t1, 0x67d2d468
p.mulhhu t2, t1, t0
sw t2, 4(sp)
li t0, 0xbf0837d2
li t1, 0xb2885238
p.mulhhu t2, t1, t0
sw t2, 4(sp)
li t0, 0xc1f8dde8
li t1, 0xf2eba114
p.mulhhu t2, t1, t0
sw t2, 4(sp)
li t0, 0x2500827f
li t1, 0xf0b36741
p.mulhhu t2, t1, t0
sw t2, 4(sp)
li t0, 0x7e643d42
li t1, 0xa4cae669
p.mulu t2, t1, t0
sw t2, 4(sp)
li t0, 0x7f9c879e
li t1, 0x816b6ba2
p.mulu t2, t1, t0
sw t2, 4(sp)
li t0, 0x9f17bab0
li t1, 0x06fca13c
p.mulu t2, t1, t0
sw t2, 4(sp)
li t0, 0x0dc396f8
li t1, 0xbcf61127
p.mulu t2, t1, t0
sw t2, 4(sp)
li t0, 0xfdbf3e7a
li t1, 0xbe91e746
p.mulu t2, t1, t0
sw t2, 4(sp)
li t0, 0x53923326
li t1, 0x82192ca0
p.mulhhuN t2, t1, t0, 0x04
sw t2, 4(sp)
li t0, 0xd31d3641
li t1, 0xdc3c686b
p.mulhhuN t2, t1, t0, 0x1b
sw t2, 4(sp)
li t0, 0xf23141e4
li t1, 0xff7b5027
p.mulhhuN t2, t1, t0, 0x19
sw t2, 4(sp)
li t0, 0x8932ea18
li t1, 0xa80941a2
p.mulhhuN t2, t1, t0, 0x06
sw t2, 4(sp)
li t0, 0x021086f7
li t1, 0x770c9473
p.mulhhuN t2, t1, t0, 0x0c
sw t2, 4(sp)
li t0, 0xc9dc0a58
li t1, 0xaa1563f8
p.muluN t2, t1, t0, 0x13
sw t2, 4(sp)
li t0, 0xf2c2e8c7
li t1, 0xd8334e7c
p.muluN t2, t1, t0, 0x0d
sw t2, 4(sp)
li t0, 0x38094ce8
li t1, 0xe9ed4c83
p.muluN t2, t1, t0, 0x12
sw t2, 4(sp)
li t0, 0x7149d17c
li t1, 0xa6faea66
p.muluN t2, t1, t0, 0x1a
sw t2, 4(sp)
li t0, 0x83a228e3
li t1, 0x959a753c
p.muluN t2, t1, t0, 0x05
sw t2, 4(sp)
li t0, 0xf8ffc554
li t1, 0xed1d4f35
p.mulhhuRN t2, t1, t0, 0x1f
sw t2, 4(sp)
li t0, 0x701cce63
li t1, 0x91fb4eac
p.mulhhuRN t2, t1, t0, 0x00
sw t2, 4(sp)
li t0, 0x928a8ee9
li t1, 0xe5cd3ca7
p.mulhhuRN t2, t1, t0, 0x1d
sw t2, 4(sp)
li t0, 0x18e69831
li t1, 0x9f4a2f63
p.mulhhuRN t2, t1, t0, 0x02
sw t2, 4(sp)
li t0, 0xc0c4d7be
li t1, 0xf408dcc7
p.mulhhuRN t2, t1, t0, 0x04
sw t2, 4(sp)
li t0, 0x8242d82c
li t1, 0xd14d47ef
p.muluRN t2, t1, t0, 0x1b
sw t2, 4(sp)
li t0, 0x928fdf3c
li t1, 0x228c71be
p.muluRN t2, t1, t0, 0x1c
sw t2, 4(sp)
li t0, 0x94d36f0f
li t1, 0xf1a994e5
p.muluRN t2, t1, t0, 0x03
sw t2, 4(sp)
li t0, 0x67b45065
li t1, 0x092f37b2
p.muluRN t2, t1, t0, 0x16
sw t2, 4(sp)
li t0, 0x533b61b8
li t1, 0x68c31a8c
p.muluRN t2, t1, t0, 0x09
sw t2, 4(sp)
li t0, 0x7ae21b73
li t1, 0x70579da7
p.mulhhsRN t2, t1, t0, 0x0a
sw t2, 4(sp)
li t0, 0x2497f002
li t1, 0x5fbc0de6
p.mulhhsRN t2, t1, t0, 0x15
sw t2, 4(sp)
li t0, 0x0c084dad
li t1, 0x5d802c78
p.mulhhsRN t2, t1, t0, 0x1c
sw t2, 4(sp)
li t0, 0x6b2c7605
li t1, 0x730a1630
p.mulhhsRN t2, t1, t0, 0x03
sw t2, 4(sp)
li t0, 0xc57b1d36
li t1, 0xfb966db2
p.mulhhsRN t2, t1, t0, 0x16
sw t2, 4(sp)
li t0, 0x346b2865
li t1, 0xee7bf79b
p.mulsRN t2, t1, t0, 0x09
sw t2, 4(sp)
li t0, 0x7fe96e85
li t1, 0xd2c80726
p.mulsRN t2, t1, t0, 0x19
sw t2, 4(sp)
li t0, 0x5bfa0d8c
li t1, 0x7dc60f64
p.mulsRN t2, t1, t0, 0x06
sw t2, 4(sp)
li t0, 0x9e8eec90
li t1, 0xa48cfd90
p.mulsRN t2, t1, t0, 0x02
sw t2, 4(sp)
li t0, 0xaf942da3
li t1, 0x20586281
p.mulsRN t2, t1, t0, 0x1d
sw t2, 4(sp)
li t0, 0x9c7fb1b7
li t1, 0x2a59f20b
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.sc.h t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.sc.h t2, t1, t0
sw t2, 4(sp)
li t0, 0x7864dff3
li t1, 0x0b5c6a92
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.sc.h t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.sc.h t2, t1, t0
sw t2, 4(sp)
li t0, 0xd40c501c
li t1, 0x6a9e9a8b
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.sc.h t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.sci.h t2, t1, 0x13
sw t2, 4(sp)
li t0, 0x0a53448f
li t1, 0xa475db54
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.sci.h t2, t1, 0x04
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.sci.h t2, t1, 0x1b
sw t2, 4(sp)
li t0, 0x0467912b
li t1, 0xd737c79e
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.sci.h t2, t1, 0x08
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.sci.h t2, t1, 0x17
sw t2, 4(sp)
li t0, 0x6a3ec0ab
li t1, 0x372bac10
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x5934e18e
li t1, 0xad7f6758
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.b t2, t1, t0
sw t2, 4(sp)
li t0, 0xc74f7e61
li t1, 0xd6808568
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x9e824467
li t1, 0x678ad48d
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.sc.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x80fc2879
li t1, 0xe9397e67
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.sc.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x07faba17
li t1, 0x17c1ee54
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.sci.b t2, t1, 0x1c
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.sci.b t2, t1, 0x03
sw t2, 4(sp)
li t0, 0x5d046530
li t1, 0xf6eb6881
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.sci.b t2, t1, 0x1e
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.sci.b t2, t1, 0x01
sw t2, 4(sp)
li t0, 0xb5b7d337
li t1, 0x5d066432
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.sci.b t2, t1, 0x13
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.h t2, t1, t0
sw t2, 4(sp)
li t0, 0xa6b36c8a
li t1, 0x75a00a8a
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.h t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.h t2, t1, t0
sw t2, 4(sp)
li t0, 0x8914c68b
li t1, 0x70636baa
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.h t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.h t2, t1, t0
sw t2, 4(sp)
li t0, 0x5cf2e666
li t1, 0xcbf2a0b3
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.sc.h t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.sc.h t2, t1, t0
sw t2, 4(sp)
li t0, 0x5eae2cf3
li t1, 0xed1220ae
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.sc.h t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.sc.h t2, t1, t0
sw t2, 4(sp)
li t0, 0xfd8ef50a
li t1, 0x3499aab0
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.sc.h t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.sci.h t2, t1, 0x1d
sw t2, 4(sp)
li t0, 0x242a8497
li t1, 0x27718949
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.sci.h t2, t1, 0x18
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.sci.h t2, t1, 0x07
sw t2, 4(sp)
li t0, 0x5eea5b29
li t1, 0x4a56541b
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.sci.h t2, t1, 0x0b
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.sci.h t2, t1, 0x14
sw t2, 4(sp)
li t0, 0x34e34270
li t1, 0x8816024f
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.b t2, t1, t0
sw t2, 4(sp)
li t0, 0xae7c17c2
li t1, 0xf3ef8176
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.b t2, t1, t0
sw t2, 4(sp)
li t0, 0xae96b792
li t1, 0x7ced03f5
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0xc592ad3b
li t1, 0x9cf8556f
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.sc.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0xa881627a
li t1, 0xceadbd5e
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.sc.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0xb2ec0b72
li t1, 0x42e58eb9
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.sci.b t2, t1, 0x07
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.sci.b t2, t1, 0x18
sw t2, 4(sp)
li t0, 0x86374abd
li t1, 0xd8d2ca98
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.sci.b t2, t1, 0x12
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.sci.b t2, t1, 0x0d
sw t2, 4(sp)
li t0, 0x4ce88405
li t1, 0xa86ddfba
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.sci.b t2, t1, 0x1a
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.h t2, t1, t0
sw t2, 4(sp)
li t0, 0xcbb5dafb
li t1, 0x5ed2ba4d
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.h t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.h t2, t1, t0
sw t2, 4(sp)
li t0, 0x47fc7f11
li t1, 0x70d14bdc
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.h t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.h t2, t1, t0
sw t2, 4(sp)
li t0, 0xae9533d4
li t1, 0x9a99395e
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.sci.h t2, t1, 0x08
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.sci.h t2, t1, 0x17
sw t2, 4(sp)
li t0, 0x049f53bd
li t1, 0x53043b0d
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.sci.h t2, t1, 0x1d
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.sci.h t2, t1, 0x02
sw t2, 4(sp)
li t0, 0xa18ea6f7
li t1, 0x6817fa9f
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.sci.h t2, t1, 0x1e
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x70df16ee
li t1, 0x797b6d4e
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.b t2, t1, t0
sw t2, 4(sp)
li t0, 0xd9dbd179
li t1, 0x014c4088
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x3a6c553b
li t1, 0xe89ac0a7
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.sc.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x9f2250bb
li t1, 0x8bfa8102
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.sc.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0xb079b230
li t1, 0x471984db
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.sc.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.sci.b t2, t1, 0x10
sw t2, 4(sp)
li t0, 0x63218c06
li t1, 0xda14862b
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.sci.b t2, t1, 0x0d
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.sci.b t2, t1, 0x12
sw t2, 4(sp)
li t0, 0xde0b33ef
li t1, 0xb81320ec
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.sci.b t2, t1, 0x1f
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.sci.b t2, t1, 0x00
sw t2, 4(sp)
li t0, 0xa5a5a5a5
li t1, 0x5a5a5a5a
mul t4, t1, t0
sw t4, 4(sp)
li t0, 0xc3c3c3c3
li t1, 0x3c3c3c3c
mul t4, t1, t0
sw t4, 4(sp)
li t0, 0x18181818
li t1, 0x81818181
mul t4, t1, t0
sw t4, 4(sp)
li t0, 0x00000000
li t1, 0x00000000
mul t4, t1, t0
sw t4, 4(sp)
li t0, 0x00000000
li t1, 0x00000010
mul t4, t1, t0
sw t4, 4(sp)
li t0, 0x00000100
li t1, 0x00000000
mul t4, t1, t0
sw t4, 4(sp)
li t0, 0xffffffff
li t1, 0xffffffff
mulh t4, t1, t0
sw t4, 4(sp)
li t0, 0xffff0000
li t1, 0x0000ffff
mul t4, t1, t0
sw t4, 4(sp)
li t0, 0xffff0000
li t1, 0x0000ffff
p.mac t4, t1, t0
sw t4, 4(sp)
li t0, 0x00000000
li t1, 0xffffffff
p.mac t4, t1, t0
sw t4, 4(sp)
li t1, 0x00000000
li t0, 0xffffffff
p.msu t4, t1, t0
sw t4, 4(sp)
li t0, 0xa5a5a5a5
li t1, 0x5a5a5a5a
mulh t4, t1, t0
sw t4, 4(sp)
li t0, 0xc3c3c3c3
li t1, 0x3c3c3c3c
mulhsu t4, t1, t0
sw t4, 4(sp)
li t0, 0x18181818
li t1, 0x81818181
mulh t4, t1, t0
sw t4, 4(sp)
li t0, 0x0f0f0f0f
li t1, 0xf0f0f0f0
p.mulhhs t4, t1, t0
sw t4, 4(sp)
li t0, 0x8370a303
xori t1, t0, 0xffffffff
pv.dotup.sc.h t2, t1, t0
sw t2, 4(sp)
li t0, 0x1e909040
xori t1, t0, 0xffffffff
pv.dotup.sc.h t2, t1, t0
sw t2, 4(sp)
li t0, 0x070d7bad
xori t1, t0, 0xffffffff
pv.dotup.sc.h t2, t1, t0
sw t2, 4(sp)
li t0, 0x4a1bfad5
xori t1, t0, 0xffffffff
pv.dotup.sci.h t2, t1, 0x1c
sw t2, 4(sp)
li t0, 0x32710643
xori t1, t0, 0xffffffff
pv.dotup.sci.h t2, t1, 0x0a
sw t2, 4(sp)
li t0, 0xb6b78609
xori t1, t0, 0xffffffff
pv.dotup.b t2, t1, t0
sw t2, 4(sp)
li t0, 0xf77b688f
xori t1, t0, 0xffffffff
pv.dotup.b t2, t1, t0
sw t2, 4(sp)
li t0, 0xe9c4cce4
xori t1, t0, 0xffffffff
pv.dotup.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x0cc70775
xori t1, t0, 0xffffffff
pv.dotup.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x1d801f01
xori t1, t0, 0xffffffff
pv.dotup.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x762aaa10
xori t1, t0, 0xffffffff
pv.dotup.sci.b t2, t1, 0x0a
sw t2, 4(sp)
li t0, 0xf0d4c7a0
xori t1, t0, 0xffffffff
pv.dotup.sci.b t2, t1, 0x0a
sw t2, 4(sp)
li t0, 0xaf0fdf7a
xori t1, t0, 0xffffffff
pv.dotup.sci.b t2, t1, 0x14
sw t2, 4(sp)
li t0, 0x404ddc00
xori t1, t0, 0xffffffff
pv.dotusp.h t2, t1, t0
sw t2, 4(sp)
li t0, 0x549b0f61
xori t1, t0, 0xffffffff
pv.dotusp.h t2, t1, t0
sw t2, 4(sp)
li t0, 0x629a3e87
xori t1, t0, 0xffffffff
pv.dotusp.sc.h t2, t1, t0
sw t2, 4(sp)
li t0, 0xf7dcbd9e
xori t1, t0, 0xffffffff
pv.dotusp.sc.h t2, t1, t0
sw t2, 4(sp)
li t0, 0x1ab99fd6
xori t1, t0, 0xffffffff
pv.dotusp.sc.h t2, t1, t0
sw t2, 4(sp)
li t0, 0xefb02db6
xori t1, t0, 0xffffffff
pv.dotusp.sci.h t2, t1, 0x0c
sw t2, 4(sp)
li t0, 0x97d91ccf
xori t1, t0, 0xffffffff
pv.dotusp.sci.h t2, t1, 0x16
sw t2, 4(sp)
li t0, 0xac856391
xori t1, t0, 0xffffffff
pv.dotusp.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x77df256f
xori t1, t0, 0xffffffff
pv.dotusp.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x7c6e71ee
xori t1, t0, 0xffffffff
pv.dotusp.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x7374ef6c
xori t1, t0, 0xffffffff
pv.dotusp.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0xd6e80333
xori t1, t0, 0xffffffff
pv.dotusp.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x7f7d80d5
xori t1, t0, 0xffffffff
pv.dotusp.sci.b t2, t1, 0x17
sw t2, 4(sp)
li t0, 0x9291a9b8
xori t1, t0, 0xffffffff
pv.dotusp.sci.b t2, t1, 0x0a
sw t2, 4(sp)
li t0, 0x86717c29
xori t1, t0, 0xffffffff
pv.dotusp.sci.b t2, t1, 0x14
sw t2, 4(sp)
li t0, 0x73f05f9d
xori t1, t0, 0xffffffff
pv.dotsp.h t2, t1, t0
sw t2, 4(sp)
li t0, 0xf2aa5f4c
xori t1, t0, 0xffffffff
pv.dotsp.h t2, t1, t0
sw t2, 4(sp)
li t0, 0xadfc4a21
xori t1, t0, 0xffffffff
pv.dotsp.sci.h t2, t1, 0x1b
sw t2, 4(sp)
li t0, 0x5bbda4b6
xori t1, t0, 0xffffffff
pv.dotsp.sci.h t2, t1, 0x06
sw t2, 4(sp)
li t0, 0xe051e48f
xori t1, t0, 0xffffffff
pv.dotsp.sci.h t2, t1, 0x08
sw t2, 4(sp)
li t0, 0xeea7ab24
xori t1, t0, 0xffffffff
pv.dotsp.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x95a3d5e7
xori t1, t0, 0xffffffff
pv.dotsp.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x18e36ec1
xori t1, t0, 0xffffffff
pv.dotsp.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x4ede0547
xori t1, t0, 0xffffffff
pv.dotsp.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0xfbec9611
xori t1, t0, 0xffffffff
pv.dotsp.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x6d6083f8
xori t1, t0, 0xffffffff
pv.dotsp.sci.b t2, t1, 0x0f
sw t2, 4(sp)
li t0, 0x1ad33c9e
xori t1, t0, 0xffffffff
pv.dotsp.sci.b t2, t1, 0x0c
sw t2, 4(sp)
li t1, 0x0000adfb
xori t0, t1, 0xffffffff
pv.dotup.sc.h t2, t1, t0
sw t2, 4(sp)
li t1, 0x00005f76
xori t0, t1, 0xffffffff
pv.dotup.sc.h t2, t1, t0
sw t2, 4(sp)
li t1, 0x0000736d
xori t0, t1, 0xffffffff
pv.dotup.sc.h t2, t1, t0
sw t2, 4(sp)
li t1, 0x0000613c
xori t0, t1, 0xffffffff
pv.dotup.sci.h t2, t1, 0x01
sw t2, 4(sp)
li t1, 0x000022e6
xori t0, t1, 0xffffffff
pv.dotup.sci.h t2, t1, 0x07
sw t2, 4(sp)
li t1, 0x000082c5
xori t0, t1, 0xffffffff
pv.dotup.b t2, t1, t0
sw t2, 4(sp)
li t1, 0x0000dac6
xori t0, t1, 0xffffffff
pv.dotup.b t2, t1, t0
sw t2, 4(sp)
li t1, 0x00009956
xori t0, t1, 0xffffffff
pv.dotup.b t2, t1, t0
sw t2, 4(sp)
li t1, 0x00000c4c
xori t0, t1, 0xffffffff
pv.dotup.sc.b t2, t1, t0
sw t2, 4(sp)
li t1, 0x00007fc4
xori t0, t1, 0xffffffff
pv.dotup.sc.b t2, t1, t0
sw t2, 4(sp)
li t1, 0x00005d99
xori t0, t1, 0xffffffff
pv.dotup.sci.b t2, t1, 0x09
sw t2, 4(sp)
li t1, 0x0000f5ed
xori t0, t1, 0xffffffff
pv.dotup.sci.b t2, t1, 0x06
sw t2, 4(sp)
li t1, 0x00002fee
xori t0, t1, 0xffffffff
pv.dotup.sci.b t2, t1, 0x0a
sw t2, 4(sp)
li t1, 0x000032b2
xori t0, t1, 0xffffffff
pv.dotusp.h t2, t1, t0
sw t2, 4(sp)
li t1, 0x0000312e
xori t0, t1, 0xffffffff
pv.dotusp.h t2, t1, t0
sw t2, 4(sp)
li t1, 0x00004dce
xori t0, t1, 0xffffffff
pv.dotusp.sc.h t2, t1, t0
sw t2, 4(sp)
li t1, 0x00001f9f
xori t0, t1, 0xffffffff
pv.dotusp.sc.h t2, t1, t0
sw t2, 4(sp)
li t1, 0x000030aa
xori t0, t1, 0xffffffff
pv.dotusp.sc.h t2, t1, t0
sw t2, 4(sp)
li t1, 0x00001a69
xori t0, t1, 0xffffffff
pv.dotusp.sci.h t2, t1, 0x0a
sw t2, 4(sp)
li t1, 0x00002893
xori t0, t1, 0xffffffff
pv.dotusp.sci.h t2, t1, 0x0b
sw t2, 4(sp)
li t1, 0x000085ca
xori t0, t1, 0xffffffff
pv.dotusp.b t2, t1, t0
sw t2, 4(sp)
li t1, 0x0000492a
xori t0, t1, 0xffffffff
pv.dotusp.b t2, t1, t0
sw t2, 4(sp)
li t1, 0x0000fa63
xori t0, t1, 0xffffffff
pv.dotusp.b t2, t1, t0
sw t2, 4(sp)
li t1, 0x00007cb9
xori t0, t1, 0xffffffff
pv.dotusp.sc.b t2, t1, t0
sw t2, 4(sp)
li t1, 0x00002494
xori t0, t1, 0xffffffff
pv.dotusp.sc.b t2, t1, t0
sw t2, 4(sp)
li t1, 0x00005924
xori t0, t1, 0xffffffff
pv.dotusp.sci.b t2, t1, 0x0b
sw t2, 4(sp)
li t1, 0x00004d37
xori t0, t1, 0xffffffff
pv.dotusp.sci.b t2, t1, 0x02
sw t2, 4(sp)
li t1, 0x0000c4f9
xori t0, t1, 0xffffffff
pv.dotusp.sci.b t2, t1, 0x12
sw t2, 4(sp)
li t1, 0x000010e4
xori t0, t1, 0xffffffff
pv.dotsp.h t2, t1, t0
sw t2, 4(sp)
li t1, 0x00008a06
xori t0, t1, 0xffffffff
pv.dotsp.h t2, t1, t0
sw t2, 4(sp)
li t1, 0x000066fb
xori t0, t1, 0xffffffff
pv.dotsp.sci.h t2, t1, 0x04
sw t2, 4(sp)
li t1, 0x0000c850
xori t0, t1, 0xffffffff
pv.dotsp.sci.h t2, t1, 0x10
sw t2, 4(sp)
li t1, 0x0000a529
xori t0, t1, 0xffffffff
pv.dotsp.sci.h t2, t1, 0x08
sw t2, 4(sp)
li t1, 0x00002c9c
xori t0, t1, 0xffffffff
pv.dotsp.b t2, t1, t0
sw t2, 4(sp)
li t1, 0x0000252d
xori t0, t1, 0xffffffff
pv.dotsp.b t2, t1, t0
sw t2, 4(sp)
li t1, 0x0000218f
xori t0, t1, 0xffffffff
pv.dotsp.sc.b t2, t1, t0
sw t2, 4(sp)
li t1, 0x0000f0b8
xori t0, t1, 0xffffffff
pv.dotsp.sc.b t2, t1, t0
sw t2, 4(sp)
li t1, 0x0000e0fb
xori t0, t1, 0xffffffff
pv.dotsp.sc.b t2, t1, t0
sw t2, 4(sp)
li t1, 0x00003456
xori t0, t1, 0xffffffff
pv.dotsp.sci.b t2, t1, 0x13
sw t2, 4(sp)
li t1, 0x00009c16
xori t0, t1, 0xffffffff
pv.dotsp.sci.b t2, t1, 0x14
sw t2, 4(sp)
