li t0, 1
li t1, 0xFFFFFFFF

add t2, t1, t0
sub t3, t1, t0
sw t2, 4(sp)
sw t3, 4(sp)

slt t4, t1, t0
sltu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)

xor t2, t1, t0
or t3, t1, t0
and t4, t1, t0
sw t2, 4(sp)
sw t3, 4(sp)
sw t4, 4(sp)

sll t4, t1, t0
srl t5, t1, t0
sra t6, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
sw t6, 4(sp)


// IMM

addi t2, t0, 0xff
addi t3, t0, 0xff
sw t2, 4(sp)
sw t3, 4(sp)

slti t4, t0, 0xff
sltiu t5,t0, 0xff
sw t4, 4(sp)
sw t5, 4(sp)


xori t2, t0, 0xff
ori t3, t0, 0xff
andi t4, t0, 0xff
sw t2, 4(sp)
sw t3, 4(sp)
sw t4, 4(sp)


slli t4, t0, 0xa
srli t5, t0, 0xb
srai t6, t0, 0xc
sw t4, 4(sp)
sw t5, 4(sp)
sw t6, 4(sp)


li t0, 0xFFFFFFFF

add t2, t1, t0
sub t3, t1, t0
sw t2, 4(sp)
sw t3, 4(sp)

slt t4, t1, t0
sltu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)

xor t2, t1, t0
or t3, t1, t0
and t4, t1, t0
sw t2, 4(sp)
sw t3, 4(sp)
sw t4, 4(sp)

sll t4, t1, t0
srl t5, t1, t0
sra t6, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
sw t6, 4(sp)

// IMM

addi t2, t0, 0xff
addi t3, t0, 0xff
sw t2, 4(sp)
sw t3, 4(sp)

slti t4, t0, 0xff
sltiu t5,t0, 0xff
sw t4, 4(sp)
sw t5, 4(sp)

xori t2, t0, 0xff
ori t3, t0, 0xff
andi t4, t0, 0xff
sw t2, 4(sp)
sw t3, 4(sp)
sw t4, 4(sp)

slli t4, t0, 0xa
srli t5, t0, 0xb
srai t6, t0, 0xc
sw t4, 4(sp)
sw t5, 4(sp)
sw t6, 4(sp)

li t0, 0

add t2, t1, t0
sub t3, t1, t0
sw t2, 4(sp)
sw t3, 4(sp)

slt t4, t1, t0
sltu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)

xor t2, t1, t0
or t3, t1, t0
and t4, t1, t0
sw t2, 4(sp)
sw t3, 4(sp)
sw t4, 4(sp)

sll t4, t1, t0
srl t5, t1, t0
sra t6, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
sw t6, 4(sp)

// IMM

addi t2, t0, 0xff
addi t3, t0, 0xff
sw t2, 4(sp)
sw t3, 4(sp)

slti t4, t0, 0xff
sltiu t5,t0, 0xff
sw t4, 4(sp)
sw t5, 4(sp)

xori t2, t0, 0xff
ori t3, t0, 0xff
andi t4, t0, 0xff
sw t2, 4(sp)
sw t3, 4(sp)
sw t4, 4(sp)

slli t4, t0, 0xc
srli t5, t0, 0xb
srai t6, t0, 0xa
sw t4, 4(sp)
sw t5, 4(sp)
sw t6, 4(sp)

li t1, 1

add t2, t1, t0
sub t3, t1, t0
sw t2, 4(sp)
sw t3, 4(sp)

slt t4, t1, t0
sltu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)

xor t2, t1, t0
or t3, t1, t0
and t4, t1, t0
sw t2, 4(sp)
sw t3, 4(sp)
sw t4, 4(sp)

sll t4, t1, t0
srl t5, t1, t0
sra t6, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
sw t6, 4(sp)

li t1, 0

add t2, t1, t0
sub t3, t1, t0
sw t2, 4(sp)
sw t3, 4(sp)

slt t4, t1, t0
sltu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)

xor t2, t1, t0
or t3, t1, t0
and t4, t1, t0
sw t2, 4(sp)
sw t3, 4(sp)
sw t4, 4(sp)

sll t4, t1, t0
srl t5, t1, t0
sra t6, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
sw t6, 4(sp)

