li ra, 0x00000000
li t0, 0x00000000
li t1, 0x00000000
li t2, 0x00000000
li s0, 0x00000000
li s1, 0x00000000
li a0, 0x00000000
li a1, 0x00000000
li a2, 0x00000000
li a3, 0x00000000
li a4, 0x00000000
li a5, 0x00000000
li a6, 0x00000000
li a7, 0x00000000
li s2, 0x00000000
li s3, 0x00000000
li s4, 0x00000000
li s5, 0x00000000
li s6, 0x00000000
li s7, 0x00000000
li s8, 0x00000000
li s9, 0x00000000
li s10, 0x00000000
li s11, 0x00000000
li t3, 0x00000000
li t4, 0x00000000
li t5, 0x00000000
li t6, 0x00000000
sw ra, 0(sp)
li ra, 0xffffffff
sw t0, 0(sp)
li t0, 0xffffffff
sw t1, 0(sp)
li t1, 0xffffffff
sw t2, 0(sp)
li t2, 0xffffffff
sw s0, 0(sp)
li s0, 0xffffffff
sw s1, 0(sp)
li s1, 0xffffffff
sw a0, 0(sp)
li a0, 0xffffffff
sw a1, 0(sp)
li a1, 0xffffffff
sw a2, 0(sp)
li a2, 0xffffffff
sw a3, 0(sp)
li a3, 0xffffffff
sw a4, 0(sp)
li a4, 0xffffffff
sw a5, 0(sp)
li a5, 0xffffffff
sw a6, 0(sp)
li a6, 0xffffffff
sw a7, 0(sp)
li a7, 0xffffffff
sw s2, 0(sp)
li s2, 0xffffffff
sw s3, 0(sp)
li s3, 0xffffffff
sw s4, 0(sp)
li s4, 0xffffffff
sw s5, 0(sp)
li s5, 0xffffffff
sw s6, 0(sp)
li s6, 0xffffffff
sw s7, 0(sp)
li s7, 0xffffffff
sw s8, 0(sp)
li s8, 0xffffffff
sw s9, 0(sp)
li s9, 0xffffffff
sw s10, 0(sp)
li s10, 0xffffffff
sw s11, 0(sp)
li s11, 0xffffffff
sw t3, 0(sp)
li t3, 0xffffffff
sw t4, 0(sp)
li t4, 0xffffffff
sw t5, 0(sp)
li t5, 0xffffffff
sw t6, 0(sp)
li t6, 0xffffffff
sw t6, 0(sp)
li t6, 0x00000000
sw t6, 0(sp)
sw t5, 0(sp)
li t5, 0x00000000
sw t5, 0(sp)
sw t4, 0(sp)
li t4, 0x00000000
sw t4, 0(sp)
sw t3, 0(sp)
li t3, 0x00000000
sw t3, 0(sp)
sw s11, 0(sp)
li s11, 0x00000000
sw s11, 0(sp)
sw s10, 0(sp)
li s10, 0x00000000
sw s10, 0(sp)
sw s9, 0(sp)
li s9, 0x00000000
sw s9, 0(sp)
sw s8, 0(sp)
li s8, 0x00000000
sw s8, 0(sp)
sw s7, 0(sp)
li s7, 0x00000000
sw s7, 0(sp)
sw s6, 0(sp)
li s6, 0x00000000
sw s6, 0(sp)
sw s5, 0(sp)
li s5, 0x00000000
sw s5, 0(sp)
sw s4, 0(sp)
li s4, 0x00000000
sw s4, 0(sp)
sw s3, 0(sp)
li s3, 0x00000000
sw s3, 0(sp)
sw s2, 0(sp)
li s2, 0x00000000
sw s2, 0(sp)
sw a7, 0(sp)
li a7, 0x00000000
sw a7, 0(sp)
sw a6, 0(sp)
li a6, 0x00000000
sw a6, 0(sp)
sw a5, 0(sp)
li a5, 0x00000000
sw a5, 0(sp)
sw a4, 0(sp)
li a4, 0x00000000
sw a4, 0(sp)
sw a3, 0(sp)
li a3, 0x00000000
sw a3, 0(sp)
sw a2, 0(sp)
li a2, 0x00000000
sw a2, 0(sp)
sw a1, 0(sp)
li a1, 0x00000000
sw a1, 0(sp)
sw a0, 0(sp)
li a0, 0x00000000
sw a0, 0(sp)
sw s1, 0(sp)
li s1, 0x00000000
sw s1, 0(sp)
sw s0, 0(sp)
li s0, 0x00000000
sw s0, 0(sp)
sw t2, 0(sp)
li t2, 0x00000000
sw t2, 0(sp)
sw t1, 0(sp)
li t1, 0x00000000
sw t1, 0(sp)
sw t0, 0(sp)
li t0, 0x00000000
sw t0, 0(sp)
sw ra, 0(sp)
li ra, 0x00000000
sw ra, 0(sp)
li ra, 0x00000000
li t0, 0x00000000
li t1, 0x00000000
li t2, 0x00000000
li s0, 0x00000000
li s1, 0x00000000
li a0, 0x00000000
li a1, 0x00000000
li a2, 0x00000000
li a3, 0x00000000
li a4, 0x00000000
li a5, 0x00000000
li a6, 0x00000000
li a7, 0x00000000
li s2, 0x00000000
li s3, 0x00000000
li s4, 0x00000000
li s5, 0x00000000
li s6, 0x00000000
li s7, 0x00000000
li s8, 0x00000000
li s9, 0x00000000
li s10, 0x00000000
li s11, 0x00000000
li t3, 0x00000000
li t4, 0x00000000
li t5, 0x00000000
li t6, 0x00000000
add ra, x0, ra
sw ra, 0(sp)
li ra, 0xffffffff
add t0, x0, t0
sw t0, 0(sp)
li t0, 0xffffffff
add t1, x0, t1
sw t1, 0(sp)
li t1, 0xffffffff
add t2, x0, t2
sw t2, 0(sp)
li t2, 0xffffffff
add s0, x0, s0
sw s0, 0(sp)
li s0, 0xffffffff
add s1, x0, s1
sw s1, 0(sp)
li s1, 0xffffffff
add a0, x0, a0
sw a0, 0(sp)
li a0, 0xffffffff
add a1, x0, a1
sw a1, 0(sp)
li a1, 0xffffffff
add a2, x0, a2
sw a2, 0(sp)
li a2, 0xffffffff
add a3, x0, a3
sw a3, 0(sp)
li a3, 0xffffffff
add a4, x0, a4
sw a4, 0(sp)
li a4, 0xffffffff
add a5, x0, a5
sw a5, 0(sp)
li a5, 0xffffffff
add a6, x0, a6
sw a6, 0(sp)
li a6, 0xffffffff
add a7, x0, a7
sw a7, 0(sp)
li a7, 0xffffffff
add s2, x0, s2
sw s2, 0(sp)
li s2, 0xffffffff
add s3, x0, s3
sw s3, 0(sp)
li s3, 0xffffffff
add s4, x0, s4
sw s4, 0(sp)
li s4, 0xffffffff
add s5, x0, s5
sw s5, 0(sp)
li s5, 0xffffffff
add s6, x0, s6
sw s6, 0(sp)
li s6, 0xffffffff
add s7, x0, s7
sw s7, 0(sp)
li s7, 0xffffffff
add s8, x0, s8
sw s8, 0(sp)
li s8, 0xffffffff
add s9, x0, s9
sw s9, 0(sp)
li s9, 0xffffffff
add s10, x0, s10
sw s10, 0(sp)
li s10, 0xffffffff
add s11, x0, s11
sw s11, 0(sp)
li s11, 0xffffffff
add t3, x0, t3
sw t3, 0(sp)
li t3, 0xffffffff
add t4, x0, t4
sw t4, 0(sp)
li t4, 0xffffffff
add t5, x0, t5
sw t5, 0(sp)
li t5, 0xffffffff
add t6, x0, t6
sw t6, 0(sp)
li t6, 0xffffffff
add t6, x0, t6
sw t6, 0(sp)
li t6, 0x00000000
add t6, x0, t6
sw t6, 0(sp)
add t5, x0, t5
sw t5, 0(sp)
li t5, 0x00000000
add t5, x0, t5
sw t5, 0(sp)
add t4, x0, t4
sw t4, 0(sp)
li t4, 0x00000000
add t4, x0, t4
sw t4, 0(sp)
add t3, x0, t3
sw t3, 0(sp)
li t3, 0x00000000
add t3, x0, t3
sw t3, 0(sp)
add s11, x0, s11
sw s11, 0(sp)
li s11, 0x00000000
add s11, x0, s11
sw s11, 0(sp)
add s10, x0, s10
sw s10, 0(sp)
li s10, 0x00000000
add s10, x0, s10
sw s10, 0(sp)
add s9, x0, s9
sw s9, 0(sp)
li s9, 0x00000000
add s9, x0, s9
sw s9, 0(sp)
add s8, x0, s8
sw s8, 0(sp)
li s8, 0x00000000
add s8, x0, s8
sw s8, 0(sp)
add s7, x0, s7
sw s7, 0(sp)
li s7, 0x00000000
add s7, x0, s7
sw s7, 0(sp)
add s6, x0, s6
sw s6, 0(sp)
li s6, 0x00000000
add s6, x0, s6
sw s6, 0(sp)
add s5, x0, s5
sw s5, 0(sp)
li s5, 0x00000000
add s5, x0, s5
sw s5, 0(sp)
add s4, x0, s4
sw s4, 0(sp)
li s4, 0x00000000
add s4, x0, s4
sw s4, 0(sp)
add s3, x0, s3
sw s3, 0(sp)
li s3, 0x00000000
add s3, x0, s3
sw s3, 0(sp)
add s2, x0, s2
sw s2, 0(sp)
li s2, 0x00000000
add s2, x0, s2
sw s2, 0(sp)
add a7, x0, a7
sw a7, 0(sp)
li a7, 0x00000000
add a7, x0, a7
sw a7, 0(sp)
add a6, x0, a6
sw a6, 0(sp)
li a6, 0x00000000
add a6, x0, a6
sw a6, 0(sp)
add a5, x0, a5
sw a5, 0(sp)
li a5, 0x00000000
add a5, x0, a5
sw a5, 0(sp)
add a4, x0, a4
sw a4, 0(sp)
li a4, 0x00000000
add a4, x0, a4
sw a4, 0(sp)
add a3, x0, a3
sw a3, 0(sp)
li a3, 0x00000000
add a3, x0, a3
sw a3, 0(sp)
add a2, x0, a2
sw a2, 0(sp)
li a2, 0x00000000
add a2, x0, a2
sw a2, 0(sp)
add a1, x0, a1
sw a1, 0(sp)
li a1, 0x00000000
add a1, x0, a1
sw a1, 0(sp)
add a0, x0, a0
sw a0, 0(sp)
li a0, 0x00000000
add a0, x0, a0
sw a0, 0(sp)
add s1, x0, s1
sw s1, 0(sp)
li s1, 0x00000000
add s1, x0, s1
sw s1, 0(sp)
add s0, x0, s0
sw s0, 0(sp)
li s0, 0x00000000
add s0, x0, s0
sw s0, 0(sp)
add t2, x0, t2
sw t2, 0(sp)
li t2, 0x00000000
add t2, x0, t2
sw t2, 0(sp)
add t1, x0, t1
sw t1, 0(sp)
li t1, 0x00000000
add t1, x0, t1
sw t1, 0(sp)
add t0, x0, t0
sw t0, 0(sp)
li t0, 0x00000000
add t0, x0, t0
sw t0, 0(sp)
add ra, x0, ra
sw ra, 0(sp)
li ra, 0x00000000
add ra, x0, ra
sw ra, 0(sp)
li ra, 0x00000000
li t0, 0x00000000
li t1, 0x00000000
li t2, 0x00000000
li s0, 0x00000000
li s1, 0x00000000
li a0, 0x00000000
li a1, 0x00000000
li a2, 0x00000000
li a3, 0x00000000
li a4, 0x00000000
li a5, 0x00000000
li a6, 0x00000000
li a7, 0x00000000
li s2, 0x00000000
li s3, 0x00000000
li s4, 0x00000000
li s5, 0x00000000
li s6, 0x00000000
li s7, 0x00000000
li s8, 0x00000000
li s9, 0x00000000
li s10, 0x00000000
li s11, 0x00000000
li t3, 0x00000000
li t4, 0x00000000
li t5, 0x00000000
li t6, 0x00000000
p.sw x0, ra(x0!)
sw ra, 0(sp)
li ra, 0xffffffff
p.sw x0, t0(x0!)
sw t0, 0(sp)
li t0, 0xffffffff
p.sw x0, t1(x0!)
sw t1, 0(sp)
li t1, 0xffffffff
p.sw x0, t2(x0!)
sw t2, 0(sp)
li t2, 0xffffffff
p.sw x0, s0(x0!)
sw s0, 0(sp)
li s0, 0xffffffff
p.sw x0, s1(x0!)
sw s1, 0(sp)
li s1, 0xffffffff
p.sw x0, a0(x0!)
sw a0, 0(sp)
li a0, 0xffffffff
p.sw x0, a1(x0!)
sw a1, 0(sp)
li a1, 0xffffffff
p.sw x0, a2(x0!)
sw a2, 0(sp)
li a2, 0xffffffff
p.sw x0, a3(x0!)
sw a3, 0(sp)
li a3, 0xffffffff
p.sw x0, a4(x0!)
sw a4, 0(sp)
li a4, 0xffffffff
p.sw x0, a5(x0!)
sw a5, 0(sp)
li a5, 0xffffffff
p.sw x0, a6(x0!)
sw a6, 0(sp)
li a6, 0xffffffff
p.sw x0, a7(x0!)
sw a7, 0(sp)
li a7, 0xffffffff
p.sw x0, s2(x0!)
sw s2, 0(sp)
li s2, 0xffffffff
p.sw x0, s3(x0!)
sw s3, 0(sp)
li s3, 0xffffffff
p.sw x0, s4(x0!)
sw s4, 0(sp)
li s4, 0xffffffff
p.sw x0, s5(x0!)
sw s5, 0(sp)
li s5, 0xffffffff
p.sw x0, s6(x0!)
sw s6, 0(sp)
li s6, 0xffffffff
p.sw x0, s7(x0!)
sw s7, 0(sp)
li s7, 0xffffffff
p.sw x0, s8(x0!)
sw s8, 0(sp)
li s8, 0xffffffff
p.sw x0, s9(x0!)
sw s9, 0(sp)
li s9, 0xffffffff
p.sw x0, s10(x0!)
sw s10, 0(sp)
li s10, 0xffffffff
p.sw x0, s11(x0!)
sw s11, 0(sp)
li s11, 0xffffffff
p.sw x0, t3(x0!)
sw t3, 0(sp)
li t3, 0xffffffff
p.sw x0, t4(x0!)
sw t4, 0(sp)
li t4, 0xffffffff
p.sw x0, t5(x0!)
sw t5, 0(sp)
li t5, 0xffffffff
p.sw x0, t6(x0!)
sw t6, 0(sp)
li t6, 0xffffffff
p.sw x0, t6(x0!)
sw t6, 0(sp)
li t6, 0x00000000
p.sw x0, t6(x0!)
sw t6, 0(sp)
p.sw x0, t5(x0!)
sw t5, 0(sp)
li t5, 0x00000000
p.sw x0, t5(x0!)
sw t5, 0(sp)
p.sw x0, t4(x0!)
sw t4, 0(sp)
li t4, 0x00000000
p.sw x0, t4(x0!)
sw t4, 0(sp)
p.sw x0, t3(x0!)
sw t3, 0(sp)
li t3, 0x00000000
p.sw x0, t3(x0!)
sw t3, 0(sp)
p.sw x0, s11(x0!)
sw s11, 0(sp)
li s11, 0x00000000
p.sw x0, s11(x0!)
sw s11, 0(sp)
p.sw x0, s10(x0!)
sw s10, 0(sp)
li s10, 0x00000000
p.sw x0, s10(x0!)
sw s10, 0(sp)
p.sw x0, s9(x0!)
sw s9, 0(sp)
li s9, 0x00000000
p.sw x0, s9(x0!)
sw s9, 0(sp)
p.sw x0, s8(x0!)
sw s8, 0(sp)
li s8, 0x00000000
p.sw x0, s8(x0!)
sw s8, 0(sp)
p.sw x0, s7(x0!)
sw s7, 0(sp)
li s7, 0x00000000
p.sw x0, s7(x0!)
sw s7, 0(sp)
p.sw x0, s6(x0!)
sw s6, 0(sp)
li s6, 0x00000000
p.sw x0, s6(x0!)
sw s6, 0(sp)
p.sw x0, s5(x0!)
sw s5, 0(sp)
li s5, 0x00000000
p.sw x0, s5(x0!)
sw s5, 0(sp)
p.sw x0, s4(x0!)
sw s4, 0(sp)
li s4, 0x00000000
p.sw x0, s4(x0!)
sw s4, 0(sp)
p.sw x0, s3(x0!)
sw s3, 0(sp)
li s3, 0x00000000
p.sw x0, s3(x0!)
sw s3, 0(sp)
p.sw x0, s2(x0!)
sw s2, 0(sp)
li s2, 0x00000000
p.sw x0, s2(x0!)
sw s2, 0(sp)
p.sw x0, a7(x0!)
sw a7, 0(sp)
li a7, 0x00000000
p.sw x0, a7(x0!)
sw a7, 0(sp)
p.sw x0, a6(x0!)
sw a6, 0(sp)
li a6, 0x00000000
p.sw x0, a6(x0!)
sw a6, 0(sp)
p.sw x0, a5(x0!)
sw a5, 0(sp)
li a5, 0x00000000
p.sw x0, a5(x0!)
sw a5, 0(sp)
p.sw x0, a4(x0!)
sw a4, 0(sp)
li a4, 0x00000000
p.sw x0, a4(x0!)
sw a4, 0(sp)
p.sw x0, a3(x0!)
sw a3, 0(sp)
li a3, 0x00000000
p.sw x0, a3(x0!)
sw a3, 0(sp)
p.sw x0, a2(x0!)
sw a2, 0(sp)
li a2, 0x00000000
p.sw x0, a2(x0!)
sw a2, 0(sp)
p.sw x0, a1(x0!)
sw a1, 0(sp)
li a1, 0x00000000
p.sw x0, a1(x0!)
sw a1, 0(sp)
p.sw x0, a0(x0!)
sw a0, 0(sp)
li a0, 0x00000000
p.sw x0, a0(x0!)
sw a0, 0(sp)
p.sw x0, s1(x0!)
sw s1, 0(sp)
li s1, 0x00000000
p.sw x0, s1(x0!)
sw s1, 0(sp)
p.sw x0, s0(x0!)
sw s0, 0(sp)
li s0, 0x00000000
p.sw x0, s0(x0!)
sw s0, 0(sp)
p.sw x0, t2(x0!)
sw t2, 0(sp)
li t2, 0x00000000
p.sw x0, t2(x0!)
sw t2, 0(sp)
p.sw x0, t1(x0!)
sw t1, 0(sp)
li t1, 0x00000000
p.sw x0, t1(x0!)
sw t1, 0(sp)
p.sw x0, t0(x0!)
sw t0, 0(sp)
li t0, 0x00000000
p.sw x0, t0(x0!)
sw t0, 0(sp)
p.sw x0, ra(x0!)
sw ra, 0(sp)
li ra, 0x00000000
p.sw x0, ra(x0!)
sw ra, 0(sp)
li ra, 0xffff0000
li t0, 0xffff0000
li t1, 0xffff0000
li t2, 0xffff0000
li s0, 0xffff0000
li s1, 0xffff0000
li a0, 0xffff0000
li a1, 0xffff0000
li a2, 0xffff0000
li a3, 0xffff0000
li a4, 0xffff0000
li a5, 0xffff0000
li a6, 0xffff0000
li a7, 0xffff0000
li s2, 0xffff0000
li s3, 0xffff0000
li s4, 0xffff0000
li s5, 0xffff0000
li s6, 0xffff0000
li s7, 0xffff0000
li s8, 0xffff0000
li s9, 0xffff0000
li s10, 0xffff0000
li s11, 0xffff0000
li t3, 0xffff0000
li t4, 0xffff0000
li t5, 0xffff0000
li t6, 0xffff0000
sw ra, 0(sp)
li ra, 0x0000ffff
sw t0, 0(sp)
li t0, 0x0000ffff
sw t1, 0(sp)
li t1, 0x0000ffff
sw t2, 0(sp)
li t2, 0x0000ffff
sw s0, 0(sp)
li s0, 0x0000ffff
sw s1, 0(sp)
li s1, 0x0000ffff
sw a0, 0(sp)
li a0, 0x0000ffff
sw a1, 0(sp)
li a1, 0x0000ffff
sw a2, 0(sp)
li a2, 0x0000ffff
sw a3, 0(sp)
li a3, 0x0000ffff
sw a4, 0(sp)
li a4, 0x0000ffff
sw a5, 0(sp)
li a5, 0x0000ffff
sw a6, 0(sp)
li a6, 0x0000ffff
sw a7, 0(sp)
li a7, 0x0000ffff
sw s2, 0(sp)
li s2, 0x0000ffff
sw s3, 0(sp)
li s3, 0x0000ffff
sw s4, 0(sp)
li s4, 0x0000ffff
sw s5, 0(sp)
li s5, 0x0000ffff
sw s6, 0(sp)
li s6, 0x0000ffff
sw s7, 0(sp)
li s7, 0x0000ffff
sw s8, 0(sp)
li s8, 0x0000ffff
sw s9, 0(sp)
li s9, 0x0000ffff
sw s10, 0(sp)
li s10, 0x0000ffff
sw s11, 0(sp)
li s11, 0x0000ffff
sw t3, 0(sp)
li t3, 0x0000ffff
sw t4, 0(sp)
li t4, 0x0000ffff
sw t5, 0(sp)
li t5, 0x0000ffff
sw t6, 0(sp)
li t6, 0x0000ffff
sw t6, 0(sp)
li t6, 0xffff0000
sw t6, 0(sp)
sw t5, 0(sp)
li t5, 0xffff0000
sw t5, 0(sp)
sw t4, 0(sp)
li t4, 0xffff0000
sw t4, 0(sp)
sw t3, 0(sp)
li t3, 0xffff0000
sw t3, 0(sp)
sw s11, 0(sp)
li s11, 0xffff0000
sw s11, 0(sp)
sw s10, 0(sp)
li s10, 0xffff0000
sw s10, 0(sp)
sw s9, 0(sp)
li s9, 0xffff0000
sw s9, 0(sp)
sw s8, 0(sp)
li s8, 0xffff0000
sw s8, 0(sp)
sw s7, 0(sp)
li s7, 0xffff0000
sw s7, 0(sp)
sw s6, 0(sp)
li s6, 0xffff0000
sw s6, 0(sp)
sw s5, 0(sp)
li s5, 0xffff0000
sw s5, 0(sp)
sw s4, 0(sp)
li s4, 0xffff0000
sw s4, 0(sp)
sw s3, 0(sp)
li s3, 0xffff0000
sw s3, 0(sp)
sw s2, 0(sp)
li s2, 0xffff0000
sw s2, 0(sp)
sw a7, 0(sp)
li a7, 0xffff0000
sw a7, 0(sp)
sw a6, 0(sp)
li a6, 0xffff0000
sw a6, 0(sp)
sw a5, 0(sp)
li a5, 0xffff0000
sw a5, 0(sp)
sw a4, 0(sp)
li a4, 0xffff0000
sw a4, 0(sp)
sw a3, 0(sp)
li a3, 0xffff0000
sw a3, 0(sp)
sw a2, 0(sp)
li a2, 0xffff0000
sw a2, 0(sp)
sw a1, 0(sp)
li a1, 0xffff0000
sw a1, 0(sp)
sw a0, 0(sp)
li a0, 0xffff0000
sw a0, 0(sp)
sw s1, 0(sp)
li s1, 0xffff0000
sw s1, 0(sp)
sw s0, 0(sp)
li s0, 0xffff0000
sw s0, 0(sp)
sw t2, 0(sp)
li t2, 0xffff0000
sw t2, 0(sp)
sw t1, 0(sp)
li t1, 0xffff0000
sw t1, 0(sp)
sw t0, 0(sp)
li t0, 0xffff0000
sw t0, 0(sp)
sw ra, 0(sp)
li ra, 0xffff0000
sw ra, 0(sp)
li ra, 0xffff0000
li t0, 0xffff0000
li t1, 0xffff0000
li t2, 0xffff0000
li s0, 0xffff0000
li s1, 0xffff0000
li a0, 0xffff0000
li a1, 0xffff0000
li a2, 0xffff0000
li a3, 0xffff0000
li a4, 0xffff0000
li a5, 0xffff0000
li a6, 0xffff0000
li a7, 0xffff0000
li s2, 0xffff0000
li s3, 0xffff0000
li s4, 0xffff0000
li s5, 0xffff0000
li s6, 0xffff0000
li s7, 0xffff0000
li s8, 0xffff0000
li s9, 0xffff0000
li s10, 0xffff0000
li s11, 0xffff0000
li t3, 0xffff0000
li t4, 0xffff0000
li t5, 0xffff0000
li t6, 0xffff0000
add ra, x0, ra
sw ra, 0(sp)
li ra, 0x0000ffff
add t0, x0, t0
sw t0, 0(sp)
li t0, 0x0000ffff
add t1, x0, t1
sw t1, 0(sp)
li t1, 0x0000ffff
add t2, x0, t2
sw t2, 0(sp)
li t2, 0x0000ffff
add s0, x0, s0
sw s0, 0(sp)
li s0, 0x0000ffff
add s1, x0, s1
sw s1, 0(sp)
li s1, 0x0000ffff
add a0, x0, a0
sw a0, 0(sp)
li a0, 0x0000ffff
add a1, x0, a1
sw a1, 0(sp)
li a1, 0x0000ffff
add a2, x0, a2
sw a2, 0(sp)
li a2, 0x0000ffff
add a3, x0, a3
sw a3, 0(sp)
li a3, 0x0000ffff
add a4, x0, a4
sw a4, 0(sp)
li a4, 0x0000ffff
add a5, x0, a5
sw a5, 0(sp)
li a5, 0x0000ffff
add a6, x0, a6
sw a6, 0(sp)
li a6, 0x0000ffff
add a7, x0, a7
sw a7, 0(sp)
li a7, 0x0000ffff
add s2, x0, s2
sw s2, 0(sp)
li s2, 0x0000ffff
add s3, x0, s3
sw s3, 0(sp)
li s3, 0x0000ffff
add s4, x0, s4
sw s4, 0(sp)
li s4, 0x0000ffff
add s5, x0, s5
sw s5, 0(sp)
li s5, 0x0000ffff
add s6, x0, s6
sw s6, 0(sp)
li s6, 0x0000ffff
add s7, x0, s7
sw s7, 0(sp)
li s7, 0x0000ffff
add s8, x0, s8
sw s8, 0(sp)
li s8, 0x0000ffff
add s9, x0, s9
sw s9, 0(sp)
li s9, 0x0000ffff
add s10, x0, s10
sw s10, 0(sp)
li s10, 0x0000ffff
add s11, x0, s11
sw s11, 0(sp)
li s11, 0x0000ffff
add t3, x0, t3
sw t3, 0(sp)
li t3, 0x0000ffff
add t4, x0, t4
sw t4, 0(sp)
li t4, 0x0000ffff
add t5, x0, t5
sw t5, 0(sp)
li t5, 0x0000ffff
add t6, x0, t6
sw t6, 0(sp)
li t6, 0x0000ffff
add t6, x0, t6
sw t6, 0(sp)
li t6, 0xffff0000
add t6, x0, t6
sw t6, 0(sp)
add t5, x0, t5
sw t5, 0(sp)
li t5, 0xffff0000
add t5, x0, t5
sw t5, 0(sp)
add t4, x0, t4
sw t4, 0(sp)
li t4, 0xffff0000
add t4, x0, t4
sw t4, 0(sp)
add t3, x0, t3
sw t3, 0(sp)
li t3, 0xffff0000
add t3, x0, t3
sw t3, 0(sp)
add s11, x0, s11
sw s11, 0(sp)
li s11, 0xffff0000
add s11, x0, s11
sw s11, 0(sp)
add s10, x0, s10
sw s10, 0(sp)
li s10, 0xffff0000
add s10, x0, s10
sw s10, 0(sp)
add s9, x0, s9
sw s9, 0(sp)
li s9, 0xffff0000
add s9, x0, s9
sw s9, 0(sp)
add s8, x0, s8
sw s8, 0(sp)
li s8, 0xffff0000
add s8, x0, s8
sw s8, 0(sp)
add s7, x0, s7
sw s7, 0(sp)
li s7, 0xffff0000
add s7, x0, s7
sw s7, 0(sp)
add s6, x0, s6
sw s6, 0(sp)
li s6, 0xffff0000
add s6, x0, s6
sw s6, 0(sp)
add s5, x0, s5
sw s5, 0(sp)
li s5, 0xffff0000
add s5, x0, s5
sw s5, 0(sp)
add s4, x0, s4
sw s4, 0(sp)
li s4, 0xffff0000
add s4, x0, s4
sw s4, 0(sp)
add s3, x0, s3
sw s3, 0(sp)
li s3, 0xffff0000
add s3, x0, s3
sw s3, 0(sp)
add s2, x0, s2
sw s2, 0(sp)
li s2, 0xffff0000
add s2, x0, s2
sw s2, 0(sp)
add a7, x0, a7
sw a7, 0(sp)
li a7, 0xffff0000
add a7, x0, a7
sw a7, 0(sp)
add a6, x0, a6
sw a6, 0(sp)
li a6, 0xffff0000
add a6, x0, a6
sw a6, 0(sp)
add a5, x0, a5
sw a5, 0(sp)
li a5, 0xffff0000
add a5, x0, a5
sw a5, 0(sp)
add a4, x0, a4
sw a4, 0(sp)
li a4, 0xffff0000
add a4, x0, a4
sw a4, 0(sp)
add a3, x0, a3
sw a3, 0(sp)
li a3, 0xffff0000
add a3, x0, a3
sw a3, 0(sp)
add a2, x0, a2
sw a2, 0(sp)
li a2, 0xffff0000
add a2, x0, a2
sw a2, 0(sp)
add a1, x0, a1
sw a1, 0(sp)
li a1, 0xffff0000
add a1, x0, a1
sw a1, 0(sp)
add a0, x0, a0
sw a0, 0(sp)
li a0, 0xffff0000
add a0, x0, a0
sw a0, 0(sp)
add s1, x0, s1
sw s1, 0(sp)
li s1, 0xffff0000
add s1, x0, s1
sw s1, 0(sp)
add s0, x0, s0
sw s0, 0(sp)
li s0, 0xffff0000
add s0, x0, s0
sw s0, 0(sp)
add t2, x0, t2
sw t2, 0(sp)
li t2, 0xffff0000
add t2, x0, t2
sw t2, 0(sp)
add t1, x0, t1
sw t1, 0(sp)
li t1, 0xffff0000
add t1, x0, t1
sw t1, 0(sp)
add t0, x0, t0
sw t0, 0(sp)
li t0, 0xffff0000
add t0, x0, t0
sw t0, 0(sp)
add ra, x0, ra
sw ra, 0(sp)
li ra, 0xffff0000
add ra, x0, ra
sw ra, 0(sp)
li ra, 0xffff0000
li t0, 0xffff0000
li t1, 0xffff0000
li t2, 0xffff0000
li s0, 0xffff0000
li s1, 0xffff0000
li a0, 0xffff0000
li a1, 0xffff0000
li a2, 0xffff0000
li a3, 0xffff0000
li a4, 0xffff0000
li a5, 0xffff0000
li a6, 0xffff0000
li a7, 0xffff0000
li s2, 0xffff0000
li s3, 0xffff0000
li s4, 0xffff0000
li s5, 0xffff0000
li s6, 0xffff0000
li s7, 0xffff0000
li s8, 0xffff0000
li s9, 0xffff0000
li s10, 0xffff0000
li s11, 0xffff0000
li t3, 0xffff0000
li t4, 0xffff0000
li t5, 0xffff0000
li t6, 0xffff0000
p.sw x0, ra(x0!)
sw ra, 0(sp)
li ra, 0x0000ffff
p.sw x0, t0(x0!)
sw t0, 0(sp)
li t0, 0x0000ffff
p.sw x0, t1(x0!)
sw t1, 0(sp)
li t1, 0x0000ffff
p.sw x0, t2(x0!)
sw t2, 0(sp)
li t2, 0x0000ffff
p.sw x0, s0(x0!)
sw s0, 0(sp)
li s0, 0x0000ffff
p.sw x0, s1(x0!)
sw s1, 0(sp)
li s1, 0x0000ffff
p.sw x0, a0(x0!)
sw a0, 0(sp)
li a0, 0x0000ffff
p.sw x0, a1(x0!)
sw a1, 0(sp)
li a1, 0x0000ffff
p.sw x0, a2(x0!)
sw a2, 0(sp)
li a2, 0x0000ffff
p.sw x0, a3(x0!)
sw a3, 0(sp)
li a3, 0x0000ffff
p.sw x0, a4(x0!)
sw a4, 0(sp)
li a4, 0x0000ffff
p.sw x0, a5(x0!)
sw a5, 0(sp)
li a5, 0x0000ffff
p.sw x0, a6(x0!)
sw a6, 0(sp)
li a6, 0x0000ffff
p.sw x0, a7(x0!)
sw a7, 0(sp)
li a7, 0x0000ffff
p.sw x0, s2(x0!)
sw s2, 0(sp)
li s2, 0x0000ffff
p.sw x0, s3(x0!)
sw s3, 0(sp)
li s3, 0x0000ffff
p.sw x0, s4(x0!)
sw s4, 0(sp)
li s4, 0x0000ffff
p.sw x0, s5(x0!)
sw s5, 0(sp)
li s5, 0x0000ffff
p.sw x0, s6(x0!)
sw s6, 0(sp)
li s6, 0x0000ffff
p.sw x0, s7(x0!)
sw s7, 0(sp)
li s7, 0x0000ffff
p.sw x0, s8(x0!)
sw s8, 0(sp)
li s8, 0x0000ffff
p.sw x0, s9(x0!)
sw s9, 0(sp)
li s9, 0x0000ffff
p.sw x0, s10(x0!)
sw s10, 0(sp)
li s10, 0x0000ffff
p.sw x0, s11(x0!)
sw s11, 0(sp)
li s11, 0x0000ffff
p.sw x0, t3(x0!)
sw t3, 0(sp)
li t3, 0x0000ffff
p.sw x0, t4(x0!)
sw t4, 0(sp)
li t4, 0x0000ffff
p.sw x0, t5(x0!)
sw t5, 0(sp)
li t5, 0x0000ffff
p.sw x0, t6(x0!)
sw t6, 0(sp)
li t6, 0x0000ffff
p.sw x0, t6(x0!)
sw t6, 0(sp)
li t6, 0xffff0000
p.sw x0, t6(x0!)
sw t6, 0(sp)
p.sw x0, t5(x0!)
sw t5, 0(sp)
li t5, 0xffff0000
p.sw x0, t5(x0!)
sw t5, 0(sp)
p.sw x0, t4(x0!)
sw t4, 0(sp)
li t4, 0xffff0000
p.sw x0, t4(x0!)
sw t4, 0(sp)
p.sw x0, t3(x0!)
sw t3, 0(sp)
li t3, 0xffff0000
p.sw x0, t3(x0!)
sw t3, 0(sp)
p.sw x0, s11(x0!)
sw s11, 0(sp)
li s11, 0xffff0000
p.sw x0, s11(x0!)
sw s11, 0(sp)
p.sw x0, s10(x0!)
sw s10, 0(sp)
li s10, 0xffff0000
p.sw x0, s10(x0!)
sw s10, 0(sp)
p.sw x0, s9(x0!)
sw s9, 0(sp)
li s9, 0xffff0000
p.sw x0, s9(x0!)
sw s9, 0(sp)
p.sw x0, s8(x0!)
sw s8, 0(sp)
li s8, 0xffff0000
p.sw x0, s8(x0!)
sw s8, 0(sp)
p.sw x0, s7(x0!)
sw s7, 0(sp)
li s7, 0xffff0000
p.sw x0, s7(x0!)
sw s7, 0(sp)
p.sw x0, s6(x0!)
sw s6, 0(sp)
li s6, 0xffff0000
p.sw x0, s6(x0!)
sw s6, 0(sp)
p.sw x0, s5(x0!)
sw s5, 0(sp)
li s5, 0xffff0000
p.sw x0, s5(x0!)
sw s5, 0(sp)
p.sw x0, s4(x0!)
sw s4, 0(sp)
li s4, 0xffff0000
p.sw x0, s4(x0!)
sw s4, 0(sp)
p.sw x0, s3(x0!)
sw s3, 0(sp)
li s3, 0xffff0000
p.sw x0, s3(x0!)
sw s3, 0(sp)
p.sw x0, s2(x0!)
sw s2, 0(sp)
li s2, 0xffff0000
p.sw x0, s2(x0!)
sw s2, 0(sp)
p.sw x0, a7(x0!)
sw a7, 0(sp)
li a7, 0xffff0000
p.sw x0, a7(x0!)
sw a7, 0(sp)
p.sw x0, a6(x0!)
sw a6, 0(sp)
li a6, 0xffff0000
p.sw x0, a6(x0!)
sw a6, 0(sp)
p.sw x0, a5(x0!)
sw a5, 0(sp)
li a5, 0xffff0000
p.sw x0, a5(x0!)
sw a5, 0(sp)
p.sw x0, a4(x0!)
sw a4, 0(sp)
li a4, 0xffff0000
p.sw x0, a4(x0!)
sw a4, 0(sp)
p.sw x0, a3(x0!)
sw a3, 0(sp)
li a3, 0xffff0000
p.sw x0, a3(x0!)
sw a3, 0(sp)
p.sw x0, a2(x0!)
sw a2, 0(sp)
li a2, 0xffff0000
p.sw x0, a2(x0!)
sw a2, 0(sp)
p.sw x0, a1(x0!)
sw a1, 0(sp)
li a1, 0xffff0000
p.sw x0, a1(x0!)
sw a1, 0(sp)
p.sw x0, a0(x0!)
sw a0, 0(sp)
li a0, 0xffff0000
p.sw x0, a0(x0!)
sw a0, 0(sp)
p.sw x0, s1(x0!)
sw s1, 0(sp)
li s1, 0xffff0000
p.sw x0, s1(x0!)
sw s1, 0(sp)
p.sw x0, s0(x0!)
sw s0, 0(sp)
li s0, 0xffff0000
p.sw x0, s0(x0!)
sw s0, 0(sp)
p.sw x0, t2(x0!)
sw t2, 0(sp)
li t2, 0xffff0000
p.sw x0, t2(x0!)
sw t2, 0(sp)
p.sw x0, t1(x0!)
sw t1, 0(sp)
li t1, 0xffff0000
p.sw x0, t1(x0!)
sw t1, 0(sp)
p.sw x0, t0(x0!)
sw t0, 0(sp)
li t0, 0xffff0000
p.sw x0, t0(x0!)
sw t0, 0(sp)
p.sw x0, ra(x0!)
sw ra, 0(sp)
li ra, 0xffff0000
p.sw x0, ra(x0!)
sw ra, 0(sp)
li ra, 0xff00ff00
li t0, 0xff00ff00
li t1, 0xff00ff00
li t2, 0xff00ff00
li s0, 0xff00ff00
li s1, 0xff00ff00
li a0, 0xff00ff00
li a1, 0xff00ff00
li a2, 0xff00ff00
li a3, 0xff00ff00
li a4, 0xff00ff00
li a5, 0xff00ff00
li a6, 0xff00ff00
li a7, 0xff00ff00
li s2, 0xff00ff00
li s3, 0xff00ff00
li s4, 0xff00ff00
li s5, 0xff00ff00
li s6, 0xff00ff00
li s7, 0xff00ff00
li s8, 0xff00ff00
li s9, 0xff00ff00
li s10, 0xff00ff00
li s11, 0xff00ff00
li t3, 0xff00ff00
li t4, 0xff00ff00
li t5, 0xff00ff00
li t6, 0xff00ff00
sw ra, 0(sp)
li ra, 0x00ff00ff
sw t0, 0(sp)
li t0, 0x00ff00ff
sw t1, 0(sp)
li t1, 0x00ff00ff
sw t2, 0(sp)
li t2, 0x00ff00ff
sw s0, 0(sp)
li s0, 0x00ff00ff
sw s1, 0(sp)
li s1, 0x00ff00ff
sw a0, 0(sp)
li a0, 0x00ff00ff
sw a1, 0(sp)
li a1, 0x00ff00ff
sw a2, 0(sp)
li a2, 0x00ff00ff
sw a3, 0(sp)
li a3, 0x00ff00ff
sw a4, 0(sp)
li a4, 0x00ff00ff
sw a5, 0(sp)
li a5, 0x00ff00ff
sw a6, 0(sp)
li a6, 0x00ff00ff
sw a7, 0(sp)
li a7, 0x00ff00ff
sw s2, 0(sp)
li s2, 0x00ff00ff
sw s3, 0(sp)
li s3, 0x00ff00ff
sw s4, 0(sp)
li s4, 0x00ff00ff
sw s5, 0(sp)
li s5, 0x00ff00ff
sw s6, 0(sp)
li s6, 0x00ff00ff
sw s7, 0(sp)
li s7, 0x00ff00ff
sw s8, 0(sp)
li s8, 0x00ff00ff
sw s9, 0(sp)
li s9, 0x00ff00ff
sw s10, 0(sp)
li s10, 0x00ff00ff
sw s11, 0(sp)
li s11, 0x00ff00ff
sw t3, 0(sp)
li t3, 0x00ff00ff
sw t4, 0(sp)
li t4, 0x00ff00ff
sw t5, 0(sp)
li t5, 0x00ff00ff
sw t6, 0(sp)
li t6, 0x00ff00ff
sw t6, 0(sp)
li t6, 0xff00ff00
sw t6, 0(sp)
sw t5, 0(sp)
li t5, 0xff00ff00
sw t5, 0(sp)
sw t4, 0(sp)
li t4, 0xff00ff00
sw t4, 0(sp)
sw t3, 0(sp)
li t3, 0xff00ff00
sw t3, 0(sp)
sw s11, 0(sp)
li s11, 0xff00ff00
sw s11, 0(sp)
sw s10, 0(sp)
li s10, 0xff00ff00
sw s10, 0(sp)
sw s9, 0(sp)
li s9, 0xff00ff00
sw s9, 0(sp)
sw s8, 0(sp)
li s8, 0xff00ff00
sw s8, 0(sp)
sw s7, 0(sp)
li s7, 0xff00ff00
sw s7, 0(sp)
sw s6, 0(sp)
li s6, 0xff00ff00
sw s6, 0(sp)
sw s5, 0(sp)
li s5, 0xff00ff00
sw s5, 0(sp)
sw s4, 0(sp)
li s4, 0xff00ff00
sw s4, 0(sp)
sw s3, 0(sp)
li s3, 0xff00ff00
sw s3, 0(sp)
sw s2, 0(sp)
li s2, 0xff00ff00
sw s2, 0(sp)
sw a7, 0(sp)
li a7, 0xff00ff00
sw a7, 0(sp)
sw a6, 0(sp)
li a6, 0xff00ff00
sw a6, 0(sp)
sw a5, 0(sp)
li a5, 0xff00ff00
sw a5, 0(sp)
sw a4, 0(sp)
li a4, 0xff00ff00
sw a4, 0(sp)
sw a3, 0(sp)
li a3, 0xff00ff00
sw a3, 0(sp)
sw a2, 0(sp)
li a2, 0xff00ff00
sw a2, 0(sp)
sw a1, 0(sp)
li a1, 0xff00ff00
sw a1, 0(sp)
sw a0, 0(sp)
li a0, 0xff00ff00
sw a0, 0(sp)
sw s1, 0(sp)
li s1, 0xff00ff00
sw s1, 0(sp)
sw s0, 0(sp)
li s0, 0xff00ff00
sw s0, 0(sp)
sw t2, 0(sp)
li t2, 0xff00ff00
sw t2, 0(sp)
sw t1, 0(sp)
li t1, 0xff00ff00
sw t1, 0(sp)
sw t0, 0(sp)
li t0, 0xff00ff00
sw t0, 0(sp)
sw ra, 0(sp)
li ra, 0xff00ff00
sw ra, 0(sp)
li ra, 0xff00ff00
li t0, 0xff00ff00
li t1, 0xff00ff00
li t2, 0xff00ff00
li s0, 0xff00ff00
li s1, 0xff00ff00
li a0, 0xff00ff00
li a1, 0xff00ff00
li a2, 0xff00ff00
li a3, 0xff00ff00
li a4, 0xff00ff00
li a5, 0xff00ff00
li a6, 0xff00ff00
li a7, 0xff00ff00
li s2, 0xff00ff00
li s3, 0xff00ff00
li s4, 0xff00ff00
li s5, 0xff00ff00
li s6, 0xff00ff00
li s7, 0xff00ff00
li s8, 0xff00ff00
li s9, 0xff00ff00
li s10, 0xff00ff00
li s11, 0xff00ff00
li t3, 0xff00ff00
li t4, 0xff00ff00
li t5, 0xff00ff00
li t6, 0xff00ff00
add ra, x0, ra
sw ra, 0(sp)
li ra, 0x00ff00ff
add t0, x0, t0
sw t0, 0(sp)
li t0, 0x00ff00ff
add t1, x0, t1
sw t1, 0(sp)
li t1, 0x00ff00ff
add t2, x0, t2
sw t2, 0(sp)
li t2, 0x00ff00ff
add s0, x0, s0
sw s0, 0(sp)
li s0, 0x00ff00ff
add s1, x0, s1
sw s1, 0(sp)
li s1, 0x00ff00ff
add a0, x0, a0
sw a0, 0(sp)
li a0, 0x00ff00ff
add a1, x0, a1
sw a1, 0(sp)
li a1, 0x00ff00ff
add a2, x0, a2
sw a2, 0(sp)
li a2, 0x00ff00ff
add a3, x0, a3
sw a3, 0(sp)
li a3, 0x00ff00ff
add a4, x0, a4
sw a4, 0(sp)
li a4, 0x00ff00ff
add a5, x0, a5
sw a5, 0(sp)
li a5, 0x00ff00ff
add a6, x0, a6
sw a6, 0(sp)
li a6, 0x00ff00ff
add a7, x0, a7
sw a7, 0(sp)
li a7, 0x00ff00ff
add s2, x0, s2
sw s2, 0(sp)
li s2, 0x00ff00ff
add s3, x0, s3
sw s3, 0(sp)
li s3, 0x00ff00ff
add s4, x0, s4
sw s4, 0(sp)
li s4, 0x00ff00ff
add s5, x0, s5
sw s5, 0(sp)
li s5, 0x00ff00ff
add s6, x0, s6
sw s6, 0(sp)
li s6, 0x00ff00ff
add s7, x0, s7
sw s7, 0(sp)
li s7, 0x00ff00ff
add s8, x0, s8
sw s8, 0(sp)
li s8, 0x00ff00ff
add s9, x0, s9
sw s9, 0(sp)
li s9, 0x00ff00ff
add s10, x0, s10
sw s10, 0(sp)
li s10, 0x00ff00ff
add s11, x0, s11
sw s11, 0(sp)
li s11, 0x00ff00ff
add t3, x0, t3
sw t3, 0(sp)
li t3, 0x00ff00ff
add t4, x0, t4
sw t4, 0(sp)
li t4, 0x00ff00ff
add t5, x0, t5
sw t5, 0(sp)
li t5, 0x00ff00ff
add t6, x0, t6
sw t6, 0(sp)
li t6, 0x00ff00ff
add t6, x0, t6
sw t6, 0(sp)
li t6, 0xff00ff00
add t6, x0, t6
sw t6, 0(sp)
add t5, x0, t5
sw t5, 0(sp)
li t5, 0xff00ff00
add t5, x0, t5
sw t5, 0(sp)
add t4, x0, t4
sw t4, 0(sp)
li t4, 0xff00ff00
add t4, x0, t4
sw t4, 0(sp)
add t3, x0, t3
sw t3, 0(sp)
li t3, 0xff00ff00
add t3, x0, t3
sw t3, 0(sp)
add s11, x0, s11
sw s11, 0(sp)
li s11, 0xff00ff00
add s11, x0, s11
sw s11, 0(sp)
add s10, x0, s10
sw s10, 0(sp)
li s10, 0xff00ff00
add s10, x0, s10
sw s10, 0(sp)
add s9, x0, s9
sw s9, 0(sp)
li s9, 0xff00ff00
add s9, x0, s9
sw s9, 0(sp)
add s8, x0, s8
sw s8, 0(sp)
li s8, 0xff00ff00
add s8, x0, s8
sw s8, 0(sp)
add s7, x0, s7
sw s7, 0(sp)
li s7, 0xff00ff00
add s7, x0, s7
sw s7, 0(sp)
add s6, x0, s6
sw s6, 0(sp)
li s6, 0xff00ff00
add s6, x0, s6
sw s6, 0(sp)
add s5, x0, s5
sw s5, 0(sp)
li s5, 0xff00ff00
add s5, x0, s5
sw s5, 0(sp)
add s4, x0, s4
sw s4, 0(sp)
li s4, 0xff00ff00
add s4, x0, s4
sw s4, 0(sp)
add s3, x0, s3
sw s3, 0(sp)
li s3, 0xff00ff00
add s3, x0, s3
sw s3, 0(sp)
add s2, x0, s2
sw s2, 0(sp)
li s2, 0xff00ff00
add s2, x0, s2
sw s2, 0(sp)
add a7, x0, a7
sw a7, 0(sp)
li a7, 0xff00ff00
add a7, x0, a7
sw a7, 0(sp)
add a6, x0, a6
sw a6, 0(sp)
li a6, 0xff00ff00
add a6, x0, a6
sw a6, 0(sp)
add a5, x0, a5
sw a5, 0(sp)
li a5, 0xff00ff00
add a5, x0, a5
sw a5, 0(sp)
add a4, x0, a4
sw a4, 0(sp)
li a4, 0xff00ff00
add a4, x0, a4
sw a4, 0(sp)
add a3, x0, a3
sw a3, 0(sp)
li a3, 0xff00ff00
add a3, x0, a3
sw a3, 0(sp)
add a2, x0, a2
sw a2, 0(sp)
li a2, 0xff00ff00
add a2, x0, a2
sw a2, 0(sp)
add a1, x0, a1
sw a1, 0(sp)
li a1, 0xff00ff00
add a1, x0, a1
sw a1, 0(sp)
add a0, x0, a0
sw a0, 0(sp)
li a0, 0xff00ff00
add a0, x0, a0
sw a0, 0(sp)
add s1, x0, s1
sw s1, 0(sp)
li s1, 0xff00ff00
add s1, x0, s1
sw s1, 0(sp)
add s0, x0, s0
sw s0, 0(sp)
li s0, 0xff00ff00
add s0, x0, s0
sw s0, 0(sp)
add t2, x0, t2
sw t2, 0(sp)
li t2, 0xff00ff00
add t2, x0, t2
sw t2, 0(sp)
add t1, x0, t1
sw t1, 0(sp)
li t1, 0xff00ff00
add t1, x0, t1
sw t1, 0(sp)
add t0, x0, t0
sw t0, 0(sp)
li t0, 0xff00ff00
add t0, x0, t0
sw t0, 0(sp)
add ra, x0, ra
sw ra, 0(sp)
li ra, 0xff00ff00
add ra, x0, ra
sw ra, 0(sp)
li ra, 0xff00ff00
li t0, 0xff00ff00
li t1, 0xff00ff00
li t2, 0xff00ff00
li s0, 0xff00ff00
li s1, 0xff00ff00
li a0, 0xff00ff00
li a1, 0xff00ff00
li a2, 0xff00ff00
li a3, 0xff00ff00
li a4, 0xff00ff00
li a5, 0xff00ff00
li a6, 0xff00ff00
li a7, 0xff00ff00
li s2, 0xff00ff00
li s3, 0xff00ff00
li s4, 0xff00ff00
li s5, 0xff00ff00
li s6, 0xff00ff00
li s7, 0xff00ff00
li s8, 0xff00ff00
li s9, 0xff00ff00
li s10, 0xff00ff00
li s11, 0xff00ff00
li t3, 0xff00ff00
li t4, 0xff00ff00
li t5, 0xff00ff00
li t6, 0xff00ff00
p.sw x0, ra(x0!)
sw ra, 0(sp)
li ra, 0x00ff00ff
p.sw x0, t0(x0!)
sw t0, 0(sp)
li t0, 0x00ff00ff
p.sw x0, t1(x0!)
sw t1, 0(sp)
li t1, 0x00ff00ff
p.sw x0, t2(x0!)
sw t2, 0(sp)
li t2, 0x00ff00ff
p.sw x0, s0(x0!)
sw s0, 0(sp)
li s0, 0x00ff00ff
p.sw x0, s1(x0!)
sw s1, 0(sp)
li s1, 0x00ff00ff
p.sw x0, a0(x0!)
sw a0, 0(sp)
li a0, 0x00ff00ff
p.sw x0, a1(x0!)
sw a1, 0(sp)
li a1, 0x00ff00ff
p.sw x0, a2(x0!)
sw a2, 0(sp)
li a2, 0x00ff00ff
p.sw x0, a3(x0!)
sw a3, 0(sp)
li a3, 0x00ff00ff
p.sw x0, a4(x0!)
sw a4, 0(sp)
li a4, 0x00ff00ff
p.sw x0, a5(x0!)
sw a5, 0(sp)
li a5, 0x00ff00ff
p.sw x0, a6(x0!)
sw a6, 0(sp)
li a6, 0x00ff00ff
p.sw x0, a7(x0!)
sw a7, 0(sp)
li a7, 0x00ff00ff
p.sw x0, s2(x0!)
sw s2, 0(sp)
li s2, 0x00ff00ff
p.sw x0, s3(x0!)
sw s3, 0(sp)
li s3, 0x00ff00ff
p.sw x0, s4(x0!)
sw s4, 0(sp)
li s4, 0x00ff00ff
p.sw x0, s5(x0!)
sw s5, 0(sp)
li s5, 0x00ff00ff
p.sw x0, s6(x0!)
sw s6, 0(sp)
li s6, 0x00ff00ff
p.sw x0, s7(x0!)
sw s7, 0(sp)
li s7, 0x00ff00ff
p.sw x0, s8(x0!)
sw s8, 0(sp)
li s8, 0x00ff00ff
p.sw x0, s9(x0!)
sw s9, 0(sp)
li s9, 0x00ff00ff
p.sw x0, s10(x0!)
sw s10, 0(sp)
li s10, 0x00ff00ff
p.sw x0, s11(x0!)
sw s11, 0(sp)
li s11, 0x00ff00ff
p.sw x0, t3(x0!)
sw t3, 0(sp)
li t3, 0x00ff00ff
p.sw x0, t4(x0!)
sw t4, 0(sp)
li t4, 0x00ff00ff
p.sw x0, t5(x0!)
sw t5, 0(sp)
li t5, 0x00ff00ff
p.sw x0, t6(x0!)
sw t6, 0(sp)
li t6, 0x00ff00ff
p.sw x0, t6(x0!)
sw t6, 0(sp)
li t6, 0xff00ff00
p.sw x0, t6(x0!)
sw t6, 0(sp)
p.sw x0, t5(x0!)
sw t5, 0(sp)
li t5, 0xff00ff00
p.sw x0, t5(x0!)
sw t5, 0(sp)
p.sw x0, t4(x0!)
sw t4, 0(sp)
li t4, 0xff00ff00
p.sw x0, t4(x0!)
sw t4, 0(sp)
p.sw x0, t3(x0!)
sw t3, 0(sp)
li t3, 0xff00ff00
p.sw x0, t3(x0!)
sw t3, 0(sp)
p.sw x0, s11(x0!)
sw s11, 0(sp)
li s11, 0xff00ff00
p.sw x0, s11(x0!)
sw s11, 0(sp)
p.sw x0, s10(x0!)
sw s10, 0(sp)
li s10, 0xff00ff00
p.sw x0, s10(x0!)
sw s10, 0(sp)
p.sw x0, s9(x0!)
sw s9, 0(sp)
li s9, 0xff00ff00
p.sw x0, s9(x0!)
sw s9, 0(sp)
p.sw x0, s8(x0!)
sw s8, 0(sp)
li s8, 0xff00ff00
p.sw x0, s8(x0!)
sw s8, 0(sp)
p.sw x0, s7(x0!)
sw s7, 0(sp)
li s7, 0xff00ff00
p.sw x0, s7(x0!)
sw s7, 0(sp)
p.sw x0, s6(x0!)
sw s6, 0(sp)
li s6, 0xff00ff00
p.sw x0, s6(x0!)
sw s6, 0(sp)
p.sw x0, s5(x0!)
sw s5, 0(sp)
li s5, 0xff00ff00
p.sw x0, s5(x0!)
sw s5, 0(sp)
p.sw x0, s4(x0!)
sw s4, 0(sp)
li s4, 0xff00ff00
p.sw x0, s4(x0!)
sw s4, 0(sp)
p.sw x0, s3(x0!)
sw s3, 0(sp)
li s3, 0xff00ff00
p.sw x0, s3(x0!)
sw s3, 0(sp)
p.sw x0, s2(x0!)
sw s2, 0(sp)
li s2, 0xff00ff00
p.sw x0, s2(x0!)
sw s2, 0(sp)
p.sw x0, a7(x0!)
sw a7, 0(sp)
li a7, 0xff00ff00
p.sw x0, a7(x0!)
sw a7, 0(sp)
p.sw x0, a6(x0!)
sw a6, 0(sp)
li a6, 0xff00ff00
p.sw x0, a6(x0!)
sw a6, 0(sp)
p.sw x0, a5(x0!)
sw a5, 0(sp)
li a5, 0xff00ff00
p.sw x0, a5(x0!)
sw a5, 0(sp)
p.sw x0, a4(x0!)
sw a4, 0(sp)
li a4, 0xff00ff00
p.sw x0, a4(x0!)
sw a4, 0(sp)
p.sw x0, a3(x0!)
sw a3, 0(sp)
li a3, 0xff00ff00
p.sw x0, a3(x0!)
sw a3, 0(sp)
p.sw x0, a2(x0!)
sw a2, 0(sp)
li a2, 0xff00ff00
p.sw x0, a2(x0!)
sw a2, 0(sp)
p.sw x0, a1(x0!)
sw a1, 0(sp)
li a1, 0xff00ff00
p.sw x0, a1(x0!)
sw a1, 0(sp)
p.sw x0, a0(x0!)
sw a0, 0(sp)
li a0, 0xff00ff00
p.sw x0, a0(x0!)
sw a0, 0(sp)
p.sw x0, s1(x0!)
sw s1, 0(sp)
li s1, 0xff00ff00
p.sw x0, s1(x0!)
sw s1, 0(sp)
p.sw x0, s0(x0!)
sw s0, 0(sp)
li s0, 0xff00ff00
p.sw x0, s0(x0!)
sw s0, 0(sp)
p.sw x0, t2(x0!)
sw t2, 0(sp)
li t2, 0xff00ff00
p.sw x0, t2(x0!)
sw t2, 0(sp)
p.sw x0, t1(x0!)
sw t1, 0(sp)
li t1, 0xff00ff00
p.sw x0, t1(x0!)
sw t1, 0(sp)
p.sw x0, t0(x0!)
sw t0, 0(sp)
li t0, 0xff00ff00
p.sw x0, t0(x0!)
sw t0, 0(sp)
p.sw x0, ra(x0!)
sw ra, 0(sp)
li ra, 0xff00ff00
p.sw x0, ra(x0!)
sw ra, 0(sp)
li ra, 0xf0f0f0f0
li t0, 0xf0f0f0f0
li t1, 0xf0f0f0f0
li t2, 0xf0f0f0f0
li s0, 0xf0f0f0f0
li s1, 0xf0f0f0f0
li a0, 0xf0f0f0f0
li a1, 0xf0f0f0f0
li a2, 0xf0f0f0f0
li a3, 0xf0f0f0f0
li a4, 0xf0f0f0f0
li a5, 0xf0f0f0f0
li a6, 0xf0f0f0f0
li a7, 0xf0f0f0f0
li s2, 0xf0f0f0f0
li s3, 0xf0f0f0f0
li s4, 0xf0f0f0f0
li s5, 0xf0f0f0f0
li s6, 0xf0f0f0f0
li s7, 0xf0f0f0f0
li s8, 0xf0f0f0f0
li s9, 0xf0f0f0f0
li s10, 0xf0f0f0f0
li s11, 0xf0f0f0f0
li t3, 0xf0f0f0f0
li t4, 0xf0f0f0f0
li t5, 0xf0f0f0f0
li t6, 0xf0f0f0f0
sw ra, 0(sp)
li ra, 0x0f0f0f0f
sw t0, 0(sp)
li t0, 0x0f0f0f0f
sw t1, 0(sp)
li t1, 0x0f0f0f0f
sw t2, 0(sp)
li t2, 0x0f0f0f0f
sw s0, 0(sp)
li s0, 0x0f0f0f0f
sw s1, 0(sp)
li s1, 0x0f0f0f0f
sw a0, 0(sp)
li a0, 0x0f0f0f0f
sw a1, 0(sp)
li a1, 0x0f0f0f0f
sw a2, 0(sp)
li a2, 0x0f0f0f0f
sw a3, 0(sp)
li a3, 0x0f0f0f0f
sw a4, 0(sp)
li a4, 0x0f0f0f0f
sw a5, 0(sp)
li a5, 0x0f0f0f0f
sw a6, 0(sp)
li a6, 0x0f0f0f0f
sw a7, 0(sp)
li a7, 0x0f0f0f0f
sw s2, 0(sp)
li s2, 0x0f0f0f0f
sw s3, 0(sp)
li s3, 0x0f0f0f0f
sw s4, 0(sp)
li s4, 0x0f0f0f0f
sw s5, 0(sp)
li s5, 0x0f0f0f0f
sw s6, 0(sp)
li s6, 0x0f0f0f0f
sw s7, 0(sp)
li s7, 0x0f0f0f0f
sw s8, 0(sp)
li s8, 0x0f0f0f0f
sw s9, 0(sp)
li s9, 0x0f0f0f0f
sw s10, 0(sp)
li s10, 0x0f0f0f0f
sw s11, 0(sp)
li s11, 0x0f0f0f0f
sw t3, 0(sp)
li t3, 0x0f0f0f0f
sw t4, 0(sp)
li t4, 0x0f0f0f0f
sw t5, 0(sp)
li t5, 0x0f0f0f0f
sw t6, 0(sp)
li t6, 0x0f0f0f0f
sw t6, 0(sp)
li t6, 0xf0f0f0f0
sw t6, 0(sp)
sw t5, 0(sp)
li t5, 0xf0f0f0f0
sw t5, 0(sp)
sw t4, 0(sp)
li t4, 0xf0f0f0f0
sw t4, 0(sp)
sw t3, 0(sp)
li t3, 0xf0f0f0f0
sw t3, 0(sp)
sw s11, 0(sp)
li s11, 0xf0f0f0f0
sw s11, 0(sp)
sw s10, 0(sp)
li s10, 0xf0f0f0f0
sw s10, 0(sp)
sw s9, 0(sp)
li s9, 0xf0f0f0f0
sw s9, 0(sp)
sw s8, 0(sp)
li s8, 0xf0f0f0f0
sw s8, 0(sp)
sw s7, 0(sp)
li s7, 0xf0f0f0f0
sw s7, 0(sp)
sw s6, 0(sp)
li s6, 0xf0f0f0f0
sw s6, 0(sp)
sw s5, 0(sp)
li s5, 0xf0f0f0f0
sw s5, 0(sp)
sw s4, 0(sp)
li s4, 0xf0f0f0f0
sw s4, 0(sp)
sw s3, 0(sp)
li s3, 0xf0f0f0f0
sw s3, 0(sp)
sw s2, 0(sp)
li s2, 0xf0f0f0f0
sw s2, 0(sp)
sw a7, 0(sp)
li a7, 0xf0f0f0f0
sw a7, 0(sp)
sw a6, 0(sp)
li a6, 0xf0f0f0f0
sw a6, 0(sp)
sw a5, 0(sp)
li a5, 0xf0f0f0f0
sw a5, 0(sp)
sw a4, 0(sp)
li a4, 0xf0f0f0f0
sw a4, 0(sp)
sw a3, 0(sp)
li a3, 0xf0f0f0f0
sw a3, 0(sp)
sw a2, 0(sp)
li a2, 0xf0f0f0f0
sw a2, 0(sp)
sw a1, 0(sp)
li a1, 0xf0f0f0f0
sw a1, 0(sp)
sw a0, 0(sp)
li a0, 0xf0f0f0f0
sw a0, 0(sp)
sw s1, 0(sp)
li s1, 0xf0f0f0f0
sw s1, 0(sp)
sw s0, 0(sp)
li s0, 0xf0f0f0f0
sw s0, 0(sp)
sw t2, 0(sp)
li t2, 0xf0f0f0f0
sw t2, 0(sp)
sw t1, 0(sp)
li t1, 0xf0f0f0f0
sw t1, 0(sp)
sw t0, 0(sp)
li t0, 0xf0f0f0f0
sw t0, 0(sp)
sw ra, 0(sp)
li ra, 0xf0f0f0f0
sw ra, 0(sp)
li ra, 0xf0f0f0f0
li t0, 0xf0f0f0f0
li t1, 0xf0f0f0f0
li t2, 0xf0f0f0f0
li s0, 0xf0f0f0f0
li s1, 0xf0f0f0f0
li a0, 0xf0f0f0f0
li a1, 0xf0f0f0f0
li a2, 0xf0f0f0f0
li a3, 0xf0f0f0f0
li a4, 0xf0f0f0f0
li a5, 0xf0f0f0f0
li a6, 0xf0f0f0f0
li a7, 0xf0f0f0f0
li s2, 0xf0f0f0f0
li s3, 0xf0f0f0f0
li s4, 0xf0f0f0f0
li s5, 0xf0f0f0f0
li s6, 0xf0f0f0f0
li s7, 0xf0f0f0f0
li s8, 0xf0f0f0f0
li s9, 0xf0f0f0f0
li s10, 0xf0f0f0f0
li s11, 0xf0f0f0f0
li t3, 0xf0f0f0f0
li t4, 0xf0f0f0f0
li t5, 0xf0f0f0f0
li t6, 0xf0f0f0f0
add ra, x0, ra
sw ra, 0(sp)
li ra, 0x0f0f0f0f
add t0, x0, t0
sw t0, 0(sp)
li t0, 0x0f0f0f0f
add t1, x0, t1
sw t1, 0(sp)
li t1, 0x0f0f0f0f
add t2, x0, t2
sw t2, 0(sp)
li t2, 0x0f0f0f0f
add s0, x0, s0
sw s0, 0(sp)
li s0, 0x0f0f0f0f
add s1, x0, s1
sw s1, 0(sp)
li s1, 0x0f0f0f0f
add a0, x0, a0
sw a0, 0(sp)
li a0, 0x0f0f0f0f
add a1, x0, a1
sw a1, 0(sp)
li a1, 0x0f0f0f0f
add a2, x0, a2
sw a2, 0(sp)
li a2, 0x0f0f0f0f
add a3, x0, a3
sw a3, 0(sp)
li a3, 0x0f0f0f0f
add a4, x0, a4
sw a4, 0(sp)
li a4, 0x0f0f0f0f
add a5, x0, a5
sw a5, 0(sp)
li a5, 0x0f0f0f0f
add a6, x0, a6
sw a6, 0(sp)
li a6, 0x0f0f0f0f
add a7, x0, a7
sw a7, 0(sp)
li a7, 0x0f0f0f0f
add s2, x0, s2
sw s2, 0(sp)
li s2, 0x0f0f0f0f
add s3, x0, s3
sw s3, 0(sp)
li s3, 0x0f0f0f0f
add s4, x0, s4
sw s4, 0(sp)
li s4, 0x0f0f0f0f
add s5, x0, s5
sw s5, 0(sp)
li s5, 0x0f0f0f0f
add s6, x0, s6
sw s6, 0(sp)
li s6, 0x0f0f0f0f
add s7, x0, s7
sw s7, 0(sp)
li s7, 0x0f0f0f0f
add s8, x0, s8
sw s8, 0(sp)
li s8, 0x0f0f0f0f
add s9, x0, s9
sw s9, 0(sp)
li s9, 0x0f0f0f0f
add s10, x0, s10
sw s10, 0(sp)
li s10, 0x0f0f0f0f
add s11, x0, s11
sw s11, 0(sp)
li s11, 0x0f0f0f0f
add t3, x0, t3
sw t3, 0(sp)
li t3, 0x0f0f0f0f
add t4, x0, t4
sw t4, 0(sp)
li t4, 0x0f0f0f0f
add t5, x0, t5
sw t5, 0(sp)
li t5, 0x0f0f0f0f
add t6, x0, t6
sw t6, 0(sp)
li t6, 0x0f0f0f0f
add t6, x0, t6
sw t6, 0(sp)
li t6, 0xf0f0f0f0
add t6, x0, t6
sw t6, 0(sp)
add t5, x0, t5
sw t5, 0(sp)
li t5, 0xf0f0f0f0
add t5, x0, t5
sw t5, 0(sp)
add t4, x0, t4
sw t4, 0(sp)
li t4, 0xf0f0f0f0
add t4, x0, t4
sw t4, 0(sp)
add t3, x0, t3
sw t3, 0(sp)
li t3, 0xf0f0f0f0
add t3, x0, t3
sw t3, 0(sp)
add s11, x0, s11
sw s11, 0(sp)
li s11, 0xf0f0f0f0
add s11, x0, s11
sw s11, 0(sp)
add s10, x0, s10
sw s10, 0(sp)
li s10, 0xf0f0f0f0
add s10, x0, s10
sw s10, 0(sp)
add s9, x0, s9
sw s9, 0(sp)
li s9, 0xf0f0f0f0
add s9, x0, s9
sw s9, 0(sp)
add s8, x0, s8
sw s8, 0(sp)
li s8, 0xf0f0f0f0
add s8, x0, s8
sw s8, 0(sp)
add s7, x0, s7
sw s7, 0(sp)
li s7, 0xf0f0f0f0
add s7, x0, s7
sw s7, 0(sp)
add s6, x0, s6
sw s6, 0(sp)
li s6, 0xf0f0f0f0
add s6, x0, s6
sw s6, 0(sp)
add s5, x0, s5
sw s5, 0(sp)
li s5, 0xf0f0f0f0
add s5, x0, s5
sw s5, 0(sp)
add s4, x0, s4
sw s4, 0(sp)
li s4, 0xf0f0f0f0
add s4, x0, s4
sw s4, 0(sp)
add s3, x0, s3
sw s3, 0(sp)
li s3, 0xf0f0f0f0
add s3, x0, s3
sw s3, 0(sp)
add s2, x0, s2
sw s2, 0(sp)
li s2, 0xf0f0f0f0
add s2, x0, s2
sw s2, 0(sp)
add a7, x0, a7
sw a7, 0(sp)
li a7, 0xf0f0f0f0
add a7, x0, a7
sw a7, 0(sp)
add a6, x0, a6
sw a6, 0(sp)
li a6, 0xf0f0f0f0
add a6, x0, a6
sw a6, 0(sp)
add a5, x0, a5
sw a5, 0(sp)
li a5, 0xf0f0f0f0
add a5, x0, a5
sw a5, 0(sp)
add a4, x0, a4
sw a4, 0(sp)
li a4, 0xf0f0f0f0
add a4, x0, a4
sw a4, 0(sp)
add a3, x0, a3
sw a3, 0(sp)
li a3, 0xf0f0f0f0
add a3, x0, a3
sw a3, 0(sp)
add a2, x0, a2
sw a2, 0(sp)
li a2, 0xf0f0f0f0
add a2, x0, a2
sw a2, 0(sp)
add a1, x0, a1
sw a1, 0(sp)
li a1, 0xf0f0f0f0
add a1, x0, a1
sw a1, 0(sp)
add a0, x0, a0
sw a0, 0(sp)
li a0, 0xf0f0f0f0
add a0, x0, a0
sw a0, 0(sp)
add s1, x0, s1
sw s1, 0(sp)
li s1, 0xf0f0f0f0
add s1, x0, s1
sw s1, 0(sp)
add s0, x0, s0
sw s0, 0(sp)
li s0, 0xf0f0f0f0
add s0, x0, s0
sw s0, 0(sp)
add t2, x0, t2
sw t2, 0(sp)
li t2, 0xf0f0f0f0
add t2, x0, t2
sw t2, 0(sp)
add t1, x0, t1
sw t1, 0(sp)
li t1, 0xf0f0f0f0
add t1, x0, t1
sw t1, 0(sp)
add t0, x0, t0
sw t0, 0(sp)
li t0, 0xf0f0f0f0
add t0, x0, t0
sw t0, 0(sp)
add ra, x0, ra
sw ra, 0(sp)
li ra, 0xf0f0f0f0
add ra, x0, ra
sw ra, 0(sp)
li ra, 0xf0f0f0f0
li t0, 0xf0f0f0f0
li t1, 0xf0f0f0f0
li t2, 0xf0f0f0f0
li s0, 0xf0f0f0f0
li s1, 0xf0f0f0f0
li a0, 0xf0f0f0f0
li a1, 0xf0f0f0f0
li a2, 0xf0f0f0f0
li a3, 0xf0f0f0f0
li a4, 0xf0f0f0f0
li a5, 0xf0f0f0f0
li a6, 0xf0f0f0f0
li a7, 0xf0f0f0f0
li s2, 0xf0f0f0f0
li s3, 0xf0f0f0f0
li s4, 0xf0f0f0f0
li s5, 0xf0f0f0f0
li s6, 0xf0f0f0f0
li s7, 0xf0f0f0f0
li s8, 0xf0f0f0f0
li s9, 0xf0f0f0f0
li s10, 0xf0f0f0f0
li s11, 0xf0f0f0f0
li t3, 0xf0f0f0f0
li t4, 0xf0f0f0f0
li t5, 0xf0f0f0f0
li t6, 0xf0f0f0f0
p.sw x0, ra(x0!)
sw ra, 0(sp)
li ra, 0x0f0f0f0f
p.sw x0, t0(x0!)
sw t0, 0(sp)
li t0, 0x0f0f0f0f
p.sw x0, t1(x0!)
sw t1, 0(sp)
li t1, 0x0f0f0f0f
p.sw x0, t2(x0!)
sw t2, 0(sp)
li t2, 0x0f0f0f0f
p.sw x0, s0(x0!)
sw s0, 0(sp)
li s0, 0x0f0f0f0f
p.sw x0, s1(x0!)
sw s1, 0(sp)
li s1, 0x0f0f0f0f
p.sw x0, a0(x0!)
sw a0, 0(sp)
li a0, 0x0f0f0f0f
p.sw x0, a1(x0!)
sw a1, 0(sp)
li a1, 0x0f0f0f0f
p.sw x0, a2(x0!)
sw a2, 0(sp)
li a2, 0x0f0f0f0f
p.sw x0, a3(x0!)
sw a3, 0(sp)
li a3, 0x0f0f0f0f
p.sw x0, a4(x0!)
sw a4, 0(sp)
li a4, 0x0f0f0f0f
p.sw x0, a5(x0!)
sw a5, 0(sp)
li a5, 0x0f0f0f0f
p.sw x0, a6(x0!)
sw a6, 0(sp)
li a6, 0x0f0f0f0f
p.sw x0, a7(x0!)
sw a7, 0(sp)
li a7, 0x0f0f0f0f
p.sw x0, s2(x0!)
sw s2, 0(sp)
li s2, 0x0f0f0f0f
p.sw x0, s3(x0!)
sw s3, 0(sp)
li s3, 0x0f0f0f0f
p.sw x0, s4(x0!)
sw s4, 0(sp)
li s4, 0x0f0f0f0f
p.sw x0, s5(x0!)
sw s5, 0(sp)
li s5, 0x0f0f0f0f
p.sw x0, s6(x0!)
sw s6, 0(sp)
li s6, 0x0f0f0f0f
p.sw x0, s7(x0!)
sw s7, 0(sp)
li s7, 0x0f0f0f0f
p.sw x0, s8(x0!)
sw s8, 0(sp)
li s8, 0x0f0f0f0f
p.sw x0, s9(x0!)
sw s9, 0(sp)
li s9, 0x0f0f0f0f
p.sw x0, s10(x0!)
sw s10, 0(sp)
li s10, 0x0f0f0f0f
p.sw x0, s11(x0!)
sw s11, 0(sp)
li s11, 0x0f0f0f0f
p.sw x0, t3(x0!)
sw t3, 0(sp)
li t3, 0x0f0f0f0f
p.sw x0, t4(x0!)
sw t4, 0(sp)
li t4, 0x0f0f0f0f
p.sw x0, t5(x0!)
sw t5, 0(sp)
li t5, 0x0f0f0f0f
p.sw x0, t6(x0!)
sw t6, 0(sp)
li t6, 0x0f0f0f0f
p.sw x0, t6(x0!)
sw t6, 0(sp)
li t6, 0xf0f0f0f0
p.sw x0, t6(x0!)
sw t6, 0(sp)
p.sw x0, t5(x0!)
sw t5, 0(sp)
li t5, 0xf0f0f0f0
p.sw x0, t5(x0!)
sw t5, 0(sp)
p.sw x0, t4(x0!)
sw t4, 0(sp)
li t4, 0xf0f0f0f0
p.sw x0, t4(x0!)
sw t4, 0(sp)
p.sw x0, t3(x0!)
sw t3, 0(sp)
li t3, 0xf0f0f0f0
p.sw x0, t3(x0!)
sw t3, 0(sp)
p.sw x0, s11(x0!)
sw s11, 0(sp)
li s11, 0xf0f0f0f0
p.sw x0, s11(x0!)
sw s11, 0(sp)
p.sw x0, s10(x0!)
sw s10, 0(sp)
li s10, 0xf0f0f0f0
p.sw x0, s10(x0!)
sw s10, 0(sp)
p.sw x0, s9(x0!)
sw s9, 0(sp)
li s9, 0xf0f0f0f0
p.sw x0, s9(x0!)
sw s9, 0(sp)
p.sw x0, s8(x0!)
sw s8, 0(sp)
li s8, 0xf0f0f0f0
p.sw x0, s8(x0!)
sw s8, 0(sp)
p.sw x0, s7(x0!)
sw s7, 0(sp)
li s7, 0xf0f0f0f0
p.sw x0, s7(x0!)
sw s7, 0(sp)
p.sw x0, s6(x0!)
sw s6, 0(sp)
li s6, 0xf0f0f0f0
p.sw x0, s6(x0!)
sw s6, 0(sp)
p.sw x0, s5(x0!)
sw s5, 0(sp)
li s5, 0xf0f0f0f0
p.sw x0, s5(x0!)
sw s5, 0(sp)
p.sw x0, s4(x0!)
sw s4, 0(sp)
li s4, 0xf0f0f0f0
p.sw x0, s4(x0!)
sw s4, 0(sp)
p.sw x0, s3(x0!)
sw s3, 0(sp)
li s3, 0xf0f0f0f0
p.sw x0, s3(x0!)
sw s3, 0(sp)
p.sw x0, s2(x0!)
sw s2, 0(sp)
li s2, 0xf0f0f0f0
p.sw x0, s2(x0!)
sw s2, 0(sp)
p.sw x0, a7(x0!)
sw a7, 0(sp)
li a7, 0xf0f0f0f0
p.sw x0, a7(x0!)
sw a7, 0(sp)
p.sw x0, a6(x0!)
sw a6, 0(sp)
li a6, 0xf0f0f0f0
p.sw x0, a6(x0!)
sw a6, 0(sp)
p.sw x0, a5(x0!)
sw a5, 0(sp)
li a5, 0xf0f0f0f0
p.sw x0, a5(x0!)
sw a5, 0(sp)
p.sw x0, a4(x0!)
sw a4, 0(sp)
li a4, 0xf0f0f0f0
p.sw x0, a4(x0!)
sw a4, 0(sp)
p.sw x0, a3(x0!)
sw a3, 0(sp)
li a3, 0xf0f0f0f0
p.sw x0, a3(x0!)
sw a3, 0(sp)
p.sw x0, a2(x0!)
sw a2, 0(sp)
li a2, 0xf0f0f0f0
p.sw x0, a2(x0!)
sw a2, 0(sp)
p.sw x0, a1(x0!)
sw a1, 0(sp)
li a1, 0xf0f0f0f0
p.sw x0, a1(x0!)
sw a1, 0(sp)
p.sw x0, a0(x0!)
sw a0, 0(sp)
li a0, 0xf0f0f0f0
p.sw x0, a0(x0!)
sw a0, 0(sp)
p.sw x0, s1(x0!)
sw s1, 0(sp)
li s1, 0xf0f0f0f0
p.sw x0, s1(x0!)
sw s1, 0(sp)
p.sw x0, s0(x0!)
sw s0, 0(sp)
li s0, 0xf0f0f0f0
p.sw x0, s0(x0!)
sw s0, 0(sp)
p.sw x0, t2(x0!)
sw t2, 0(sp)
li t2, 0xf0f0f0f0
p.sw x0, t2(x0!)
sw t2, 0(sp)
p.sw x0, t1(x0!)
sw t1, 0(sp)
li t1, 0xf0f0f0f0
p.sw x0, t1(x0!)
sw t1, 0(sp)
p.sw x0, t0(x0!)
sw t0, 0(sp)
li t0, 0xf0f0f0f0
p.sw x0, t0(x0!)
sw t0, 0(sp)
p.sw x0, ra(x0!)
sw ra, 0(sp)
li ra, 0xf0f0f0f0
p.sw x0, ra(x0!)
sw ra, 0(sp)
li ra, 0xcccccccc
li t0, 0xcccccccc
li t1, 0xcccccccc
li t2, 0xcccccccc
li s0, 0xcccccccc
li s1, 0xcccccccc
li a0, 0xcccccccc
li a1, 0xcccccccc
li a2, 0xcccccccc
li a3, 0xcccccccc
li a4, 0xcccccccc
li a5, 0xcccccccc
li a6, 0xcccccccc
li a7, 0xcccccccc
li s2, 0xcccccccc
li s3, 0xcccccccc
li s4, 0xcccccccc
li s5, 0xcccccccc
li s6, 0xcccccccc
li s7, 0xcccccccc
li s8, 0xcccccccc
li s9, 0xcccccccc
li s10, 0xcccccccc
li s11, 0xcccccccc
li t3, 0xcccccccc
li t4, 0xcccccccc
li t5, 0xcccccccc
li t6, 0xcccccccc
sw ra, 0(sp)
li ra, 0x33333333
sw t0, 0(sp)
li t0, 0x33333333
sw t1, 0(sp)
li t1, 0x33333333
sw t2, 0(sp)
li t2, 0x33333333
sw s0, 0(sp)
li s0, 0x33333333
sw s1, 0(sp)
li s1, 0x33333333
sw a0, 0(sp)
li a0, 0x33333333
sw a1, 0(sp)
li a1, 0x33333333
sw a2, 0(sp)
li a2, 0x33333333
sw a3, 0(sp)
li a3, 0x33333333
sw a4, 0(sp)
li a4, 0x33333333
sw a5, 0(sp)
li a5, 0x33333333
sw a6, 0(sp)
li a6, 0x33333333
sw a7, 0(sp)
li a7, 0x33333333
sw s2, 0(sp)
li s2, 0x33333333
sw s3, 0(sp)
li s3, 0x33333333
sw s4, 0(sp)
li s4, 0x33333333
sw s5, 0(sp)
li s5, 0x33333333
sw s6, 0(sp)
li s6, 0x33333333
sw s7, 0(sp)
li s7, 0x33333333
sw s8, 0(sp)
li s8, 0x33333333
sw s9, 0(sp)
li s9, 0x33333333
sw s10, 0(sp)
li s10, 0x33333333
sw s11, 0(sp)
li s11, 0x33333333
sw t3, 0(sp)
li t3, 0x33333333
sw t4, 0(sp)
li t4, 0x33333333
sw t5, 0(sp)
li t5, 0x33333333
sw t6, 0(sp)
li t6, 0x33333333
sw t6, 0(sp)
li t6, 0xcccccccc
sw t6, 0(sp)
sw t5, 0(sp)
li t5, 0xcccccccc
sw t5, 0(sp)
sw t4, 0(sp)
li t4, 0xcccccccc
sw t4, 0(sp)
sw t3, 0(sp)
li t3, 0xcccccccc
sw t3, 0(sp)
sw s11, 0(sp)
li s11, 0xcccccccc
sw s11, 0(sp)
sw s10, 0(sp)
li s10, 0xcccccccc
sw s10, 0(sp)
sw s9, 0(sp)
li s9, 0xcccccccc
sw s9, 0(sp)
sw s8, 0(sp)
li s8, 0xcccccccc
sw s8, 0(sp)
sw s7, 0(sp)
li s7, 0xcccccccc
sw s7, 0(sp)
sw s6, 0(sp)
li s6, 0xcccccccc
sw s6, 0(sp)
sw s5, 0(sp)
li s5, 0xcccccccc
sw s5, 0(sp)
sw s4, 0(sp)
li s4, 0xcccccccc
sw s4, 0(sp)
sw s3, 0(sp)
li s3, 0xcccccccc
sw s3, 0(sp)
sw s2, 0(sp)
li s2, 0xcccccccc
sw s2, 0(sp)
sw a7, 0(sp)
li a7, 0xcccccccc
sw a7, 0(sp)
sw a6, 0(sp)
li a6, 0xcccccccc
sw a6, 0(sp)
sw a5, 0(sp)
li a5, 0xcccccccc
sw a5, 0(sp)
sw a4, 0(sp)
li a4, 0xcccccccc
sw a4, 0(sp)
sw a3, 0(sp)
li a3, 0xcccccccc
sw a3, 0(sp)
sw a2, 0(sp)
li a2, 0xcccccccc
sw a2, 0(sp)
sw a1, 0(sp)
li a1, 0xcccccccc
sw a1, 0(sp)
sw a0, 0(sp)
li a0, 0xcccccccc
sw a0, 0(sp)
sw s1, 0(sp)
li s1, 0xcccccccc
sw s1, 0(sp)
sw s0, 0(sp)
li s0, 0xcccccccc
sw s0, 0(sp)
sw t2, 0(sp)
li t2, 0xcccccccc
sw t2, 0(sp)
sw t1, 0(sp)
li t1, 0xcccccccc
sw t1, 0(sp)
sw t0, 0(sp)
li t0, 0xcccccccc
sw t0, 0(sp)
sw ra, 0(sp)
li ra, 0xcccccccc
sw ra, 0(sp)
li ra, 0xcccccccc
li t0, 0xcccccccc
li t1, 0xcccccccc
li t2, 0xcccccccc
li s0, 0xcccccccc
li s1, 0xcccccccc
li a0, 0xcccccccc
li a1, 0xcccccccc
li a2, 0xcccccccc
li a3, 0xcccccccc
li a4, 0xcccccccc
li a5, 0xcccccccc
li a6, 0xcccccccc
li a7, 0xcccccccc
li s2, 0xcccccccc
li s3, 0xcccccccc
li s4, 0xcccccccc
li s5, 0xcccccccc
li s6, 0xcccccccc
li s7, 0xcccccccc
li s8, 0xcccccccc
li s9, 0xcccccccc
li s10, 0xcccccccc
li s11, 0xcccccccc
li t3, 0xcccccccc
li t4, 0xcccccccc
li t5, 0xcccccccc
li t6, 0xcccccccc
add ra, x0, ra
sw ra, 0(sp)
li ra, 0x33333333
add t0, x0, t0
sw t0, 0(sp)
li t0, 0x33333333
add t1, x0, t1
sw t1, 0(sp)
li t1, 0x33333333
add t2, x0, t2
sw t2, 0(sp)
li t2, 0x33333333
add s0, x0, s0
sw s0, 0(sp)
li s0, 0x33333333
add s1, x0, s1
sw s1, 0(sp)
li s1, 0x33333333
add a0, x0, a0
sw a0, 0(sp)
li a0, 0x33333333
add a1, x0, a1
sw a1, 0(sp)
li a1, 0x33333333
add a2, x0, a2
sw a2, 0(sp)
li a2, 0x33333333
add a3, x0, a3
sw a3, 0(sp)
li a3, 0x33333333
add a4, x0, a4
sw a4, 0(sp)
li a4, 0x33333333
add a5, x0, a5
sw a5, 0(sp)
li a5, 0x33333333
add a6, x0, a6
sw a6, 0(sp)
li a6, 0x33333333
add a7, x0, a7
sw a7, 0(sp)
li a7, 0x33333333
add s2, x0, s2
sw s2, 0(sp)
li s2, 0x33333333
add s3, x0, s3
sw s3, 0(sp)
li s3, 0x33333333
add s4, x0, s4
sw s4, 0(sp)
li s4, 0x33333333
add s5, x0, s5
sw s5, 0(sp)
li s5, 0x33333333
add s6, x0, s6
sw s6, 0(sp)
li s6, 0x33333333
add s7, x0, s7
sw s7, 0(sp)
li s7, 0x33333333
add s8, x0, s8
sw s8, 0(sp)
li s8, 0x33333333
add s9, x0, s9
sw s9, 0(sp)
li s9, 0x33333333
add s10, x0, s10
sw s10, 0(sp)
li s10, 0x33333333
add s11, x0, s11
sw s11, 0(sp)
li s11, 0x33333333
add t3, x0, t3
sw t3, 0(sp)
li t3, 0x33333333
add t4, x0, t4
sw t4, 0(sp)
li t4, 0x33333333
add t5, x0, t5
sw t5, 0(sp)
li t5, 0x33333333
add t6, x0, t6
sw t6, 0(sp)
li t6, 0x33333333
add t6, x0, t6
sw t6, 0(sp)
li t6, 0xcccccccc
add t6, x0, t6
sw t6, 0(sp)
add t5, x0, t5
sw t5, 0(sp)
li t5, 0xcccccccc
add t5, x0, t5
sw t5, 0(sp)
add t4, x0, t4
sw t4, 0(sp)
li t4, 0xcccccccc
add t4, x0, t4
sw t4, 0(sp)
add t3, x0, t3
sw t3, 0(sp)
li t3, 0xcccccccc
add t3, x0, t3
sw t3, 0(sp)
add s11, x0, s11
sw s11, 0(sp)
li s11, 0xcccccccc
add s11, x0, s11
sw s11, 0(sp)
add s10, x0, s10
sw s10, 0(sp)
li s10, 0xcccccccc
add s10, x0, s10
sw s10, 0(sp)
add s9, x0, s9
sw s9, 0(sp)
li s9, 0xcccccccc
add s9, x0, s9
sw s9, 0(sp)
add s8, x0, s8
sw s8, 0(sp)
li s8, 0xcccccccc
add s8, x0, s8
sw s8, 0(sp)
add s7, x0, s7
sw s7, 0(sp)
li s7, 0xcccccccc
add s7, x0, s7
sw s7, 0(sp)
add s6, x0, s6
sw s6, 0(sp)
li s6, 0xcccccccc
add s6, x0, s6
sw s6, 0(sp)
add s5, x0, s5
sw s5, 0(sp)
li s5, 0xcccccccc
add s5, x0, s5
sw s5, 0(sp)
add s4, x0, s4
sw s4, 0(sp)
li s4, 0xcccccccc
add s4, x0, s4
sw s4, 0(sp)
add s3, x0, s3
sw s3, 0(sp)
li s3, 0xcccccccc
add s3, x0, s3
sw s3, 0(sp)
add s2, x0, s2
sw s2, 0(sp)
li s2, 0xcccccccc
add s2, x0, s2
sw s2, 0(sp)
add a7, x0, a7
sw a7, 0(sp)
li a7, 0xcccccccc
add a7, x0, a7
sw a7, 0(sp)
add a6, x0, a6
sw a6, 0(sp)
li a6, 0xcccccccc
add a6, x0, a6
sw a6, 0(sp)
add a5, x0, a5
sw a5, 0(sp)
li a5, 0xcccccccc
add a5, x0, a5
sw a5, 0(sp)
add a4, x0, a4
sw a4, 0(sp)
li a4, 0xcccccccc
add a4, x0, a4
sw a4, 0(sp)
add a3, x0, a3
sw a3, 0(sp)
li a3, 0xcccccccc
add a3, x0, a3
sw a3, 0(sp)
add a2, x0, a2
sw a2, 0(sp)
li a2, 0xcccccccc
add a2, x0, a2
sw a2, 0(sp)
add a1, x0, a1
sw a1, 0(sp)
li a1, 0xcccccccc
add a1, x0, a1
sw a1, 0(sp)
add a0, x0, a0
sw a0, 0(sp)
li a0, 0xcccccccc
add a0, x0, a0
sw a0, 0(sp)
add s1, x0, s1
sw s1, 0(sp)
li s1, 0xcccccccc
add s1, x0, s1
sw s1, 0(sp)
add s0, x0, s0
sw s0, 0(sp)
li s0, 0xcccccccc
add s0, x0, s0
sw s0, 0(sp)
add t2, x0, t2
sw t2, 0(sp)
li t2, 0xcccccccc
add t2, x0, t2
sw t2, 0(sp)
add t1, x0, t1
sw t1, 0(sp)
li t1, 0xcccccccc
add t1, x0, t1
sw t1, 0(sp)
add t0, x0, t0
sw t0, 0(sp)
li t0, 0xcccccccc
add t0, x0, t0
sw t0, 0(sp)
add ra, x0, ra
sw ra, 0(sp)
li ra, 0xcccccccc
add ra, x0, ra
sw ra, 0(sp)
li ra, 0xcccccccc
li t0, 0xcccccccc
li t1, 0xcccccccc
li t2, 0xcccccccc
li s0, 0xcccccccc
li s1, 0xcccccccc
li a0, 0xcccccccc
li a1, 0xcccccccc
li a2, 0xcccccccc
li a3, 0xcccccccc
li a4, 0xcccccccc
li a5, 0xcccccccc
li a6, 0xcccccccc
li a7, 0xcccccccc
li s2, 0xcccccccc
li s3, 0xcccccccc
li s4, 0xcccccccc
li s5, 0xcccccccc
li s6, 0xcccccccc
li s7, 0xcccccccc
li s8, 0xcccccccc
li s9, 0xcccccccc
li s10, 0xcccccccc
li s11, 0xcccccccc
li t3, 0xcccccccc
li t4, 0xcccccccc
li t5, 0xcccccccc
li t6, 0xcccccccc
p.sw x0, ra(x0!)
sw ra, 0(sp)
li ra, 0x33333333
p.sw x0, t0(x0!)
sw t0, 0(sp)
li t0, 0x33333333
p.sw x0, t1(x0!)
sw t1, 0(sp)
li t1, 0x33333333
p.sw x0, t2(x0!)
sw t2, 0(sp)
li t2, 0x33333333
p.sw x0, s0(x0!)
sw s0, 0(sp)
li s0, 0x33333333
p.sw x0, s1(x0!)
sw s1, 0(sp)
li s1, 0x33333333
p.sw x0, a0(x0!)
sw a0, 0(sp)
li a0, 0x33333333
p.sw x0, a1(x0!)
sw a1, 0(sp)
li a1, 0x33333333
p.sw x0, a2(x0!)
sw a2, 0(sp)
li a2, 0x33333333
p.sw x0, a3(x0!)
sw a3, 0(sp)
li a3, 0x33333333
p.sw x0, a4(x0!)
sw a4, 0(sp)
li a4, 0x33333333
p.sw x0, a5(x0!)
sw a5, 0(sp)
li a5, 0x33333333
p.sw x0, a6(x0!)
sw a6, 0(sp)
li a6, 0x33333333
p.sw x0, a7(x0!)
sw a7, 0(sp)
li a7, 0x33333333
p.sw x0, s2(x0!)
sw s2, 0(sp)
li s2, 0x33333333
p.sw x0, s3(x0!)
sw s3, 0(sp)
li s3, 0x33333333
p.sw x0, s4(x0!)
sw s4, 0(sp)
li s4, 0x33333333
p.sw x0, s5(x0!)
sw s5, 0(sp)
li s5, 0x33333333
p.sw x0, s6(x0!)
sw s6, 0(sp)
li s6, 0x33333333
p.sw x0, s7(x0!)
sw s7, 0(sp)
li s7, 0x33333333
p.sw x0, s8(x0!)
sw s8, 0(sp)
li s8, 0x33333333
p.sw x0, s9(x0!)
sw s9, 0(sp)
li s9, 0x33333333
p.sw x0, s10(x0!)
sw s10, 0(sp)
li s10, 0x33333333
p.sw x0, s11(x0!)
sw s11, 0(sp)
li s11, 0x33333333
p.sw x0, t3(x0!)
sw t3, 0(sp)
li t3, 0x33333333
p.sw x0, t4(x0!)
sw t4, 0(sp)
li t4, 0x33333333
p.sw x0, t5(x0!)
sw t5, 0(sp)
li t5, 0x33333333
p.sw x0, t6(x0!)
sw t6, 0(sp)
li t6, 0x33333333
p.sw x0, t6(x0!)
sw t6, 0(sp)
li t6, 0xcccccccc
p.sw x0, t6(x0!)
sw t6, 0(sp)
p.sw x0, t5(x0!)
sw t5, 0(sp)
li t5, 0xcccccccc
p.sw x0, t5(x0!)
sw t5, 0(sp)
p.sw x0, t4(x0!)
sw t4, 0(sp)
li t4, 0xcccccccc
p.sw x0, t4(x0!)
sw t4, 0(sp)
p.sw x0, t3(x0!)
sw t3, 0(sp)
li t3, 0xcccccccc
p.sw x0, t3(x0!)
sw t3, 0(sp)
p.sw x0, s11(x0!)
sw s11, 0(sp)
li s11, 0xcccccccc
p.sw x0, s11(x0!)
sw s11, 0(sp)
p.sw x0, s10(x0!)
sw s10, 0(sp)
li s10, 0xcccccccc
p.sw x0, s10(x0!)
sw s10, 0(sp)
p.sw x0, s9(x0!)
sw s9, 0(sp)
li s9, 0xcccccccc
p.sw x0, s9(x0!)
sw s9, 0(sp)
p.sw x0, s8(x0!)
sw s8, 0(sp)
li s8, 0xcccccccc
p.sw x0, s8(x0!)
sw s8, 0(sp)
p.sw x0, s7(x0!)
sw s7, 0(sp)
li s7, 0xcccccccc
p.sw x0, s7(x0!)
sw s7, 0(sp)
p.sw x0, s6(x0!)
sw s6, 0(sp)
li s6, 0xcccccccc
p.sw x0, s6(x0!)
sw s6, 0(sp)
p.sw x0, s5(x0!)
sw s5, 0(sp)
li s5, 0xcccccccc
p.sw x0, s5(x0!)
sw s5, 0(sp)
p.sw x0, s4(x0!)
sw s4, 0(sp)
li s4, 0xcccccccc
p.sw x0, s4(x0!)
sw s4, 0(sp)
p.sw x0, s3(x0!)
sw s3, 0(sp)
li s3, 0xcccccccc
p.sw x0, s3(x0!)
sw s3, 0(sp)
p.sw x0, s2(x0!)
sw s2, 0(sp)
li s2, 0xcccccccc
p.sw x0, s2(x0!)
sw s2, 0(sp)
p.sw x0, a7(x0!)
sw a7, 0(sp)
li a7, 0xcccccccc
p.sw x0, a7(x0!)
sw a7, 0(sp)
p.sw x0, a6(x0!)
sw a6, 0(sp)
li a6, 0xcccccccc
p.sw x0, a6(x0!)
sw a6, 0(sp)
p.sw x0, a5(x0!)
sw a5, 0(sp)
li a5, 0xcccccccc
p.sw x0, a5(x0!)
sw a5, 0(sp)
p.sw x0, a4(x0!)
sw a4, 0(sp)
li a4, 0xcccccccc
p.sw x0, a4(x0!)
sw a4, 0(sp)
p.sw x0, a3(x0!)
sw a3, 0(sp)
li a3, 0xcccccccc
p.sw x0, a3(x0!)
sw a3, 0(sp)
p.sw x0, a2(x0!)
sw a2, 0(sp)
li a2, 0xcccccccc
p.sw x0, a2(x0!)
sw a2, 0(sp)
p.sw x0, a1(x0!)
sw a1, 0(sp)
li a1, 0xcccccccc
p.sw x0, a1(x0!)
sw a1, 0(sp)
p.sw x0, a0(x0!)
sw a0, 0(sp)
li a0, 0xcccccccc
p.sw x0, a0(x0!)
sw a0, 0(sp)
p.sw x0, s1(x0!)
sw s1, 0(sp)
li s1, 0xcccccccc
p.sw x0, s1(x0!)
sw s1, 0(sp)
p.sw x0, s0(x0!)
sw s0, 0(sp)
li s0, 0xcccccccc
p.sw x0, s0(x0!)
sw s0, 0(sp)
p.sw x0, t2(x0!)
sw t2, 0(sp)
li t2, 0xcccccccc
p.sw x0, t2(x0!)
sw t2, 0(sp)
p.sw x0, t1(x0!)
sw t1, 0(sp)
li t1, 0xcccccccc
p.sw x0, t1(x0!)
sw t1, 0(sp)
p.sw x0, t0(x0!)
sw t0, 0(sp)
li t0, 0xcccccccc
p.sw x0, t0(x0!)
sw t0, 0(sp)
p.sw x0, ra(x0!)
sw ra, 0(sp)
li ra, 0xcccccccc
p.sw x0, ra(x0!)
sw ra, 0(sp)
li ra, 0xaaaaaaaa
li t0, 0xaaaaaaaa
li t1, 0xaaaaaaaa
li t2, 0xaaaaaaaa
li s0, 0xaaaaaaaa
li s1, 0xaaaaaaaa
li a0, 0xaaaaaaaa
li a1, 0xaaaaaaaa
li a2, 0xaaaaaaaa
li a3, 0xaaaaaaaa
li a4, 0xaaaaaaaa
li a5, 0xaaaaaaaa
li a6, 0xaaaaaaaa
li a7, 0xaaaaaaaa
li s2, 0xaaaaaaaa
li s3, 0xaaaaaaaa
li s4, 0xaaaaaaaa
li s5, 0xaaaaaaaa
li s6, 0xaaaaaaaa
li s7, 0xaaaaaaaa
li s8, 0xaaaaaaaa
li s9, 0xaaaaaaaa
li s10, 0xaaaaaaaa
li s11, 0xaaaaaaaa
li t3, 0xaaaaaaaa
li t4, 0xaaaaaaaa
li t5, 0xaaaaaaaa
li t6, 0xaaaaaaaa
sw ra, 0(sp)
li ra, 0x55555555
sw t0, 0(sp)
li t0, 0x55555555
sw t1, 0(sp)
li t1, 0x55555555
sw t2, 0(sp)
li t2, 0x55555555
sw s0, 0(sp)
li s0, 0x55555555
sw s1, 0(sp)
li s1, 0x55555555
sw a0, 0(sp)
li a0, 0x55555555
sw a1, 0(sp)
li a1, 0x55555555
sw a2, 0(sp)
li a2, 0x55555555
sw a3, 0(sp)
li a3, 0x55555555
sw a4, 0(sp)
li a4, 0x55555555
sw a5, 0(sp)
li a5, 0x55555555
sw a6, 0(sp)
li a6, 0x55555555
sw a7, 0(sp)
li a7, 0x55555555
sw s2, 0(sp)
li s2, 0x55555555
sw s3, 0(sp)
li s3, 0x55555555
sw s4, 0(sp)
li s4, 0x55555555
sw s5, 0(sp)
li s5, 0x55555555
sw s6, 0(sp)
li s6, 0x55555555
sw s7, 0(sp)
li s7, 0x55555555
sw s8, 0(sp)
li s8, 0x55555555
sw s9, 0(sp)
li s9, 0x55555555
sw s10, 0(sp)
li s10, 0x55555555
sw s11, 0(sp)
li s11, 0x55555555
sw t3, 0(sp)
li t3, 0x55555555
sw t4, 0(sp)
li t4, 0x55555555
sw t5, 0(sp)
li t5, 0x55555555
sw t6, 0(sp)
li t6, 0x55555555
sw t6, 0(sp)
li t6, 0xaaaaaaaa
sw t6, 0(sp)
sw t5, 0(sp)
li t5, 0xaaaaaaaa
sw t5, 0(sp)
sw t4, 0(sp)
li t4, 0xaaaaaaaa
sw t4, 0(sp)
sw t3, 0(sp)
li t3, 0xaaaaaaaa
sw t3, 0(sp)
sw s11, 0(sp)
li s11, 0xaaaaaaaa
sw s11, 0(sp)
sw s10, 0(sp)
li s10, 0xaaaaaaaa
sw s10, 0(sp)
sw s9, 0(sp)
li s9, 0xaaaaaaaa
sw s9, 0(sp)
sw s8, 0(sp)
li s8, 0xaaaaaaaa
sw s8, 0(sp)
sw s7, 0(sp)
li s7, 0xaaaaaaaa
sw s7, 0(sp)
sw s6, 0(sp)
li s6, 0xaaaaaaaa
sw s6, 0(sp)
sw s5, 0(sp)
li s5, 0xaaaaaaaa
sw s5, 0(sp)
sw s4, 0(sp)
li s4, 0xaaaaaaaa
sw s4, 0(sp)
sw s3, 0(sp)
li s3, 0xaaaaaaaa
sw s3, 0(sp)
sw s2, 0(sp)
li s2, 0xaaaaaaaa
sw s2, 0(sp)
sw a7, 0(sp)
li a7, 0xaaaaaaaa
sw a7, 0(sp)
sw a6, 0(sp)
li a6, 0xaaaaaaaa
sw a6, 0(sp)
sw a5, 0(sp)
li a5, 0xaaaaaaaa
sw a5, 0(sp)
sw a4, 0(sp)
li a4, 0xaaaaaaaa
sw a4, 0(sp)
sw a3, 0(sp)
li a3, 0xaaaaaaaa
sw a3, 0(sp)
sw a2, 0(sp)
li a2, 0xaaaaaaaa
sw a2, 0(sp)
sw a1, 0(sp)
li a1, 0xaaaaaaaa
sw a1, 0(sp)
sw a0, 0(sp)
li a0, 0xaaaaaaaa
sw a0, 0(sp)
sw s1, 0(sp)
li s1, 0xaaaaaaaa
sw s1, 0(sp)
sw s0, 0(sp)
li s0, 0xaaaaaaaa
sw s0, 0(sp)
sw t2, 0(sp)
li t2, 0xaaaaaaaa
sw t2, 0(sp)
sw t1, 0(sp)
li t1, 0xaaaaaaaa
sw t1, 0(sp)
sw t0, 0(sp)
li t0, 0xaaaaaaaa
sw t0, 0(sp)
sw ra, 0(sp)
li ra, 0xaaaaaaaa
sw ra, 0(sp)
li ra, 0xaaaaaaaa
li t0, 0xaaaaaaaa
li t1, 0xaaaaaaaa
li t2, 0xaaaaaaaa
li s0, 0xaaaaaaaa
li s1, 0xaaaaaaaa
li a0, 0xaaaaaaaa
li a1, 0xaaaaaaaa
li a2, 0xaaaaaaaa
li a3, 0xaaaaaaaa
li a4, 0xaaaaaaaa
li a5, 0xaaaaaaaa
li a6, 0xaaaaaaaa
li a7, 0xaaaaaaaa
li s2, 0xaaaaaaaa
li s3, 0xaaaaaaaa
li s4, 0xaaaaaaaa
li s5, 0xaaaaaaaa
li s6, 0xaaaaaaaa
li s7, 0xaaaaaaaa
li s8, 0xaaaaaaaa
li s9, 0xaaaaaaaa
li s10, 0xaaaaaaaa
li s11, 0xaaaaaaaa
li t3, 0xaaaaaaaa
li t4, 0xaaaaaaaa
li t5, 0xaaaaaaaa
li t6, 0xaaaaaaaa
add ra, x0, ra
sw ra, 0(sp)
li ra, 0x55555555
add t0, x0, t0
sw t0, 0(sp)
li t0, 0x55555555
add t1, x0, t1
sw t1, 0(sp)
li t1, 0x55555555
add t2, x0, t2
sw t2, 0(sp)
li t2, 0x55555555
add s0, x0, s0
sw s0, 0(sp)
li s0, 0x55555555
add s1, x0, s1
sw s1, 0(sp)
li s1, 0x55555555
add a0, x0, a0
sw a0, 0(sp)
li a0, 0x55555555
add a1, x0, a1
sw a1, 0(sp)
li a1, 0x55555555
add a2, x0, a2
sw a2, 0(sp)
li a2, 0x55555555
add a3, x0, a3
sw a3, 0(sp)
li a3, 0x55555555
add a4, x0, a4
sw a4, 0(sp)
li a4, 0x55555555
add a5, x0, a5
sw a5, 0(sp)
li a5, 0x55555555
add a6, x0, a6
sw a6, 0(sp)
li a6, 0x55555555
add a7, x0, a7
sw a7, 0(sp)
li a7, 0x55555555
add s2, x0, s2
sw s2, 0(sp)
li s2, 0x55555555
add s3, x0, s3
sw s3, 0(sp)
li s3, 0x55555555
add s4, x0, s4
sw s4, 0(sp)
li s4, 0x55555555
add s5, x0, s5
sw s5, 0(sp)
li s5, 0x55555555
add s6, x0, s6
sw s6, 0(sp)
li s6, 0x55555555
add s7, x0, s7
sw s7, 0(sp)
li s7, 0x55555555
add s8, x0, s8
sw s8, 0(sp)
li s8, 0x55555555
add s9, x0, s9
sw s9, 0(sp)
li s9, 0x55555555
add s10, x0, s10
sw s10, 0(sp)
li s10, 0x55555555
add s11, x0, s11
sw s11, 0(sp)
li s11, 0x55555555
add t3, x0, t3
sw t3, 0(sp)
li t3, 0x55555555
add t4, x0, t4
sw t4, 0(sp)
li t4, 0x55555555
add t5, x0, t5
sw t5, 0(sp)
li t5, 0x55555555
add t6, x0, t6
sw t6, 0(sp)
li t6, 0x55555555
add t6, x0, t6
sw t6, 0(sp)
li t6, 0xaaaaaaaa
add t6, x0, t6
sw t6, 0(sp)
add t5, x0, t5
sw t5, 0(sp)
li t5, 0xaaaaaaaa
add t5, x0, t5
sw t5, 0(sp)
add t4, x0, t4
sw t4, 0(sp)
li t4, 0xaaaaaaaa
add t4, x0, t4
sw t4, 0(sp)
add t3, x0, t3
sw t3, 0(sp)
li t3, 0xaaaaaaaa
add t3, x0, t3
sw t3, 0(sp)
add s11, x0, s11
sw s11, 0(sp)
li s11, 0xaaaaaaaa
add s11, x0, s11
sw s11, 0(sp)
add s10, x0, s10
sw s10, 0(sp)
li s10, 0xaaaaaaaa
add s10, x0, s10
sw s10, 0(sp)
add s9, x0, s9
sw s9, 0(sp)
li s9, 0xaaaaaaaa
add s9, x0, s9
sw s9, 0(sp)
add s8, x0, s8
sw s8, 0(sp)
li s8, 0xaaaaaaaa
add s8, x0, s8
sw s8, 0(sp)
add s7, x0, s7
sw s7, 0(sp)
li s7, 0xaaaaaaaa
add s7, x0, s7
sw s7, 0(sp)
add s6, x0, s6
sw s6, 0(sp)
li s6, 0xaaaaaaaa
add s6, x0, s6
sw s6, 0(sp)
add s5, x0, s5
sw s5, 0(sp)
li s5, 0xaaaaaaaa
add s5, x0, s5
sw s5, 0(sp)
add s4, x0, s4
sw s4, 0(sp)
li s4, 0xaaaaaaaa
add s4, x0, s4
sw s4, 0(sp)
add s3, x0, s3
sw s3, 0(sp)
li s3, 0xaaaaaaaa
add s3, x0, s3
sw s3, 0(sp)
add s2, x0, s2
sw s2, 0(sp)
li s2, 0xaaaaaaaa
add s2, x0, s2
sw s2, 0(sp)
add a7, x0, a7
sw a7, 0(sp)
li a7, 0xaaaaaaaa
add a7, x0, a7
sw a7, 0(sp)
add a6, x0, a6
sw a6, 0(sp)
li a6, 0xaaaaaaaa
add a6, x0, a6
sw a6, 0(sp)
add a5, x0, a5
sw a5, 0(sp)
li a5, 0xaaaaaaaa
add a5, x0, a5
sw a5, 0(sp)
add a4, x0, a4
sw a4, 0(sp)
li a4, 0xaaaaaaaa
add a4, x0, a4
sw a4, 0(sp)
add a3, x0, a3
sw a3, 0(sp)
li a3, 0xaaaaaaaa
add a3, x0, a3
sw a3, 0(sp)
add a2, x0, a2
sw a2, 0(sp)
li a2, 0xaaaaaaaa
add a2, x0, a2
sw a2, 0(sp)
add a1, x0, a1
sw a1, 0(sp)
li a1, 0xaaaaaaaa
add a1, x0, a1
sw a1, 0(sp)
add a0, x0, a0
sw a0, 0(sp)
li a0, 0xaaaaaaaa
add a0, x0, a0
sw a0, 0(sp)
add s1, x0, s1
sw s1, 0(sp)
li s1, 0xaaaaaaaa
add s1, x0, s1
sw s1, 0(sp)
add s0, x0, s0
sw s0, 0(sp)
li s0, 0xaaaaaaaa
add s0, x0, s0
sw s0, 0(sp)
add t2, x0, t2
sw t2, 0(sp)
li t2, 0xaaaaaaaa
add t2, x0, t2
sw t2, 0(sp)
add t1, x0, t1
sw t1, 0(sp)
li t1, 0xaaaaaaaa
add t1, x0, t1
sw t1, 0(sp)
add t0, x0, t0
sw t0, 0(sp)
li t0, 0xaaaaaaaa
add t0, x0, t0
sw t0, 0(sp)
add ra, x0, ra
sw ra, 0(sp)
li ra, 0xaaaaaaaa
add ra, x0, ra
sw ra, 0(sp)
li ra, 0xaaaaaaaa
li t0, 0xaaaaaaaa
li t1, 0xaaaaaaaa
li t2, 0xaaaaaaaa
li s0, 0xaaaaaaaa
li s1, 0xaaaaaaaa
li a0, 0xaaaaaaaa
li a1, 0xaaaaaaaa
li a2, 0xaaaaaaaa
li a3, 0xaaaaaaaa
li a4, 0xaaaaaaaa
li a5, 0xaaaaaaaa
li a6, 0xaaaaaaaa
li a7, 0xaaaaaaaa
li s2, 0xaaaaaaaa
li s3, 0xaaaaaaaa
li s4, 0xaaaaaaaa
li s5, 0xaaaaaaaa
li s6, 0xaaaaaaaa
li s7, 0xaaaaaaaa
li s8, 0xaaaaaaaa
li s9, 0xaaaaaaaa
li s10, 0xaaaaaaaa
li s11, 0xaaaaaaaa
li t3, 0xaaaaaaaa
li t4, 0xaaaaaaaa
li t5, 0xaaaaaaaa
li t6, 0xaaaaaaaa
p.sw x0, ra(x0!)
sw ra, 0(sp)
li ra, 0x55555555
p.sw x0, t0(x0!)
sw t0, 0(sp)
li t0, 0x55555555
p.sw x0, t1(x0!)
sw t1, 0(sp)
li t1, 0x55555555
p.sw x0, t2(x0!)
sw t2, 0(sp)
li t2, 0x55555555
p.sw x0, s0(x0!)
sw s0, 0(sp)
li s0, 0x55555555
p.sw x0, s1(x0!)
sw s1, 0(sp)
li s1, 0x55555555
p.sw x0, a0(x0!)
sw a0, 0(sp)
li a0, 0x55555555
p.sw x0, a1(x0!)
sw a1, 0(sp)
li a1, 0x55555555
p.sw x0, a2(x0!)
sw a2, 0(sp)
li a2, 0x55555555
p.sw x0, a3(x0!)
sw a3, 0(sp)
li a3, 0x55555555
p.sw x0, a4(x0!)
sw a4, 0(sp)
li a4, 0x55555555
p.sw x0, a5(x0!)
sw a5, 0(sp)
li a5, 0x55555555
p.sw x0, a6(x0!)
sw a6, 0(sp)
li a6, 0x55555555
p.sw x0, a7(x0!)
sw a7, 0(sp)
li a7, 0x55555555
p.sw x0, s2(x0!)
sw s2, 0(sp)
li s2, 0x55555555
p.sw x0, s3(x0!)
sw s3, 0(sp)
li s3, 0x55555555
p.sw x0, s4(x0!)
sw s4, 0(sp)
li s4, 0x55555555
p.sw x0, s5(x0!)
sw s5, 0(sp)
li s5, 0x55555555
p.sw x0, s6(x0!)
sw s6, 0(sp)
li s6, 0x55555555
p.sw x0, s7(x0!)
sw s7, 0(sp)
li s7, 0x55555555
p.sw x0, s8(x0!)
sw s8, 0(sp)
li s8, 0x55555555
p.sw x0, s9(x0!)
sw s9, 0(sp)
li s9, 0x55555555
p.sw x0, s10(x0!)
sw s10, 0(sp)
li s10, 0x55555555
p.sw x0, s11(x0!)
sw s11, 0(sp)
li s11, 0x55555555
p.sw x0, t3(x0!)
sw t3, 0(sp)
li t3, 0x55555555
p.sw x0, t4(x0!)
sw t4, 0(sp)
li t4, 0x55555555
p.sw x0, t5(x0!)
sw t5, 0(sp)
li t5, 0x55555555
p.sw x0, t6(x0!)
sw t6, 0(sp)
li t6, 0x55555555
p.sw x0, t6(x0!)
sw t6, 0(sp)
li t6, 0xaaaaaaaa
p.sw x0, t6(x0!)
sw t6, 0(sp)
p.sw x0, t5(x0!)
sw t5, 0(sp)
li t5, 0xaaaaaaaa
p.sw x0, t5(x0!)
sw t5, 0(sp)
p.sw x0, t4(x0!)
sw t4, 0(sp)
li t4, 0xaaaaaaaa
p.sw x0, t4(x0!)
sw t4, 0(sp)
p.sw x0, t3(x0!)
sw t3, 0(sp)
li t3, 0xaaaaaaaa
p.sw x0, t3(x0!)
sw t3, 0(sp)
p.sw x0, s11(x0!)
sw s11, 0(sp)
li s11, 0xaaaaaaaa
p.sw x0, s11(x0!)
sw s11, 0(sp)
p.sw x0, s10(x0!)
sw s10, 0(sp)
li s10, 0xaaaaaaaa
p.sw x0, s10(x0!)
sw s10, 0(sp)
p.sw x0, s9(x0!)
sw s9, 0(sp)
li s9, 0xaaaaaaaa
p.sw x0, s9(x0!)
sw s9, 0(sp)
p.sw x0, s8(x0!)
sw s8, 0(sp)
li s8, 0xaaaaaaaa
p.sw x0, s8(x0!)
sw s8, 0(sp)
p.sw x0, s7(x0!)
sw s7, 0(sp)
li s7, 0xaaaaaaaa
p.sw x0, s7(x0!)
sw s7, 0(sp)
p.sw x0, s6(x0!)
sw s6, 0(sp)
li s6, 0xaaaaaaaa
p.sw x0, s6(x0!)
sw s6, 0(sp)
p.sw x0, s5(x0!)
sw s5, 0(sp)
li s5, 0xaaaaaaaa
p.sw x0, s5(x0!)
sw s5, 0(sp)
p.sw x0, s4(x0!)
sw s4, 0(sp)
li s4, 0xaaaaaaaa
p.sw x0, s4(x0!)
sw s4, 0(sp)
p.sw x0, s3(x0!)
sw s3, 0(sp)
li s3, 0xaaaaaaaa
p.sw x0, s3(x0!)
sw s3, 0(sp)
p.sw x0, s2(x0!)
sw s2, 0(sp)
li s2, 0xaaaaaaaa
p.sw x0, s2(x0!)
sw s2, 0(sp)
p.sw x0, a7(x0!)
sw a7, 0(sp)
li a7, 0xaaaaaaaa
p.sw x0, a7(x0!)
sw a7, 0(sp)
p.sw x0, a6(x0!)
sw a6, 0(sp)
li a6, 0xaaaaaaaa
p.sw x0, a6(x0!)
sw a6, 0(sp)
p.sw x0, a5(x0!)
sw a5, 0(sp)
li a5, 0xaaaaaaaa
p.sw x0, a5(x0!)
sw a5, 0(sp)
p.sw x0, a4(x0!)
sw a4, 0(sp)
li a4, 0xaaaaaaaa
p.sw x0, a4(x0!)
sw a4, 0(sp)
p.sw x0, a3(x0!)
sw a3, 0(sp)
li a3, 0xaaaaaaaa
p.sw x0, a3(x0!)
sw a3, 0(sp)
p.sw x0, a2(x0!)
sw a2, 0(sp)
li a2, 0xaaaaaaaa
p.sw x0, a2(x0!)
sw a2, 0(sp)
p.sw x0, a1(x0!)
sw a1, 0(sp)
li a1, 0xaaaaaaaa
p.sw x0, a1(x0!)
sw a1, 0(sp)
p.sw x0, a0(x0!)
sw a0, 0(sp)
li a0, 0xaaaaaaaa
p.sw x0, a0(x0!)
sw a0, 0(sp)
p.sw x0, s1(x0!)
sw s1, 0(sp)
li s1, 0xaaaaaaaa
p.sw x0, s1(x0!)
sw s1, 0(sp)
p.sw x0, s0(x0!)
sw s0, 0(sp)
li s0, 0xaaaaaaaa
p.sw x0, s0(x0!)
sw s0, 0(sp)
p.sw x0, t2(x0!)
sw t2, 0(sp)
li t2, 0xaaaaaaaa
p.sw x0, t2(x0!)
sw t2, 0(sp)
p.sw x0, t1(x0!)
sw t1, 0(sp)
li t1, 0xaaaaaaaa
p.sw x0, t1(x0!)
sw t1, 0(sp)
p.sw x0, t0(x0!)
sw t0, 0(sp)
li t0, 0xaaaaaaaa
p.sw x0, t0(x0!)
sw t0, 0(sp)
p.sw x0, ra(x0!)
sw ra, 0(sp)
li ra, 0xaaaaaaaa
p.sw x0, ra(x0!)
sw ra, 0(sp)
