li t0, 0x800bf7e0
li t1, 0x9c8d2007
li t3, 0x7808002a
li t4, 0x70067826
p.msu  t2, t0, t1
pv.sdotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu  t2, t0, t1
pv.dotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x481d1211
li t1, 0xc882585b
li t3, 0x85380b07
li t4, 0xb0c8be54
pv.dotup.b t2, t0, t1
p.msu t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.b t2, t0, t1
p.msu t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x9800083d
li t1, 0x6001059a
li t3, 0xaf007f1f
li t4, 0x7717ac6e
p.msu t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x77e9cd0b
li t1, 0xd26470f9
li t3, 0x3c5162d9
li t4, 0x39c5fdad
pv.dotusp.b t2, t0, t1
pv.sdotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotusp.b t2, t0, t1
pv.dotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x41e0fc1
li t1, 0x93bf0ac8
li t3, 0xfe5fde86
li t4, 0xfae47fe
p.msu  t2, t0, t1
pv.sdotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu  t2, t0, t1
pv.dotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x24acf77e
li t1, 0x2e37dd13
li t3, 0xd338b91f
li t4, 0xd93019a5
p.muls t2, t0, t1
p.msu t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x9008028e
li t1, 0x51c12103
li t3, 0xa244cfe7
li t4, 0xac963e84
pv.dotup.h t2, t0, t1
p.msu t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.h t2, t0, t1
p.msu t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xf3dc1f20
li t1, 0x6801b0ee
li t3, 0x87965115
li t4, 0xceb4d310
p.mac t2, t0, t1
pv.sdotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mac t2, t0, t1
pv.dotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xa808800f
li t1, 0x53e85888
li t3, 0xcf2fe9d0
li t4, 0x6477fe87
p.mac  t2, t0, t1
pv.sdotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mac  t2, t0, t1
pv.dotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x71f1c09f
li t1, 0xea2b05a8
li t3, 0xe1e59445
li t4, 0x7bad34c4
p.msu t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x1eddc90
li t1, 0x972d31a3
li t3, 0x109a8797
li t4, 0xab396650
pv.dotsp.h t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotsp.h t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x3f1ff4bf
li t1, 0xa1c1f85f
li t3, 0x68250e7e
li t4, 0xc7734f1a
p.msu t2, t0, t1
pv.sdotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu t2, t0, t1
pv.dotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x9f88734e
li t1, 0x10d5f8dd
li t3, 0xb412873f
li t4, 0x63b9a78d
p.msu t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x7022319d
li t1, 0x6257950b
li t3, 0x3a610e2a
li t4, 0xa3332ff4
pv.dotsp.b t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotsp.b t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xa3e1f0e8
li t1, 0x3fc783c3
li t3, 0x1d308715
li t4, 0x519997fa
p.msu t2, t0, t1
pv.sdotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu t2, t0, t1
pv.dotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x63ee9030
li t1, 0x32a8bef6
li t3, 0xeef00e3f
li t4, 0xba2337cf
p.msu t2, t0, t1
pv.sdotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu t2, t0, t1
pv.dotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x708a51c
li t1, 0xf9b497ba
li t3, 0xcb882555
li t4, 0x67ff33ea
p.mulu t2, t0, t1
pv.sdotusp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mulu t2, t0, t1
pv.dotusp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x1915800f
li t1, 0xf1c7370d
li t3, 0xb31e5c55
li t4, 0xbfe12860
p.msu t2, t0, t1
p.msu  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xa39b5523
li t1, 0xa1326706
li t3, 0x7806dd0f
li t4, 0x4bf30441
p.msu  t2, t0, t1
p.mac  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x4c5db84
li t1, 0x60481ce0
li t3, 0x556fc33c
li t4, 0x2c0c65f9
p.msu t2, t0, t1
p.mac t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x1cc83c2f
li t1, 0x85a90fac
li t3, 0xc5011085
li t4, 0x7a56e1b1
p.msu  t2, t0, t1
p.msu  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x9570b41f
li t1, 0xb81101c1
li t3, 0x12241141
li t4, 0x11cd418e
p.msu  t2, t0, t1
p.mac t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xe7f0ac9d
li t1, 0x364a55d2
li t3, 0xef685897
li t4, 0x8abc01e8
pv.dotup.h t2, t0, t1
pv.sdotsp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.h t2, t0, t1
pv.dotsp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x73f8564e
li t1, 0x9b252ae9
li t3, 0xf7b42c4b
li t4, 0xc55e00f4
p.muls t2, t0, t1
pv.sdotusp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.muls t2, t0, t1
pv.dotusp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x88fe2342
li t1, 0x9e86e83f
li t3, 0x842162ff
li t4, 0x84804cb
p.msu  t2, t0, t1
p.msu  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xe5b0d116
li t1, 0xa2522817
li t3, 0x37016081
li t4, 0xbf4300ee
p.msu t2, t0, t1
p.msu  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xa80c085f
li t1, 0xa84401e0
li t3, 0xfd04f009
li t4, 0xca5ca02b
p.msu  t2, t0, t1
p.msu t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x7dc5b10d
li t1, 0xac8dc27d
li t3, 0xb495e654
li t4, 0x57cbdc4
p.mulhhs t2, t0, t1
p.msu  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x1cf924d
li t1, 0x64a7c4df
li t3, 0xe99b3cb4
li t4, 0xdaf57b78
pv.dotsp.h t2, t0, t1
pv.sdotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotsp.h t2, t0, t1
pv.dotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x80e7c926
li t1, 0xb253e26f
li t3, 0xf4cd9e5a
li t4, 0x6d7abdbc
pv.dotusp.h t2, t0, t1
pv.sdotusp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotusp.h t2, t0, t1
pv.dotusp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xc1bc76de
li t1, 0x3d8e35e8
li t3, 0x13fdf399
li t4, 0xec4825a6
pv.dotusp.h t2, t0, t1
pv.sdotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotusp.h t2, t0, t1
pv.dotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xe111a922
li t1, 0x7a60de2b
li t3, 0x6065c578
li t4, 0x2cd169ab
pv.dotsp.h t2, t0, t1
pv.sdotup.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotsp.h t2, t0, t1
pv.dotup.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xc87f3068
li t1, 0x1921cebe
li t3, 0xe1e4152c
li t4, 0xc28f07d5
p.msu  t2, t0, t1
p.msu  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x78a3a36e
li t1, 0x2ccbd5e5
li t3, 0x6cd4ef04
li t4, 0x664ee7d6
p.muls t2, t0, t1
pv.sdotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.muls t2, t0, t1
pv.dotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xbd9e43fa
li t1, 0x72c22e2d
li t3, 0x5ff14b36
li t4, 0xe9d20893
pv.dotup.h t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.h t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xaea802b3
li t1, 0xf8174f54
li t3, 0xfe676e79
li t4, 0x6081f95c
pv.dotup.h t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.h t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x57540159
li t1, 0xfc0ba7aa
li t3, 0x7f33b73c
li t4, 0xb040fcae
pv.dotup.b t2, t0, t1
pv.sdotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.b t2, t0, t1
pv.dotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x2baa00ac
li t1, 0xfe05d3d5
li t3, 0xbf99db9e
li t4, 0x58207e57
p.muls t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.muls t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x65e16da0
li t1, 0x74baa922
li t3, 0x99586a04
li t4, 0x90c3eca8
pv.dotup.h t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.h t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x333f249d
li t1, 0x5efa904e
li t3, 0xa53709b6
li t4, 0x92948d2c
pv.dotup.h t2, t0, t1
pv.sdotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.h t2, t0, t1
pv.dotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x199f924e
li t1, 0xaf7d4827
li t3, 0xd29b84db
li t4, 0x494a4696
pv.dotup.b t2, t0, t1
pv.sdotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.b t2, t0, t1
pv.dotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xd005b6a
li t1, 0x331960cc
li t3, 0xd6fed9
li t4, 0x7e505833
p.mac t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mac t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x874fbff8
li t1, 0x7d2b74b9
li t3, 0xe9f043d8
li t4, 0x65dd5761
pv.dotup.h t2, t0, t1
pv.sdotusp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.h t2, t0, t1
pv.dotusp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x43a7dffc
li t1, 0x3e95ba5c
li t3, 0xf4f821ec
li t4, 0x32eeabb0
p.msu t2, t0, t1
pv.sdotup.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu t2, t0, t1
pv.dotup.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xa1d3effe
li t1, 0x1f4add2e
li t3, 0x7a7c10f6
li t4, 0x197755d8
pv.dotup.b t2, t0, t1
pv.sdotup.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.b t2, t0, t1
pv.dotup.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x6017da02
li t1, 0x8d8c80bf
li t3, 0x4820c224
li t4, 0x83fde29a
p.msu t2, t0, t1
p.msu  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x854c000c
li t1, 0xa34bbfc1
li t3, 0x132f2c45
li t4, 0x13c57171
p.msu  t2, t0, t1
p.mac  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x11e5d174
li t1, 0x66eb802e
li t3, 0xcccc0438
li t4, 0x184c6151
p.muls t2, t0, t1
p.msu  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xaa54f140
li t1, 0x37c43805
li t3, 0x8f398ff0
li t4, 0x5411d579
p.msu t2, t0, t1
p.mac  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x3a0e8a2c
li t1, 0x5da00250
li t3, 0xbb137c56
li t4, 0x68081c6b
pv.dotup.b t2, t0, t1
p.msu  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.b t2, t0, t1
p.msu  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x1cf924d6
li t1, 0x4a7c4dfe
li t3, 0x99b3cb4d
li t4, 0xaf57b78d
pv.dotup.b t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.b t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xe7c926b
li t1, 0x253e26ff
li t3, 0x4cd9e5a6
li t4, 0xd7abdbc6
p.mulhhu t2, t0, t1
pv.sdotsp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mulhhu t2, t0, t1
pv.dotsp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x43d0584
li t1, 0x12dfb2f7
li t3, 0xa24b2168
li t4, 0x6adf27f0
p.mulu t2, t0, t1
p.msu t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x39f202c
li t1, 0x49038b7b
li t3, 0xd170f24f
li t4, 0xb5e5204c
pv.dotup.h t2, t0, t1
p.msu t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.h t2, t0, t1
p.msu t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xb3018035
li t1, 0x300071dd
li t3, 0xe0bd380e
li t4, 0x7a701cfa
p.msu  t2, t0, t1
p.mac t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x7c035876
li t1, 0x52e6708a
li t3, 0xd8c115a0
li t4, 0xf6f6d48f
pv.dotusp.b t2, t0, t1
pv.sdotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotusp.b t2, t0, t1
pv.dotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x46071cd7
li t1, 0x8cbfd950
li t3, 0x5de2a191
li t4, 0x9696c358
pv.dotup.h t2, t0, t1
pv.sdotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.h t2, t0, t1
pv.dotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xdb053e87
li t1, 0x63930dbd
li t3, 0x1f737b89
li t4, 0x26a6c8b3
pv.dotup.h t2, t0, t1
pv.sdotsp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.h t2, t0, t1
pv.dotsp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x95842faf
li t1, 0x140567cb
li t3, 0x3e3b9685
li t4, 0x7ebecd46
pv.dotup.h t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.h t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x4ac217d7
li t1, 0x8a02b3e5
li t3, 0x1f1dcb42
li t4, 0xbf5f66a3
pv.dotsp.b t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotsp.b t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x5d67bb07
li t1, 0x60cdb8e7
li t3, 0xbe0ccee0
li t4, 0xb2421a4e
pv.dotsp.h t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotsp.h t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xaeb3dd83
li t1, 0xb066dc73
li t3, 0x5f066770
li t4, 0x59210d27
pv.dotsp.h t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotsp.h t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x2f5f5e2d
li t1, 0x7dff8f2c
li t3, 0x9e1ca0e7
li t4, 0xc1f3881c
p.mac t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mac t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x97afaf16
li t1, 0xbeffc796
li t3, 0x4f008c7d
li t4, 0x60be97c6
p.msu t2, t0, t1
pv.sdotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu t2, t0, t1
pv.dotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xcbd7d78b
li t1, 0x5f7fe3cb
li t3, 0xa780463e
li t4, 0x705f4be3
pv.dotup.h t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.h t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x9ded5b29
li t1, 0xa7310f0
li t3, 0xe242085e
li t4, 0xd5c20cee
pv.dotsp.b t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotsp.b t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x36f01d78
li t1, 0x20f5696d
li t3, 0xc0a32f6e
li t4, 0x870caf68
pv.dotsp.h t2, t0, t1
pv.sdotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotsp.h t2, t0, t1
pv.dotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x9b780ebc
li t1, 0x107ab4b6
li t3, 0xe05197b7
li t4, 0x438657b4
pv.dotsp.h t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotsp.h t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x9add5bd9
li t1, 0x56f8dda7
li t3, 0xe0d5704d
li t4, 0x26174162
p.msu t2, t0, t1
pv.sdotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu t2, t0, t1
pv.dotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x35681d00
li t1, 0xeb08fc6
li t3, 0x41e89367
li t4, 0x7ee609ae
p.muls t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.muls t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x3039f406
li t1, 0x50c0ff39
li t3, 0x48bb3179
li t4, 0x294f56e4
p.mac t2, t0, t1
pv.sdotup.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mac t2, t0, t1
pv.dotup.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x98af7c0f
li t1, 0xa8ad4231
li t3, 0x245d98bc
li t4, 0x94a7ab72
p.msu t2, t0, t1
pv.sdotsp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu t2, t0, t1
pv.dotsp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xcc5657cd
li t1, 0x945294de
li t3, 0x922ecc5e
li t4, 0x4a53d5b9
pv.dotusp.h t2, t0, t1
pv.sdotusp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotusp.h t2, t0, t1
pv.dotusp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xe63ecc1e
li t1, 0xc388c161
li t3, 0xc9b17c0b
li t4, 0xa5aad838
p.msu  t2, t0, t1
p.msu  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x8f17acdf
li t1, 0xece88483
li t3, 0xd33ac6cd
li t4, 0x7e811b82
p.msu t2, t0, t1
p.mac  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x67c0a052
li t1, 0x71cc98f
li t3, 0x5fa2c6c8
li t4, 0x855e21d6
p.mulhhu t2, t0, t1
p.msu  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xe1b6f89b
li t1, 0xe40bc130
li t3, 0xa6827d7c
li t4, 0xccdce3bc
pv.dotusp.h t2, t0, t1
pv.sdotup.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotusp.h t2, t0, t1
pv.dotup.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xf0db7c4d
li t1, 0xf205e098
li t3, 0x53413ebe
li t4, 0x666e71de
pv.dotup.h t2, t0, t1
pv.sdotusp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.h t2, t0, t1
pv.dotusp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xc00059ef
li t1, 0xae65b215
li t3, 0x8c95683c
li t4, 0x6630f90a
p.msu t2, t0, t1
p.msu t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xe11dfcde
li t1, 0x177c021c
li t3, 0xc5f3b194
li t4, 0xbf05a533
p.msu t2, t0, t1
p.msu  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xf00d6e33
li t1, 0xcb984278
li t3, 0x6342e0e3
li t4, 0x5b0a202d
p.msu t2, t0, t1
p.mac t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xb0b073f0
li t1, 0xa1013808
li t3, 0xe5bd0e0
li t4, 0x6fab6488
p.msu  t2, t0, t1
p.msu t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x586ae363
li t1, 0xd0b73036
li t3, 0x87c7243e
li t4, 0x375bd32b
p.mac  t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mac  t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x9ccf8047
li t1, 0xc91e105b
li t3, 0x4c50355c
li t4, 0x7501fb87
pv.dotusp.b t2, t0, t1
p.mac t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotusp.b t2, t0, t1
p.mac t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x8f06482c
li t1, 0x63942c63
li t3, 0xdbd7cdd1
li t4, 0x4aadc5e
p.msu t2, t0, t1
p.msu t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x533404d9
li t1, 0xd98b6bfd
li t3, 0x795aceca
li t4, 0xcf9d1ff5
p.mac  t2, t0, t1
pv.sdotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mac  t2, t0, t1
pv.dotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x299a026c
li t1, 0xecc5b5fe
li t3, 0xbcad6765
li t4, 0x67ce8ffa
p.mac t2, t0, t1
pv.sdotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mac t2, t0, t1
pv.dotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x2418c7f1
li t1, 0xd70cba93
li t3, 0xd1d8fbce
li t4, 0xdd50e1ab
pv.dotup.h t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.h t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x120c63f8
li t1, 0xeb865d49
li t3, 0x68ec7de7
li t4, 0x6ea870d5
p.mulu t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mulu t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x90631fc
li t1, 0x75c32ea4
li t3, 0x34763ef3
li t4, 0xb754386a
pv.dotusp.h t2, t0, t1
pv.sdotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotusp.h t2, t0, t1
pv.dotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xaafea9db
li t1, 0x6ca99bf3
li t3, 0xc554e3fe
li t4, 0xb4397b67
p.mulhhs t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mulhhs t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xd578d4e8
li t1, 0xb657cdff
li t3, 0x40004000
li t4, 0x5a1dbdb3
p.mulhhs t2, t0, t1
pv.sdotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mulhhs t2, t0, t1
pv.dotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x5a6a6cb1
li t1, 0x7a440690
li t3, 0xbedb7083
li t4, 0xc3b9f88f
p.mulu t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mulu t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x2d353658
li t1, 0xbd220348
li t3, 0x5f6db841
li t4, 0xe1dcfc47
p.msu t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x264f5deb
li t1, 0xffff61c8
li t3, 0x2038945c
li t4, 0x9e59d875
pv.dotup.h t2, t0, t1
pv.sdotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.h t2, t0, t1
pv.dotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xd1f93419
li t1, 0x2f48e844
li t3, 0xcfc90129
li t4, 0x10cda536
pv.dotsp.h t2, t0, t1
pv.sdotup.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotsp.h t2, t0, t1
pv.dotup.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xe8fc4b18
li t1, 0x97a47422
li t3, 0x67f009b2
li t4, 0x881be9be
p.msu t2, t0, t1
p.msu  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xf470e474
li t1, 0xcbc008a4
li t3, 0x33036951
li t4, 0x440412cb
p.msu t2, t0, t1
p.msu  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xfa3f4a50
li t1, 0xa5e94cc5
li t3, 0x19e5b720
li t4, 0xa258991d
p.msu  t2, t0, t1
p.mac  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x5630ec04
li t1, 0xb8a31718
li t3, 0x8e37244b
li t4, 0x116a1854
p.mulhhs t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mulhhs t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x1bcdb0c5
li t1, 0xfd3febe0
li t3, 0x4895da59
li t4, 0xe602aa7c
p.muls t2, t0, t1
pv.sdotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.muls t2, t0, t1
pv.dotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x8def3400
li t1, 0x7e9fc1e7
li t3, 0xa48f3c3b
li t4, 0x73079010
pv.dotup.b t2, t0, t1
p.msu t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.b t2, t0, t1
p.msu t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xd5c6c7a
li t1, 0x16e606c9
li t3, 0xf8e487c6
li t4, 0xeb7a6564
p.muls t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.muls t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x86ae363d
li t1, 0xb730364
li t3, 0x7c7243e3
li t4, 0x75bd32b2
p.msu t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xc3571b1e
li t1, 0x85b981b2
li t3, 0x3e3921f1
li t4, 0xbade9959
pv.dotup.b t2, t0, t1
pv.sdotup.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.b t2, t0, t1
pv.dotup.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x61ab8d8f
li t1, 0x42dcc0d9
li t3, 0x1f1c90f8
li t4, 0xdd6f4cac
p.muls t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.muls t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x8924a6ea
li t1, 0x90bf1e25
li t3, 0xb05535e6
li t4, 0xc460ee72
pv.dotusp.h t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotusp.h t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xc48257e3
li t1, 0xc85f8f18
li t3, 0x58cd5408
li t4, 0xe0203e8a
p.msu  t2, t0, t1
p.mac  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xfc926142
li t1, 0x8af772f3
li t3, 0xfe7509a9
li t4, 0x7edc8485
pv.dotusp.b t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotusp.b t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xbbb6cb25
li t1, 0xeae253ae
li t3, 0xe7b7d899
li t4, 0x3d875618
p.msu  t2, t0, t1
pv.sdotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu  t2, t0, t1
pv.dotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xd4ffc378
li t1, 0x65ce37f2
li t3, 0x438ed9aa
li t4, 0x5aa3457e
p.msu  t2, t0, t1
pv.sdotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu  t2, t0, t1
pv.dotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x6a7fe1bc
li t1, 0x32e71bf9
li t3, 0xa1c76cd5
li t4, 0x2d51a2bf
pv.dotsp.b t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotsp.b t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x1e0dab1a
li t1, 0x44e649ec
li t3, 0x705b41c6
li t4, 0x29641f96
p.msu  t2, t0, t1
pv.sdotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu  t2, t0, t1
pv.dotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xf06d58d
li t1, 0x227324f6
li t3, 0xb82da0e3
li t4, 0x14b20fcb
p.mac t2, t0, t1
pv.sdotup.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mac t2, t0, t1
pv.dotup.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xea7cc2c
li t1, 0x1868c5e
li t3, 0xec43e597
li t4, 0x4e39e997
p.msu  t2, t0, t1
pv.sdotusp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu  t2, t0, t1
pv.dotusp.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x8e7740fc
li t1, 0x907c580a
li t3, 0x4674c72d
li t4, 0x637c1ab9
p.msu t2, t0, t1
pv.sdotup.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu t2, t0, t1
pv.dotup.b t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xc73ba768
li t1, 0x483e2c1f
li t3, 0x233b471a
li t4, 0x31b40070
p.mulhhs t2, t0, t1
p.msu t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x355cbb6a
li t1, 0xda500413
li t3, 0x10e40216
li t4, 0xce5ff46e
p.msu  t2, t0, t1
pv.sdotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu  t2, t0, t1
pv.dotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x938afb5f
li t1, 0xfd971c2c
li t3, 0x382734ed
li t4, 0xa34f1445
pv.dotup.h t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.h t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xb0387655
li t1, 0x5b9d240e
li t3, 0xab110bd8
li t4, 0x5708105
p.msu t2, t0, t1
p.mac  t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xd81c3b4a
li t1, 0x2dce920e
li t3, 0x55ee9afb
li t4, 0x232c1ce
p.msu t2, t0, t1
p.msu t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x7f23a830
li t1, 0xbbccbaa4
li t3, 0xe537009a
li t4, 0x44ced550
p.mac t2, t0, t1
pv.sdotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mac t2, t0, t1
pv.dotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x36b572f2
li t1, 0xcd594377
li t3, 0x42ceb5ab
li t4, 0xe60784da
p.msu  t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.msu  t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xc93f0fc9
li t1, 0xfb09dfcf
li t3, 0xc8993799
li t4, 0x9bb1960f
p.mac t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mac t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x6dbb210e
li t1, 0x6d3bf1c2
li t3, 0xd419ae2a
li t4, 0x9b82575
pv.dotup.h t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.h t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x36dd9087
li t1, 0x369df8e1
li t3, 0x6a0cd715
li t4, 0x4dc12ba
p.mulhhu t2, t0, t1
pv.sdotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mulhhu t2, t0, t1
pv.dotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x924a6ea9
li t1, 0xbf1e255
li t3, 0x5535e6c
li t4, 0x460ee72f
p.mulhhu t2, t0, t1
pv.sdotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mulhhu t2, t0, t1
pv.dotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x24929baa
li t1, 0x42fc7895
li t3, 0xc154d79b
li t4, 0x1183b9cb
pv.dotup.h t2, t0, t1
pv.sdotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.h t2, t0, t1
pv.dotup.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x12494dd5
li t1, 0x217e3c4a
li t3, 0x60aa6bcd
li t4, 0x88c1dce5
p.muls t2, t0, t1
pv.sdotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.muls t2, t0, t1
pv.dotusp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0xd7132aad
li t1, 0xb60e28a9
li t3, 0x4dd40b08
li t4, 0x7f0cebe6
pv.dotup.b t2, t0, t1
pv.sdotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
pv.sdotup.b t2, t0, t1
pv.dotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x6b899556
li t1, 0xdb071454
li t3, 0xa6ea0584
li t4, 0x3f8675f3
p.mulhhs t2, t0, t1
pv.sdotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
p.mulhhs t2, t0, t1
pv.dotsp.h t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
li t0, 0x242f47f9
li t1, 0xdbea545d
li t3, 0xcc964cf8
li t4, 0xd8b96a52
p.msu  t2, t0, t1
p.msu t5, t3, t4
sw t2, 4(sp)
sw t5, 4(sp)
