li t0, 0x00000000
li t1, 0x00000ff0
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000000
li t1, 0x00000000
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x0f000f00
li t1, 0x00000000
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0xffffffff
li t1, 0xffffffff
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000001
li t1, 0x00000001
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t4, t0, t1
remu t5, t0, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x00000001
li t1, 0xffffffff
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0xffffffff
li t1, 0x00000001
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000001
li t1, 0x00000010
li t0, 0x00000001
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000001
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000001
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000001
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000002
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000003
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000006
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x0000000a
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x0000000c
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000015
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000027
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000049
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x0000007e
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x000000f0
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x000001a3
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000291
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000307
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x0000049f
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x000007f5
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000001
li t1, 0x0000ffff
li t0, 0x00018879
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x0002c774
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00053d1f
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x0007fb69
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x000a4fee
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x000c36f2
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00108805
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000001
li t1, 0xf0f0f0f0
li t0, 0x00000002
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000002
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000003
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000006
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x0000000b
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000016
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0x00000023
div t4, t1, t0
divu t5, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
rem t2, t0, t1
remu t3, t0, t1
sw t2, 4(sp)
sw t3, 4(sp)
li t0, 0xc8f9dae0
li t1, 0x6eba63bc
div t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
div t4, t1, t0
sw t4, 4(sp)
li t0, 0xab6c72a2
li t1, 0xaef32a1a
div t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
div t4, t1, t0
sw t4, 4(sp)
li t0, 0xed0028a4
li t1, 0xc067628a
div t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
divu t4, t1, t0
sw t4, 4(sp)
li t0, 0x4b295576
li t1, 0xfe1796f7
divu t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
divu t4, t1, t0
sw t4, 4(sp)
li t0, 0x1f6f54d9
li t1, 0x51a21744
divu t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
divu t4, t1, t0
sw t4, 4(sp)
li t0, 0x00009cca
li t1, 0x0000a0cb
div t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
div t4, t1, t0
sw t4, 4(sp)
li t0, 0x00004fe6
li t1, 0x00007ef1
div t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
div t4, t1, t0
sw t4, 4(sp)
li t0, 0x0000d33a
li t1, 0x0000d4b8
div t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
divu t4, t1, t0
sw t4, 4(sp)
li t0, 0x00001e56
li t1, 0x0000d70e
divu t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
divu t4, t1, t0
sw t4, 4(sp)
li t0, 0x0000a88a
li t1, 0x0000df3b
divu t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
divu t4, t1, t0
sw t4, 4(sp)
li t0, 0x064856fb
li t1, 0x2822481b
div t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
div t4, t1, t0
sw t4, 4(sp)
li t0, 0x4829c7de
li t1, 0xe8f61062
div t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
div t4, t1, t0
sw t4, 4(sp)
li t0, 0x42e40a59
li t1, 0x37da8ef6
div t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
divu t4, t1, t0
sw t4, 4(sp)
li t0, 0x87e1b132
li t1, 0x15b15b5f
divu t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
divu t4, t1, t0
sw t4, 4(sp)
li t0, 0x13440846
li t1, 0xd65e2ea0
divu t4, t1, t0
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
divu t4, t1, t0
sw t4, 4(sp)
li t0, 0xc7d38a9b
li t1, 0x61f0b9c4
rem t4, t0, t1
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
rem t4, t0, t1
sw t4, 4(sp)
li t0, 0xc5754a54
li t1, 0x00ed789d
rem t4, t0, t1
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
rem t4, t0, t1
sw t4, 4(sp)
li t0, 0x459e7156
li t1, 0xc613ac0b
rem t4, t0, t1
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
remu t4, t0, t1
sw t4, 4(sp)
li t0, 0xf64ff5d2
li t1, 0x72544d05
remu t4, t0, t1
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
remu t4, t0, t1
sw t4, 4(sp)
li t0, 0x61a9b3ac
li t1, 0x4f303d54
remu t4, t0, t1
sw t4, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
remu t4, t0, t1
sw t4, 4(sp)
