li t2, 0x00000000
li t0, 0x4200cd35
li t1, 0xfa17864e
p.mac t2, t1, t0
sw t2, 4(sp)
li t0, 0x6008703f
li t1, 0xf1af43bf
p.mac t2, t1, t0
sw t2, 4(sp)
li t0, 0xac1c319f
li t1, 0xe8130ce3
p.mac t2, t1, t0
sw t2, 4(sp)
li t0, 0x30503008
li t1, 0x9e887302
p.mac t2, t1, t0
sw t2, 4(sp)
li t0, 0x92403077
li t1, 0xf0a353c1
p.mac t2, t1, t0
sw t2, 4(sp)
li t0, 0x659c840c
li t1, 0x2edffe83
p.mac t2, t1, t0
sw t2, 4(sp)
li t0, 0x8d0580e3
li t1, 0xe7e0e0f3
p.msu t2, t1, t0
sw t2, 4(sp)
li t0, 0xc2bcd63f
li t1, 0x1c17128f
p.msu t2, t1, t0
sw t2, 4(sp)
li t0, 0x900702ce
li t1, 0x10b15701
p.msu t2, t1, t0
sw t2, 4(sp)
li t0, 0x843e00c0
li t1, 0xc7961d0
p.msu t2, t1, t0
sw t2, 4(sp)
li t0, 0xc6902a67
li t1, 0xc147980
p.msu t2, t1, t0
sw t2, 4(sp)
li t0, 0xcc81fc83
li t1, 0xf9842166
p.macsN t2, t1, t0, 0x0c
sw t2, 4(sp)
li t0, 0x20f00520
li t1, 0x3038016a
p.macsN t2, t1, t0, 0x0c
sw t2, 4(sp)
li t0, 0x91eb2c85
li t1, 0xd347d8f7
p.macsN t2, t1, t0, 0x13
sw t2, 4(sp)
li t0, 0x9479c07f
li t1, 0xd5103e46
p.macsN t2, t1, t0, 0x00
sw t2, 4(sp)
li t0, 0x5008c6c4
li t1, 0x1fd14c2b
p.macsN t2, t1, t0, 0x1f
sw t2, 4(sp)
li t0, 0x9a085623
li t1, 0xfc340177
p.machhsN t2, t1, t0, 0x01
sw t2, 4(sp)
li t0, 0xc0cb2c10
li t1, 0xe1ef0050
p.machhsN t2, t1, t0, 0x1e
sw t2, 4(sp)
li t0, 0xca88002c
li t1, 0x2f36a8e7
p.machhsN t2, t1, t0, 0x12
sw t2, 4(sp)
li t0, 0x68000020
li t1, 0x15201e61
p.machhsN t2, t1, t0, 0x0d
sw t2, 4(sp)
li t0, 0xe029a008
li t1, 0x7000400
p.machhsN t2, t1, t0, 0x1a
sw t2, 4(sp)
li t0, 0xa10ffc9f
li t1, 0xce88ef86
p.macsRN t2, t1, t0, 0x05
sw t2, 4(sp)
li t0, 0xb34414c1
li t1, 0x71c71f10
p.macsRN t2, t1, t0, 0x03
sw t2, 4(sp)
li t0, 0xa01f0243
li t1, 0xdc1803c3
p.macsRN t2, t1, t0, 0x1c
sw t2, 4(sp)
li t0, 0x90dd0070
li t1, 0xcb86e823
p.macsRN t2, t1, t0, 0x15
sw t2, 4(sp)
li t0, 0xb2397d00
li t1, 0x12884b05
p.macsRN t2, t1, t0, 0x0a
sw t2, 4(sp)
li t0, 0x50fefc02
li t1, 0x658b6e7e
p.machhsRN t2, t1, t0, 0x15
sw t2, 4(sp)
li t0, 0x400e74bc
li t1, 0x2df0e38d
p.machhsRN t2, t1, t0, 0x0a
sw t2, 4(sp)
li t0, 0x604e86bd
li t1, 0x7fc1130d
p.machhsRN t2, t1, t0, 0x01
sw t2, 4(sp)
li t0, 0xc130fce1
li t1, 0xf1c75e9c
p.machhsRN t2, t1, t0, 0x1e
sw t2, 4(sp)
li t0, 0x291f8111
li t1, 0xf945c018
p.machhsRN t2, t1, t0, 0x1e
sw t2, 4(sp)
li t0, 0x6bd100f0
li t1, 0x2bc2639
p.machhsRN t2, t1, t0, 0x01
sw t2, 4(sp)
li t0, 0xd8034604
li t1, 0x3f7ce0cd
p.macuN t2, t1, t0, 0x13
sw t2, 4(sp)
li t0, 0xdc72f3c5
li t1, 0xf4638b4e
p.macuN t2, t1, t0, 0x0c
sw t2, 4(sp)
li t0, 0xb298f303
li t1, 0x87367910
p.macuN t2, t1, t0, 0x03
sw t2, 4(sp)
li t0, 0x88222060
li t1, 0x805b0006
p.macuN t2, t1, t0, 0x1c
sw t2, 4(sp)
li t0, 0x5940f45f
li t1, 0x4995c144
p.macuN t2, t1, t0, 0x1d
sw t2, 4(sp)
li t0, 0xca1170f8
li t1, 0x787dc602
p.machhuN t2, t1, t0, 0x02
sw t2, 4(sp)
li t0, 0x3fbdf4fc
li t1, 0xf22a000b
p.machhuN t2, t1, t0, 0x1f
sw t2, 4(sp)
li t0, 0xf01237dd
li t1, 0x3c2d198a
p.machhuN t2, t1, t0, 0x00
sw t2, 4(sp)
li t0, 0x8007e080
li t1, 0x8619e80
p.machhuN t2, t1, t0, 0x11
sw t2, 4(sp)
li t0, 0x78b0651b
li t1, 0x2c98664e
p.machhuN t2, t1, t0, 0x0e
sw t2, 4(sp)
li t0, 0xc41008d2
li t1, 0xc7c3e3cf
p.macuRN t2, t1, t0, 0x05
sw t2, 4(sp)
li t0, 0x341c38db
li t1, 0x867c70e4
p.macuRN t2, t1, t0, 0x1a
sw t2, 4(sp)
li t0, 0x37cb8607
li t1, 0x8f859794
p.macuRN t2, t1, t0, 0x18
sw t2, 4(sp)
li t0, 0x72ec0081
li t1, 0x99cf5a07
p.macuRN t2, t1, t0, 0x07
sw t2, 4(sp)
li t0, 0xca327fd4
li t1, 0x14064463
p.macuRN t2, t1, t0, 0x06
sw t2, 4(sp)
li t0, 0x40842eff
li t1, 0xa7bd859a
p.machhuRN t2, t1, t0, 0x19
sw t2, 4(sp)
li t0, 0xb040a18b
li t1, 0x13864933
p.machhuRN t2, t1, t0, 0x08
sw t2, 4(sp)
li t0, 0x50003cee
li t1, 0xc63588cf
p.machhuRN t2, t1, t0, 0x17
sw t2, 4(sp)
li t0, 0xd811de04
li t1, 0x191fde0
p.machhuRN t2, t1, t0, 0x15
sw t2, 4(sp)
li t0, 0xa84b780a
li t1, 0x1eac81e7
p.machhuRN t2, t1, t0, 0x0a
sw t2, 4(sp)
li t0, 0x79111e7a
li t1, 0x79111e7a
mul t2, t1, t0
sw t2, 4(sp)
li t0, 0x86ee1e7a
li t1, 0x7911e185
mul t2, t1, t0
sw t2, 4(sp)
li t0, 0x86ee1e7a
li t1, 0x7911e185
mul t2, t1, t0
sw t2, 4(sp)
li t0, 0x86ee1e7a
li t1, 0x7911e185
mul t2, t1, t0
sw t2, 4(sp)
li t0, 0x86ee1e7a
li t1, 0x7911e185
mul t2, t1, t0
sw t2, 4(sp)
li t0, 0x86ee1e7a
li t1, 0x7911e185
mul t2, t1, t0
sw t2, 4(sp)
li t0, 0x86ee1e7a
li t1, 0x7911e185
mul t2, t1, t0
sw t2, 4(sp)
li t0, 0x86ee1e7a
li t1, 0x7911e185
mul t2, t1, t0
sw t2, 4(sp)
li t0, 0x86ee1e7a
li t1, 0x7911e185
mul t2, t1, t0
sw t2, 4(sp)
li t0, 0x86ee1e7a
li t1, 0x7911e185
mul t2, t1, t0
sw t2, 4(sp)
mulh t2, t1, t0
sw t2, 4(sp)
li t0, 0xad37aec8
li t1, 0xad37aec8
mulh t2, t1, t0
sw t2, 4(sp)
li t0, 0x52c8aec8
li t1, 0xad375137
mulh t2, t1, t0
sw t2, 4(sp)
li t0, 0x52c8aec8
li t1, 0xad375137
mulh t2, t1, t0
sw t2, 4(sp)
li t0, 0x52c8aec8
li t1, 0xad375137
mulh t2, t1, t0
sw t2, 4(sp)
li t0, 0x52c8aec8
li t1, 0xad375137
mulh t2, t1, t0
sw t2, 4(sp)
li t0, 0x52c8aec8
li t1, 0xad375137
mulh t2, t1, t0
sw t2, 4(sp)
li t0, 0x52c8aec8
li t1, 0xad375137
mulh t2, t1, t0
sw t2, 4(sp)
li t0, 0x52c8aec8
li t1, 0xad375137
mulh t2, t1, t0
sw t2, 4(sp)
li t0, 0x52c8aec8
li t1, 0xad375137
mulh t2, t1, t0
sw t2, 4(sp)
li t0, 0x52c8aec8
li t1, 0xad375137
mulhsu t2, t1, t0
sw t2, 4(sp)
mulhsu t2, t1, t0
sw t2, 4(sp)
li t0, 0xe4bd92dc
li t1, 0xe4bd92dc
mulhsu t2, t1, t0
sw t2, 4(sp)
li t0, 0x1b4292dc
li t1, 0xe4bd6d23
mulhsu t2, t1, t0
sw t2, 4(sp)
li t0, 0x1b4292dc
li t1, 0xe4bd6d23
mulhsu t2, t1, t0
sw t2, 4(sp)
li t0, 0x1b4292dc
li t1, 0xe4bd6d23
mulhsu t2, t1, t0
sw t2, 4(sp)
li t0, 0x1b4292dc
li t1, 0xe4bd6d23
mulhsu t2, t1, t0
sw t2, 4(sp)
li t0, 0x1b4292dc
li t1, 0xe4bd6d23
mulhsu t2, t1, t0
sw t2, 4(sp)
li t0, 0x1b4292dc
li t1, 0xe4bd6d23
mulhsu t2, t1, t0
sw t2, 4(sp)
li t0, 0x1b4292dc
li t1, 0xe4bd6d23
mulhsu t2, t1, t0
sw t2, 4(sp)
li t0, 0x1b4292dc
li t1, 0xe4bd6d23
mulhu t2, t1, t0
sw t2, 4(sp)
li t0, 0x1b4292dc
li t1, 0xe4bd6d23
mulhu t2, t1, t0
sw t2, 4(sp)
mulhu t2, t1, t0
sw t2, 4(sp)
li t0, 0x807dfbb5
li t1, 0x807dfbb5
mulhu t2, t1, t0
sw t2, 4(sp)
li t0, 0x7f82fbb5
li t1, 0x807d044a
mulhu t2, t1, t0
sw t2, 4(sp)
li t0, 0x7f82fbb5
li t1, 0x807d044a
mulhu t2, t1, t0
sw t2, 4(sp)
li t0, 0x7f82fbb5
li t1, 0x807d044a
mulhu t2, t1, t0
sw t2, 4(sp)
li t0, 0x7f82fbb5
li t1, 0x807d044a
mulhu t2, t1, t0
sw t2, 4(sp)
li t0, 0x7f82fbb5
li t1, 0x807d044a
mulhu t2, t1, t0
sw t2, 4(sp)
li t0, 0x7f82fbb5
li t1, 0x807d044a
mulhu t2, t1, t0
sw t2, 4(sp)
/*
li t0, 0x7f82fbb5
li t1, 0x807d044a
div t2, t1, t0
sw t2, 4(sp)
li t0, 0x7f82fbb5
li t1, 0x807d044a
div t2, t1, t0
sw t2, 4(sp)
li t0, 0x7f82fbb5
li t1, 0x807d044a
div t2, t1, t0
sw t2, 4(sp)
div t2, t1, t0
sw t2, 4(sp)
li t0, 0x8cc8556b
li t1, 0x8cc8556b
div t2, t1, t0
sw t2, 4(sp)
li t0, 0x7337556b
li t1, 0x8cc8aa94
div t2, t1, t0
sw t2, 4(sp)
li t0, 0x7337556b
li t1, 0x8cc8aa94
div t2, t1, t0
sw t2, 4(sp)
li t0, 0x7337556b
li t1, 0x8cc8aa94
div t2, t1, t0
sw t2, 4(sp)
li t0, 0x7337556b
li t1, 0x8cc8aa94
div t2, t1, t0
sw t2, 4(sp)
li t0, 0x7337556b
li t1, 0x8cc8aa94
div t2, t1, t0
sw t2, 4(sp)
li t0, 0x7337556b
li t1, 0x8cc8aa94
divu t2, t1, t0
sw t2, 4(sp)
li t0, 0x7337556b
li t1, 0x8cc8aa94
divu t2, t1, t0
sw t2, 4(sp)
li t0, 0x7337556b
li t1, 0x8cc8aa94
divu t2, t1, t0
sw t2, 4(sp)
li t0, 0x7337556b
li t1, 0x8cc8aa94
divu t2, t1, t0
sw t2, 4(sp)
divu t2, t1, t0
sw t2, 4(sp)
li t0, 0x4e8fd178
li t1, 0x4e8fd178
divu t2, t1, t0
sw t2, 4(sp)
li t0, 0xb170d178
li t1, 0x4e8f2e87
divu t2, t1, t0
sw t2, 4(sp)
li t0, 0xb170d178
li t1, 0x4e8f2e87
divu t2, t1, t0
sw t2, 4(sp)
li t0, 0xb170d178
li t1, 0x4e8f2e87
divu t2, t1, t0
sw t2, 4(sp)
li t0, 0xb170d178
li t1, 0x4e8f2e87
divu t2, t1, t0
sw t2, 4(sp)
li t0, 0xb170d178
li t1, 0x4e8f2e87
rem t2, t1, t0
sw t2, 4(sp)
li t0, 0xb170d178
li t1, 0x4e8f2e87
rem t2, t1, t0
sw t2, 4(sp)
li t0, 0xb170d178
li t1, 0x4e8f2e87
rem t2, t1, t0
sw t2, 4(sp)
li t0, 0xb170d178
li t1, 0x4e8f2e87
rem t2, t1, t0
sw t2, 4(sp)
li t0, 0xb170d178
li t1, 0x4e8f2e87
rem t2, t1, t0
sw t2, 4(sp)
rem t2, t1, t0
sw t2, 4(sp)
li t0, 0x54dcd140
li t1, 0x54dcd140
rem t2, t1, t0
sw t2, 4(sp)
li t0, 0xab23d140
li t1, 0x54dc2ebf
rem t2, t1, t0
sw t2, 4(sp)
li t0, 0xab23d140
li t1, 0x54dc2ebf
rem t2, t1, t0
sw t2, 4(sp)
li t0, 0xab23d140
li t1, 0x54dc2ebf
rem t2, t1, t0
sw t2, 4(sp)
li t0, 0xab23d140
li t1, 0x54dc2ebf
remu t2, t1, t0
sw t2, 4(sp)
li t0, 0xab23d140
li t1, 0x54dc2ebf
remu t2, t1, t0
sw t2, 4(sp)
li t0, 0xab23d140
li t1, 0x54dc2ebf
remu t2, t1, t0
sw t2, 4(sp)
li t0, 0xab23d140
li t1, 0x54dc2ebf
remu t2, t1, t0
sw t2, 4(sp)
li t0, 0xab23d140
li t1, 0x54dc2ebf
remu t2, t1, t0
sw t2, 4(sp)
li t0, 0xab23d140
li t1, 0x54dc2ebf
remu t2, t1, t0
sw t2, 4(sp)
remu t2, t1, t0
sw t2, 4(sp)
li t0, 0xf9f3a550
li t1, 0xf9f3a550
remu t2, t1, t0
sw t2, 4(sp)
li t0, 0x060ca550
li t1, 0xf9f35aaf
remu t2, t1, t0
sw t2, 4(sp)
li t0, 0x060ca550
li t1, 0xf9f35aaf
remu t2, t1, t0
sw t2, 4(sp)*/
li t0, 0xbd6f676e
li t1, 0xe8ac275f
p.mulhhs t2, t1, t0
sw t2, 4(sp)
li t0, 0x84773ec3
li t1, 0x8eee66ed
p.mulhhs t2, t1, t0
sw t2, 4(sp)
li t0, 0x2f057966
li t1, 0xc340b896
p.mulhhs t2, t1, t0
sw t2, 4(sp)
li t0, 0x89724c38
li t1, 0xc120f620
p.mulhhs t2, t1, t0
sw t2, 4(sp)
li t0, 0x75e48ebe
li t1, 0xdd26473b
p.mulhhs t2, t1, t0
sw t2, 4(sp)
li t0, 0x53ccbc5f
li t1, 0xbecc7418
p.muls t2, t1, t0
sw t2, 4(sp)
li t0, 0x3630f242
li t1, 0xe3bf3c4b
p.muls t2, t1, t0
sw t2, 4(sp)
li t0, 0x5cf7064e
li t1, 0xf65a7c34
p.muls t2, t1, t0
sw t2, 4(sp)
li t0, 0xfa538a07
li t1, 0xdc299a4c
p.muls t2, t1, t0
sw t2, 4(sp)
li t0, 0x19174476
li t1, 0x66dafad1
p.muls t2, t1, t0
sw t2, 4(sp)
li t0, 0xfc88f064
li t1, 0x1f3d8d1a
p.mulhhsN t2, t1, t0, 0x04
sw t2, 4(sp)
li t0, 0xccf75bda
li t1, 0x1677a6d5
p.mulhhsN t2, t1, t0, 0x1b
sw t2, 4(sp)
li t0, 0x1e5a498f
li t1, 0x14da23c5
p.mulhhsN t2, t1, t0, 0x09
sw t2, 4(sp)
li t0, 0x4c045d83
li t1, 0x4d529f2c
p.mulhhsN t2, t1, t0, 0x16
sw t2, 4(sp)
li t0, 0x19edc3fd
li t1, 0x05c4f916
p.mulhhsN t2, t1, t0, 0x16
sw t2, 4(sp)
li t0, 0x859c079d
li t1, 0x7199602b
p.mulsN t2, t1, t0, 0x09
sw t2, 4(sp)
li t0, 0x411067df
li t1, 0x13e8df93
p.mulsN t2, t1, t0, 0x09
sw t2, 4(sp)
li t0, 0xddc98b96
li t1, 0x1b11138d
p.mulsN t2, t1, t0, 0x16
sw t2, 4(sp)
li t0, 0xe95eb18b
li t1, 0x346d36ad
p.mulsN t2, t1, t0, 0x0b
sw t2, 4(sp)
li t0, 0x463515b2
li t1, 0x629385a4
p.mulsN t2, t1, t0, 0x14
sw t2, 4(sp)
li t0, 0x434781c9
li t1, 0x03960c1e
p.mulhhu t2, t1, t0
sw t2, 4(sp)
li t0, 0x0120d389
li t1, 0x0ed6abc5
p.mulhhu t2, t1, t0
sw t2, 4(sp)
li t0, 0x322f31c0
li t1, 0xdea2e998
p.mulhhu t2, t1, t0
sw t2, 4(sp)
li t0, 0x5260edbc
li t1, 0x4dad6c72
p.mulhhu t2, t1, t0
sw t2, 4(sp)
li t0, 0xfac9af23
li t1, 0x8c46b594
p.mulhhu t2, t1, t0
sw t2, 4(sp)
li t0, 0xa975c67e
li t1, 0xf7d59a85
p.mulu t2, t1, t0
sw t2, 4(sp)
li t0, 0x7993a33b
li t1, 0x27aa7eb7
p.mulu t2, t1, t0
sw t2, 4(sp)
li t0, 0xb641c8ec
li t1, 0xecc1984b
p.mulu t2, t1, t0
sw t2, 4(sp)
li t0, 0x052161c5
li t1, 0xcb5dba65
p.mulu t2, t1, t0
sw t2, 4(sp)
li t0, 0xfaf188af
li t1, 0x2d168a3b
p.mulu t2, t1, t0
sw t2, 4(sp)
li t0, 0x7f4074fc
li t1, 0x6bb773fe
p.mulhhuN t2, t1, t0, 0x09
sw t2, 4(sp)
li t0, 0xc3afd192
li t1, 0xd33379c2
p.mulhhuN t2, t1, t0, 0x16
sw t2, 4(sp)
li t0, 0x6b1b3073
li t1, 0xa9a4ff4b
p.mulhhuN t2, t1, t0, 0x06
sw t2, 4(sp)
li t0, 0xdaebf3a1
li t1, 0xfbef5828
p.mulhhuN t2, t1, t0, 0x19
sw t2, 4(sp)
li t0, 0x5d9f78ca
li t1, 0xfdca757f
p.mulhhuN t2, t1, t0, 0x12
sw t2, 4(sp)
li t0, 0x004b75fb
li t1, 0xcbbb8010
p.muluN t2, t1, t0, 0x0d
sw t2, 4(sp)
li t0, 0x850c373e
li t1, 0x505c3fd8
p.muluN t2, t1, t0, 0x18
sw t2, 4(sp)
li t0, 0x5f0bd9c7
li t1, 0x8df0f37a
p.muluN t2, t1, t0, 0x07
sw t2, 4(sp)
li t0, 0x3089e624
li t1, 0x32875aa5
p.muluN t2, t1, t0, 0x17
sw t2, 4(sp)
li t0, 0x934e10aa
li t1, 0xa29a87c9
p.muluN t2, t1, t0, 0x08
sw t2, 4(sp)
li t0, 0x910ae8d0
li t1, 0xb59f26dd
p.mulhhuRN t2, t1, t0, 0x13
sw t2, 4(sp)
li t0, 0xcb895029
li t1, 0xd485f876
p.mulhhuRN t2, t1, t0, 0x0c
sw t2, 4(sp)
li t0, 0xa734085c
li t1, 0xb950e759
p.mulhhuRN t2, t1, t0, 0x1e
sw t2, 4(sp)
li t0, 0x12bd0c90
li t1, 0x32e1f32b
p.mulhhuRN t2, t1, t0, 0x01
sw t2, 4(sp)
li t0, 0x930b3d76
li t1, 0x273db13c
p.mulhhuRN t2, t1, t0, 0x05
sw t2, 4(sp)
li t0, 0x88215682
li t1, 0xf69a22b2
p.muluRN t2, t1, t0, 0x1a
sw t2, 4(sp)
li t0, 0xc2953733
li t1, 0x01fbd3ed
p.muluRN t2, t1, t0, 0x17
sw t2, 4(sp)
li t0, 0x388b02d8
li t1, 0xc6765a29
p.muluRN t2, t1, t0, 0x08
sw t2, 4(sp)
li t0, 0xc4895d17
li t1, 0x971c8dda
p.muluRN t2, t1, t0, 0x1f
sw t2, 4(sp)
li t0, 0x08376598
li t1, 0x74793dda
p.muluRN t2, t1, t0, 0x00
sw t2, 4(sp)
li t0, 0xc07f548d
li t1, 0x4ce874d2
p.mulhhsRN t2, t1, t0, 0x0a
sw t2, 4(sp)
li t0, 0xc399e21f
li t1, 0x7b84e5d8
p.mulhhsRN t2, t1, t0, 0x15
sw t2, 4(sp)
li t0, 0x90fa7a95
li t1, 0xdfef7f6f
p.mulhhsRN t2, t1, t0, 0x1f
sw t2, 4(sp)
li t0, 0x0ab530ef
li t1, 0x46707f5c
p.mulhhsRN t2, t1, t0, 0x00
sw t2, 4(sp)
li t0, 0x11509752
li t1, 0xc56e1643
p.mulhhsRN t2, t1, t0, 0x1f
sw t2, 4(sp)
li t0, 0xb776f2bc
li t1, 0x8ca2a70c
p.mulsRN t2, t1, t0, 0x00
sw t2, 4(sp)
li t0, 0x8b9ec7da
li t1, 0xe978f07b
p.mulsRN t2, t1, t0, 0x1d
sw t2, 4(sp)
li t0, 0x58c85e12
li t1, 0x47cbd6f2
p.mulsRN t2, t1, t0, 0x02
sw t2, 4(sp)
li t0, 0x3553b62f
li t1, 0x9cf3cdec
p.mulsRN t2, t1, t0, 0x1f
sw t2, 4(sp)
li t0, 0xace7c278
li t1, 0xaf51af78
p.mulsRN t2, t1, t0, 0x00
sw t2, 4(sp)
li t0, 0xd84e829a
li t1, 0x87913ba1
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.sc.h t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.sc.h t2, t1, t0
sw t2, 4(sp)
li t0, 0x40b1c94f
li t1, 0x92a5463d
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.sc.h t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.sc.h t2, t1, t0
sw t2, 4(sp)
li t0, 0x2a83b346
li t1, 0x05802d8d
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.sc.h t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.sci.h t2, t1, 0x04
sw t2, 4(sp)
li t0, 0xb0c513e0
li t1, 0xeb83280e
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.sci.h t2, t1, 0x10
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.sci.h t2, t1, 0x0f
sw t2, 4(sp)
li t0, 0x935b7f6f
li t1, 0x7a5e5014
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.sci.h t2, t1, 0x0d
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.sci.h t2, t1, 0x12
sw t2, 4(sp)
li t0, 0xc0eb928b
li t1, 0x69c8c1c8
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.b t2, t1, t0
sw t2, 4(sp)
li t0, 0xde3daa3d
li t1, 0x16da0494
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x365b8e5e
li t1, 0x7b6d3f09
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0xf92a1e55
li t1, 0xb8904e03
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.sc.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x16195fdf
li t1, 0xd3b283fc
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.sc.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x1837e615
li t1, 0x7815224c
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.sci.b t2, t1, 0x00
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.sci.b t2, t1, 0x1f
sw t2, 4(sp)
li t0, 0xb24f7ffd
li t1, 0xbc2bd428
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.sci.b t2, t1, 0x08
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotup.sci.b t2, t1, 0x17
sw t2, 4(sp)
li t0, 0x8f6b7d4a
li t1, 0x6f995e18
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotup.sci.b t2, t1, 0x16
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.h t2, t1, t0
sw t2, 4(sp)
li t0, 0xd1f6be80
li t1, 0x88eea1ff
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.h t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.h t2, t1, t0
sw t2, 4(sp)
li t0, 0x807f6168
li t1, 0x650e0432
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.h t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.h t2, t1, t0
sw t2, 4(sp)
li t0, 0xc34b68f9
li t1, 0x30bd0647
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.sc.h t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.sc.h t2, t1, t0
sw t2, 4(sp)
li t0, 0xf7c8745c
li t1, 0x8d413900
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.sc.h t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.sc.h t2, t1, t0
sw t2, 4(sp)
li t0, 0xc6d0944d
li t1, 0xe15f8029
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.sc.h t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.sci.h t2, t1, 0x09
sw t2, 4(sp)
li t0, 0x1e3cb715
li t1, 0x9ec2541c
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.sci.h t2, t1, 0x1a
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.sci.h t2, t1, 0x05
sw t2, 4(sp)
li t0, 0xfaeb81bf
li t1, 0xa1bd0c63
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.sci.h t2, t1, 0x15
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.sci.h t2, t1, 0x0a
sw t2, 4(sp)
li t0, 0x21e5483c
li t1, 0xb45f0c9f
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.b t2, t1, t0
sw t2, 4(sp)
li t0, 0xf242ada4
li t1, 0xcd2c3cc8
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.b t2, t1, t0
sw t2, 4(sp)
li t0, 0xd9cc98fd
li t1, 0x91d08cc6
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x4bc4da49
li t1, 0x65cd7af5
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.sc.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x7461f7fd
li t1, 0x67444da8
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.sc.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0xafd7dcd5
li t1, 0x0a350809
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.sci.b t2, t1, 0x1e
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.sci.b t2, t1, 0x01
sw t2, 4(sp)
li t0, 0xbe53c196
li t1, 0x7a29e92a
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.sci.b t2, t1, 0x19
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotusp.sci.b t2, t1, 0x06
sw t2, 4(sp)
li t0, 0x21ef736e
li t1, 0x83314e52
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotusp.sci.b t2, t1, 0x0b
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.h t2, t1, t0
sw t2, 4(sp)
li t0, 0x353138e1
li t1, 0x9ea3445e
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.h t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.h t2, t1, t0
sw t2, 4(sp)
li t0, 0xa4094b8f
li t1, 0xa1bdd25d
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.h t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.h t2, t1, t0
sw t2, 4(sp)
li t0, 0xa5a2931d
li t1, 0x25e19c9a
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.sci.h t2, t1, 0x13
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.sci.h t2, t1, 0x0c
sw t2, 4(sp)
li t0, 0xc912c3fc
li t1, 0x1578a334
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.sci.h t2, t1, 0x0e
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.sci.h t2, t1, 0x11
sw t2, 4(sp)
li t0, 0x59cc0455
li t1, 0x26adedce
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.sci.h t2, t1, 0x14
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.b t2, t1, t0
sw t2, 4(sp)
li t0, 0xb38ec3fe
li t1, 0x5b766182
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x7b03fe8f
li t1, 0x4d101bd1
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x137db3e1
li t1, 0xdc5bf981
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.sc.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0x0c1d244d
li t1, 0x64f0a66d
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.sc.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.sc.b t2, t1, t0
sw t2, 4(sp)
li t0, 0xfaa04d5c
li t1, 0x9356fab0
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.sc.b t2, t1, t0
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.sci.b t2, t1, 0x01
sw t2, 4(sp)
li t0, 0x31cd83d5
li t1, 0x515bbac0
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.sci.b t2, t1, 0x11
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.sci.b t2, t1, 0x0e
sw t2, 4(sp)
li t0, 0xa383d6fa
li t1, 0x271bda8c
addi t0, t0, 0x1
addi t1, t1, 0x1
pv.dotsp.sci.b t2, t1, 0x08
sw t2, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
pv.dotsp.sci.b t2, t1, 0x17
sw t2, 4(sp)
