li t0, 0x18181818
li t1, 0x81818181
add t4, t1, t0
sub t4, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xc3c3c3c3
li t1, 0x3c3c3c3c
add t4, t1, t0
sub t4, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xf0f0f0f0
li t1, 0x0f0f0f0f
add t4, t1, t0
sub t4, t1, t0
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xddc5316c
li t1, 0x7cb6b4ca
li t2, 0x4dedb29f
li t3, 0xd8e61ee6
add t4, t1, t0
add t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
add t4, t1, t0
add t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x9ab8174d
li t1, 0x3517294d
li t2, 0x6d135183
li t3, 0x787dd3b0
sub t4, t1, t0
sub t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
sub t4, t1, t0
sub t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x6e415e9f
li t1, 0x107e597c
li t2, 0xa4b06732
li t3, 0x33f39a4f
xor t4, t1, t0
xor t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
xor t4, t1, t0
xor t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x08722cec
li t1, 0x2a29408f
li t2, 0xff5414ba
li t3, 0x9d3c4cef
srl t4, t1, t0
srl t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
srl t4, t1, t0
srl t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x4e119170
li t1, 0x169d5fc9
li t2, 0x93481d99
li t3, 0x252d1b0d
sra t4, t1, t0
sra t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
sra t4, t1, t0
sra t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xb10b85b8
li t1, 0x3a14d322
li t2, 0x7223cd26
li t3, 0x669605cd
or t4, t1, t0
or t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
or t4, t1, t0
or t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xfc3da01f
li t1, 0xd0b02ed1
li t2, 0x121808c0
li t3, 0x335a2eb0
and t4, t1, t0
and t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
and t4, t1, t0
and t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xda0cb6f0
li t1, 0xd488b47b
li t2, 0xf0a1c58a
li t3, 0x31839ec9
p.adduNr t4, t1, t0
p.adduNr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.adduNr t4, t1, t0
p.adduNr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xa4a86ad0
li t1, 0x33ab7761
li t2, 0x11383a83
li t3, 0xa6afdc37
p.addRNr t4, t1, t0
p.addRNr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.addRNr t4, t1, t0
p.addRNr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x4dff3f81
li t1, 0xfdcd1970
li t2, 0x2b4bf8e7
li t3, 0xb427fc74
p.exths t4, t1
p.exths t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.exths t4, t1
p.exths t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0307e1ce
li t1, 0x2b3c9ec3
li t2, 0x2ed5a687
li t3, 0x99dc471d
p.subNr t4, t1, t0
p.subNr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.subNr t4, t1, t0
p.subNr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xd33e187a
li t1, 0xec109bbb
li t2, 0x0b4b683d
li t3, 0x3d09a560
p.subRNr t4, t1, t0
p.subRNr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.subRNr t4, t1, t0
p.subRNr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xe679a0e0
li t1, 0x37f1d340
li t2, 0x0814ec33
li t3, 0xf2507552
p.subuRNr t4, t1, t0
p.subuRNr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.subuRNr t4, t1, t0
p.subuRNr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x669a5447
li t1, 0x47d9ef1a
li t2, 0x785775e4
li t3, 0x2568675c
p.extractr t4, t1, t0
p.extractr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.extractr t4, t1, t0
p.extractr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xe5a6172e
li t1, 0xe60c230d
li t2, 0x3da2454e
li t3, 0x0db7dd8c
p.extractur t4, t1, t0
p.extractur t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.extractur t4, t1, t0
p.extractur t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xad9b652d
li t1, 0x8c8afe09
li t2, 0x273a1d73
li t3, 0x56d799ad
p.insertr t4, t1, t0
p.insertr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.insertr t4, t1, t0
p.insertr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x94c8d0e9
li t1, 0x886ae4be
li t2, 0xf2478900
li t3, 0xeac97e1e
p.bclrr t4, t1, t0
p.bclrr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.bclrr t4, t1, t0
p.bclrr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x374b2fe6
li t1, 0x4145c8eb
li t2, 0xa0d28c48
li t3, 0xeb3af00a
p.bsetr t4, t1, t0
p.bsetr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.bsetr t4, t1, t0
p.bsetr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xd2dfb387
li t1, 0xb3bd9ed7
li t2, 0x591146e7
li t3, 0xe46111e8
p.ror t4, t1, t0
p.ror t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.ror t4, t1, t0
p.ror t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x4d086a24
li t1, 0x67afe016
li t2, 0x008aeedd
li t3, 0xf5eac4b9
p.slet t4, t1, t0
p.slet t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.slet t4, t1, t0
p.slet t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x05f12a06
li t1, 0x0ec28523
li t2, 0x33a20c73
li t3, 0x7974df24
p.slet t4, t1, t0
p.slet t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.slet t4, t1, t0
p.slet t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x8a5db7e2
li t1, 0x919ff74c
li t2, 0x5b57814b
li t3, 0xfba83620
p.sletu t4, t1, t0
p.sletu t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.sletu t4, t1, t0
p.sletu t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x817b3ab2
li t1, 0xd29cf252
li t2, 0x75fcacd6
li t3, 0xe185871b
p.min t4, t1, t0
p.min t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.min t4, t1, t0
p.min t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x7a16c576
li t1, 0x8a813452
li t2, 0x761a01ed
li t3, 0xa1d45974
p.minu t4, t1, t0
p.minu t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.minu t4, t1, t0
p.minu t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xf8f73ca5
li t1, 0x19b2e5c9
li t2, 0x313a690b
li t3, 0x33671e7a
p.max t4, t1, t0
p.max t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.max t4, t1, t0
p.max t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x5f28295f
li t1, 0x6fcba286
li t2, 0x6feb78ab
li t3, 0x0a3ccd3e
p.insertr t4, t1, t0
p.insertr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.insertr t4, t1, t0
p.insertr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x96b0a703
li t1, 0x86df935a
li t2, 0xccb6b06b
li t3, 0x9868fe15
p.bclrr t4, t1, t0
p.bclrr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.bclrr t4, t1, t0
p.bclrr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xd73a8a09
li t1, 0x49df1dce
li t2, 0x7fa5a926
li t3, 0xdbf08a5f
p.bsetr t4, t1, t0
p.bsetr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.bsetr t4, t1, t0
p.bsetr t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x4e61f1cd
li t1, 0xcfbbde59
li t2, 0x3ce35185
li t3, 0xcc72d7e6
p.ror t4, t1, t0
p.ror t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.ror t4, t1, t0
p.ror t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xaacd73c5
li t1, 0xf8951dd8
li t2, 0x54465dea
li t3, 0x50af7872
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.clip t4, t1, 0x0e
p.clip t5, t3, 0x0e
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x32286b14
li t1, 0x1591cebc
li t2, 0x712b900e
li t3, 0x2c8a37b8
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.clipu t4, t1, 0x1d
p.clipu t5, t3, 0x1d
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xcaac4959
li t1, 0x00ab2abb
li t2, 0x21d1cc36
li t3, 0xc2707e18
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.clipr t4, t1, t0
p.clipr t5, t3, t2
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0e5d949d
li t1, 0x48310c88
li t2, 0x3e971132
li t3, 0xe6f0f5c4
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.clipur t4, t1, t0
p.clipur t5, t2, t1
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x01965288
li t1, 0x6242778d
li t2, 0xf63ca7b3
li t3, 0x58732b49
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.addN t4, t1, t0, 0x0a
p.addN t5, t2, t3, 0x0a
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x12033149
li t1, 0xb5117891
li t2, 0x3cd05571
li t3, 0xecf51901
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.adduN t4, t1, t0, 0x03
p.adduN t5, t2, t3, 0x03
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xe2886f1a
li t1, 0x7868e991
li t2, 0xac2b46b1
li t3, 0x86c74504
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.addRN t4, t1, t0, 0x0a
p.addRN t5, t2, t3, 0x0a
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x81ca2a91
li t1, 0xdbd9c4ad
li t2, 0xf5468356
li t3, 0x7a89ff44
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.adduRN t4, t1, t0, 0x0a
p.adduRN t5, t2, t3, 0x0a
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xb08cbdb0
li t1, 0x312871a5
li t2, 0x09425196
li t3, 0x76b8dee7
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.subN t4, t1, t0, 0x04
p.subN t5, t2, t3, 0x04
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x2873785d
li t1, 0xa58abecf
li t2, 0x34116eab
li t3, 0xc60c7b7c
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.subuN t4, t1, t0, 0x10
p.subuN t5, t2, t3, 0x10
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x6bc70c14
li t1, 0x20e32e9f
li t2, 0x3a44824a
li t3, 0x5813334a
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.subRN t4, t1, t0, 0x14
p.subRN t5, t2, t3, 0x14
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xa9625cb0
li t1, 0xd1f1021f
li t2, 0x4a79f112
li t3, 0x9f4c67db
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.subuRN t4, t1, t0, 0x03
p.subuRN t5, t2, t3, 0x03
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xe3afb639
li t1, 0x3aae31a4
li t2, 0xcdad5973
li t3, 0x807c253b
p.abs t4, t1
p.abs t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.abs t4, t1
p.abs t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x629550bc
li t1, 0xdb5ce096
li t2, 0x2e9186d7
li t3, 0xbabc743e
p.exths t4, t1
p.exths t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.exths t4, t1
p.exths t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x81c9e471
li t1, 0x73df7b05
li t2, 0x1bd5d7e3
li t3, 0x4aa8781c
p.exthz t4, t1
p.exthz t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.exthz t4, t1
p.exthz t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xa48b3cf4
li t1, 0xed740ad1
li t2, 0xe0a53938
li t3, 0xd84510bd
p.extbs t4, t1
p.extbs t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.extbs t4, t1
p.extbs t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x156c4b8c
li t1, 0xc1c37b2d
li t2, 0x0ee78864
li t3, 0x91270e72
p.extbz t4, t1
p.extbz t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
p.extbz t4, t1
p.extbz t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x3ee69516
li t1, 0x2963ce79
li t2, 0xe1990727
li t3, 0x05433dd5
sll t4, t1, t0
sll t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
sll t4, t1, t0
sll t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x82da82b3
li t1, 0xd9702e79
li t2, 0xadb1295e
li t3, 0xa8f00591
slt t4, t1, t0
slt t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
slt t4, t1, t0
slt t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xf96efd30
li t1, 0x7673e3fb
li t2, 0x8d837b1a
li t3, 0x2253c108
sltu t4, t1, t0
sltu t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
sltu t4, t1, t0
sltu t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x8c791f24
li t1, 0x16f8ee45
li t2, 0x99f81698
li t3, 0x388abd36
div t4, t1, t0
div t5, t3, t2
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
div t4, t1, t0
div t5, t3, t2
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x04677ed1
li t1, 0xc75c4e16
li t2, 0x108a227d
li t3, 0x7a971702
divu t4, t1, t0
divu t5, t3, t2
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
divu t4, t1, t0
divu t5, t3, t2
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xb4b26cfe
li t1, 0x905ccf6b
li t2, 0x5a800292
li t3, 0xcdb1d407
pv.add.h t4, t1, t0
pv.add.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.add.h t4, t1, t0
pv.add.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x659cd700
li t1, 0x1b6f80ac
li t2, 0x1d5d9d13
li t3, 0xc95673f5
pv.add.sc.h t4, t1, t0
pv.add.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.add.sc.h t4, t1, t0
pv.add.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xb7c11ac1
li t1, 0x2cbc4e86
li t2, 0x6340c88b
li t3, 0xe0800e38
pv.add.sci.h t4, t1, 0x05
pv.add.sci.h t5, t2, 0x05
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.add.sci.h t4, t1, 0x1a
pv.add.sci.h t5, t2, 0x1a
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x07b74d82
li t1, 0xe7656f5e
li t2, 0x5ff76637
li t3, 0x5a7ae8c6
pv.add.b t4, t1, t0
pv.add.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.add.b t4, t1, t0
pv.add.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x6e1509f9
li t1, 0xdbfc32b9
li t2, 0xa8e20e5e
li t3, 0x1141ea5f
pv.add.sc.b t4, t1, t0
pv.add.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.add.sc.b t4, t1, t0
pv.add.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x12a5172a
li t1, 0x50525f66
li t2, 0x39eea50c
li t3, 0x2a23b0e8
pv.add.sci.b t4, t1, 0x01
pv.add.sci.b t5, t2, 0x01
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.add.sci.b t4, t1, 0x1e
pv.add.sci.b t5, t2, 0x1e
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xe0b298e4
li t1, 0xb6d60d16
li t2, 0x85f53f77
li t3, 0x9b3921b5
pv.sub.h t4, t1, t0
pv.sub.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.sub.h t4, t1, t0
pv.sub.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xae40b9d4
li t1, 0x77f3dfc3
li t2, 0xd7863ca1
li t3, 0xc275f253
pv.sub.sc.h t4, t1, t0
pv.sub.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.sub.sc.h t4, t1, t0
pv.sub.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x477a8025
li t1, 0x104ae976
li t2, 0x005ba68b
li t3, 0x32393c21
pv.sub.sci.h t4, t1, 0x1a
pv.sub.sci.h t5, t2, 0x1a
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.sub.sci.h t4, t1, 0x05
pv.sub.sci.h t5, t2, 0x05
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x337f650e
li t1, 0xd948bb72
li t2, 0x6b71a965
li t3, 0xc6558b30
pv.sub.b t4, t1, t0
pv.sub.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.sub.b t4, t1, t0
pv.sub.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xdd734a21
li t1, 0x0de88e1e
li t2, 0xe68d1aba
li t3, 0xcfefc3c4
pv.sub.sc.b t4, t1, t0
pv.sub.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.sub.sc.b t4, t1, t0
pv.sub.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x5aa670f2
li t1, 0x21a5a75e
li t2, 0xcc24c8c0
li t3, 0x9dbef5b0
pv.sub.sci.b t4, t1, 0x0d
pv.sub.sci.b t5, t2, 0x0d
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.sub.sci.b t4, t1, 0x12
pv.sub.sci.b t5, t2, 0x12
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x3c6e0785
li t1, 0x6b184c32
li t2, 0x6e0863ca
li t3, 0xeabd78e2
pv.avg.h t4, t1, t0
pv.avg.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.avg.h t4, t1, t0
pv.avg.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xadf492b0
li t1, 0x6572295e
li t2, 0x9deadde2
li t3, 0x7af02b87
pv.avg.sc.h t4, t1, t0
pv.avg.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.avg.sc.h t4, t1, t0
pv.avg.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x49aa31f3
li t1, 0xcfbc027f
li t2, 0xcdf15314
li t3, 0x8065aa7e
pv.avg.sci.h t4, t1, 0x11
pv.avg.sci.h t5, t2, 0x11
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.avg.sci.h t4, t1, 0x0e
pv.avg.sci.h t5, t2, 0x0e
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xbf9528ff
li t1, 0x1d6aa8a2
li t2, 0xce0c8542
li t3, 0x75bd5b07
pv.avg.b t4, t1, t0
pv.avg.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.avg.b t4, t1, t0
pv.avg.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x5b1f70fc
li t1, 0xa23e48a5
li t2, 0x236548d2
li t3, 0x022c0508
pv.avg.sc.b t4, t1, t0
pv.avg.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.avg.sc.b t4, t1, t0
pv.avg.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xb4e2cde6
li t1, 0xa3c1c85d
li t2, 0x06dc6465
li t3, 0xf57a6a08
pv.avg.sci.b t4, t1, 0x1f
pv.avg.sci.b t5, t2, 0x1f
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.avg.sci.b t4, t1, 0x00
pv.avg.sci.b t5, t2, 0x00
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xf42f298b
li t1, 0xd7459e2a
li t2, 0x61a688b0
li t3, 0x000eaa6b
pv.avgu.h t4, t1, t0
pv.avgu.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.avgu.h t4, t1, t0
pv.avgu.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x82dc8d47
li t1, 0x5fa506e0
li t2, 0xc3ea0491
li t3, 0x7c25859e
pv.avgu.sc.h t4, t1, t0
pv.avgu.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.avgu.sc.h t4, t1, t0
pv.avgu.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x8bb4f32b
li t1, 0x2c692a7b
li t2, 0xd1ddbc93
li t3, 0xec2f40b0
pv.avgu.sci.h t4, t1, 0x0a
pv.avgu.sci.h t5, t2, 0x0a
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.avgu.sci.h t4, t1, 0x15
pv.avgu.sci.h t5, t2, 0x15
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x76567e2d
li t1, 0xe28c534b
li t2, 0x97ee1fff
li t3, 0xee3ed3ed
pv.avgu.b t4, t1, t0
pv.avgu.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.avgu.b t4, t1, t0
pv.avgu.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x9f1e3133
li t1, 0x4b3c8409
li t2, 0xa0dfe1da
li t3, 0xf69dae34
pv.avgu.sc.b t4, t1, t0
pv.avgu.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.avgu.sc.b t4, t1, t0
pv.avgu.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xfc1873bf
li t1, 0x7d2643db
li t2, 0xde85ad02
li t3, 0x4634a7d7
pv.avgu.sci.b t4, t1, 0x1e
pv.avgu.sci.b t5, t2, 0x1e
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.avgu.sci.b t4, t1, 0x01
pv.avgu.sci.b t5, t2, 0x01
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x81106cc9
li t1, 0xc099fced
li t2, 0x8c4075a1
li t3, 0xfe9ad166
pv.max.h t4, t1, t0
pv.max.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.max.h t4, t1, t0
pv.max.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x730c6295
li t1, 0x5ccfc815
li t2, 0xcfb76039
li t3, 0xd34e4893
pv.max.sc.h t4, t1, t0
pv.max.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.max.sc.h t4, t1, t0
pv.max.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xfa03def2
li t1, 0xd6b075c2
li t2, 0x4c51267f
li t3, 0x758192ab
pv.max.sci.h t4, t1, 0x06
pv.max.sci.h t5, t2, 0x06
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.max.sci.h t4, t1, 0x19
pv.max.sci.h t5, t2, 0x19
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x0346ab14
li t1, 0x3c9cfb0e
li t2, 0xcdf4cce2
li t3, 0x9ceca406
pv.max.b t4, t1, t0
pv.max.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.max.b t4, t1, t0
pv.max.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x62d00803
li t1, 0xa9c36d74
li t2, 0xddd956b8
li t3, 0xa735bb95
pv.max.sc.b t4, t1, t0
pv.max.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.max.sc.b t4, t1, t0
pv.max.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x23e3a82f
li t1, 0xbcf1ba33
li t2, 0x32f7e282
li t3, 0xc54c9def
pv.max.sci.b t4, t1, 0x04
pv.max.sci.b t5, t2, 0x04
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.max.sci.b t4, t1, 0x1b
pv.max.sci.b t5, t2, 0x1b
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xbaa49f48
li t1, 0x3c76a754
li t2, 0x71390b88
li t3, 0xa90659bf
pv.maxu.h t4, t1, t0
pv.maxu.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.maxu.h t4, t1, t0
pv.maxu.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x61a9d7dd
li t1, 0x967d026e
li t2, 0x62483ee8
li t3, 0x55b1bf2c
pv.maxu.sc.h t4, t1, t0
pv.maxu.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.maxu.sc.h t4, t1, t0
pv.maxu.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xda7248e7
li t1, 0x0d44b94c
li t2, 0x9cafced9
li t3, 0x61ae145b
pv.maxu.sci.h t4, t1, 0x10
pv.maxu.sci.h t5, t2, 0x10
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.maxu.sci.h t4, t1, 0x0f
pv.maxu.sci.h t5, t2, 0x0f
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x40656d3d
li t1, 0xbb350b84
li t2, 0x7fec4fa1
li t3, 0xf4717615
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x16e9e708
li t1, 0x63b1a3d9
li t2, 0x8a6647b3
li t3, 0x0b12d162
pv.maxu.b t4, t1, t0
pv.maxu.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.maxu.b t4, t1, t0
pv.maxu.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x5a2bacaa
li t1, 0x99461203
li t2, 0xbfc8d90c
li t3, 0xdbb73240
pv.maxu.sc.b t4, t1, t0
pv.maxu.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.maxu.sc.b t4, t1, t0
pv.maxu.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x5328d071
li t1, 0x25713f13
li t2, 0xa15ea61d
li t3, 0x64300ebf
pv.maxu.sci.b t4, t1, 0x00
pv.maxu.sci.b t5, t2, 0x00
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.maxu.sci.b t4, t1, 0x1f
pv.maxu.sci.b t5, t2, 0x1f
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xcc25c37c
li t1, 0x98e58605
li t2, 0x723cf6bf
li t3, 0x71c15f2f
pv.srl.h t4, t1, t0
pv.srl.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.srl.h t4, t1, t0
pv.srl.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xbd287784
li t1, 0x1f2d9a39
li t2, 0x503f98b5
li t3, 0xb85d15e5
pv.srl.sc.h t4, t1, t0
pv.srl.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.srl.sc.h t4, t1, t0
pv.srl.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xeda385c6
li t1, 0x7fd05641
li t2, 0xdc2f4bc6
li t3, 0xc5c91614
pv.srl.sci.h t4, t1, 0x06
pv.srl.sci.h t5, t2, 0x06
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.srl.sci.h t4, t1, 0x19
pv.srl.sci.h t5, t2, 0x19
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x4d3defe4
li t1, 0x5f233bca
li t2, 0xf671c29d
li t3, 0x96b56516
pv.srl.b t4, t1, t0
pv.srl.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.srl.b t4, t1, t0
pv.srl.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x84de05ba
li t1, 0x196730f6
li t2, 0xb65cfa60
li t3, 0xf85bae0e
pv.srl.sc.b t4, t1, t0
pv.srl.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.srl.sc.b t4, t1, t0
pv.srl.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xd955efd2
li t1, 0x20532d77
li t2, 0xb9f3d8b4
li t3, 0xabc275f7
pv.srl.sci.b t4, t1, 0x0b
pv.srl.sci.b t5, t2, 0x0b
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.srl.sci.b t4, t1, 0x14
pv.srl.sci.b t5, t2, 0x14
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xc9626b10
li t1, 0x0a88c76d
li t2, 0xf3ed0ff7
li t3, 0xf299362f
pv.sra.h t4, t1, t0
pv.sra.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.sra.h t4, t1, t0
pv.sra.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x871672e4
li t1, 0x49834b84
li t2, 0x0f67c50d
li t3, 0x927e3e8d
pv.sra.sc.h t4, t1, t0
pv.sra.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.sra.sc.h t4, t1, t0
pv.sra.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x5db8e006
li t1, 0xb7fe1dc2
li t2, 0x42a8d054
li t3, 0xcecddeff
pv.sra.sci.h t4, t1, 0x1d
pv.sra.sci.h t5, t2, 0x1d
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.sra.sci.h t4, t1, 0x02
pv.sra.sci.h t5, t2, 0x02
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x7c8d877b
li t1, 0xfa58f0d7
li t2, 0x78394a69
li t3, 0x8cc04124
pv.sra.b t4, t1, t0
pv.sra.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.sra.b t4, t1, t0
pv.sra.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x891fa34d
li t1, 0x02b3959b
li t2, 0xd70d2c02
li t3, 0x10b73e34
pv.sra.sc.b t4, t1, t0
pv.sra.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.sra.sc.b t4, t1, t0
pv.sra.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x3a71220b
li t1, 0xb14244ce
li t2, 0x8d9634a2
li t3, 0x1af57184
pv.sra.sci.b t4, t1, 0x0e
pv.sra.sci.b t5, t2, 0x0e
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.sra.sci.b t4, t1, 0x11
pv.sra.sci.b t5, t2, 0x11
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x6cc008b7
li t1, 0x71a6b630
li t2, 0x1f330aed
li t3, 0x2c487dff
pv.sll.h t4, t1, t0
pv.sll.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.sll.h t4, t1, t0
pv.sll.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xf520ce6d
li t1, 0xdef52794
li t2, 0xdb3a9fae
li t3, 0x34124a18
pv.sll.sc.h t4, t1, t0
pv.sll.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.sll.sc.h t4, t1, t0
pv.sll.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x34e749f9
li t1, 0x14e7a98a
li t2, 0x56f58a01
li t3, 0xe73d8a60
pv.sll.sci.h t4, t1, 0x10
pv.sll.sci.h t5, t2, 0x10
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.sll.sci.h t4, t1, 0x0f
pv.sll.sci.h t5, t2, 0x0f
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xaeb92db5
li t1, 0x0aeb9611
li t2, 0x8e735188
li t3, 0x20d8f31d
pv.sll.b t4, t1, t0
pv.sll.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.sll.b t4, t1, t0
pv.sll.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x8f291289
li t1, 0x93fd762d
li t2, 0x95465eb6
li t3, 0x14253f29
pv.sll.sc.b t4, t1, t0
pv.sll.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.sll.sc.b t4, t1, t0
pv.sll.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x2f0f3f6c
li t1, 0x66d7fc7d
li t2, 0x1f0abbf1
li t3, 0xa375139c
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x4aeb24a7
li t1, 0x810b841e
li t2, 0xdf3029cf
li t3, 0x82702db2
pv.sll.sci.b t4, t1, 0x09
pv.sll.sci.b t5, t2, 0x09
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.sll.sci.b t4, t1, 0x16
pv.sll.sci.b t5, t2, 0x16
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x5befddf7
li t1, 0xc04f84c9
li t2, 0xe2fe6637
li t3, 0xfa6a3c7d
pv.or.h t4, t1, t0
pv.or.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.or.h t4, t1, t0
pv.or.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x3cdcf86b
li t1, 0xdc7f23d0
li t2, 0xb53d0eaa
li t3, 0xb130b80c
pv.or.sc.h t4, t1, t0
pv.or.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.or.sc.h t4, t1, t0
pv.or.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x4ce1f0a4
li t1, 0xa13d3788
li t2, 0x53ac073d
li t3, 0x8ca21ab7
pv.or.sci.h t4, t1, 0x04
pv.or.sci.h t5, t2, 0x04
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.or.sci.h t4, t1, 0x1b
pv.or.sci.h t5, t2, 0x1b
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x2efa2f70
li t1, 0x4a8a9ffa
li t2, 0xa55ea61f
li t3, 0xbc3f8189
pv.or.b t4, t1, t0
pv.or.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.or.b t4, t1, t0
pv.or.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x41c54a97
li t1, 0x54288d3e
li t2, 0x0ae56830
li t3, 0x9daa57ea
pv.or.sc.b t4, t1, t0
pv.or.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.or.sc.b t4, t1, t0
pv.or.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xb047036c
li t1, 0xebe1e598
li t2, 0x9e19e860
li t3, 0x59cd558e
pv.or.sci.b t4, t1, 0x1e
pv.or.sci.b t5, t2, 0x1e
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.or.sci.b t4, t1, 0x01
pv.or.sci.b t5, t2, 0x01
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xb5ba78d8
li t1, 0x201f1f09
li t2, 0x3665a77e
li t3, 0xb946d49d
pv.xor.h t4, t1, t0
pv.xor.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.xor.h t4, t1, t0
pv.xor.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xf0a04d74
li t1, 0xf6d06cb3
li t2, 0xe617d200
li t3, 0x1c86ac82
pv.xor.sc.h t4, t1, t0
pv.xor.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.xor.sc.h t4, t1, t0
pv.xor.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xd96778d9
li t1, 0x95cb7216
li t2, 0xddf6b6fb
li t3, 0x04b948a5
pv.xor.sci.h t4, t1, 0x02
pv.xor.sci.h t5, t2, 0x02
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.xor.sci.h t4, t1, 0x1d
pv.xor.sci.h t5, t2, 0x1d
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x662739e0
li t1, 0x3195d646
li t2, 0x3b47c3e9
li t3, 0x559a26d2
pv.xor.b t4, t1, t0
pv.xor.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.xor.b t4, t1, t0
pv.xor.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x3e561143
li t1, 0xd8afe78f
li t2, 0x45de48d3
li t3, 0x37a49ac7
pv.xor.sc.b t4, t1, t0
pv.xor.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.xor.sc.b t4, t1, t0
pv.xor.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x7f470dd5
li t1, 0xde654b20
li t2, 0xfbc97885
li t3, 0x7680eba0
pv.xor.sci.b t4, t1, 0x18
pv.xor.sci.b t5, t2, 0x18
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.xor.sci.b t4, t1, 0x07
pv.xor.sci.b t5, t2, 0x07
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xc31e64a5
li t1, 0x3223809f
li t2, 0x7881be3a
li t3, 0x7eeea914
pv.and.h t4, t1, t0
pv.and.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.and.h t4, t1, t0
pv.and.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x6b0cefef
li t1, 0xb091d03f
li t2, 0x7f463f89
li t3, 0x1487397c
pv.and.sc.h t4, t1, t0
pv.and.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.and.sc.h t4, t1, t0
pv.and.sc.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x544f5a66
li t1, 0xfb98aed3
li t2, 0xc4c63a8d
li t3, 0x5f9dac11
pv.and.sci.h t4, t1, 0x0b
pv.and.sci.h t5, t2, 0x0b
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.and.sci.h t4, t1, 0x14
pv.and.sci.h t5, t2, 0x14
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xaf824e6d
li t1, 0x6a8ea0fc
li t2, 0x6a35ad3b
li t3, 0x713a77c9
pv.and.b t4, t1, t0
pv.and.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.and.b t4, t1, t0
pv.and.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x7aa58ea0
li t1, 0x6901d5dd
li t2, 0x5b779221
li t3, 0x82fdbda2
pv.and.sc.b t4, t1, t0
pv.and.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.and.sc.b t4, t1, t0
pv.and.sc.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xb10215c5
li t1, 0x48fe44a7
li t2, 0x4fbd24ce
li t3, 0x831c7ef4
pv.and.sci.b t4, t1, 0x10
pv.and.sci.b t5, t2, 0x10
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.and.sci.b t4, t1, 0x0f
pv.and.sci.b t5, t2, 0x0f
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x6ab131e8
li t1, 0x77acbc7e
li t2, 0x084e505f
li t3, 0xdcace0b2
pv.abs.h t4, t1
pv.abs.b t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.abs.h t4, t1
pv.abs.b t5, t2
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xb0203db7
li t1, 0xf768997f
li t2, 0x0e68e378
li t3, 0x472afea2
pv.shuffle.h t4, t1, t0
pv.shuffle.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.shuffle.h t4, t1, t0
pv.shuffle.h t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x3039b2ef
li t1, 0x9deee289
li t2, 0xd33d21cf
li t3, 0x2dd5a070
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0x43f6d1b6
li t1, 0x37d67ec5
li t2, 0x72e25dd1
li t3, 0x74588fc5
pv.shuffle.sci.h t4, t1, 0x1b
pv.shuffle.sci.h t5, t2, 0x1b
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.shuffle.sci.h t4, t1, 0x04
pv.shuffle.sci.h t5, t2, 0x04
sw t4, 4(sp)
sw t5, 4(sp)
li t0, 0xe8161d7d
li t1, 0x7c508ea4
li t2, 0xabe5a4ba
li t3, 0x4f72c142
pv.shuffle.b t4, t1, t0
pv.shuffle.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
xori t0, t0, 0xffffffff
xori t1, t1, 0xffffffff
xori t2, t2, 0xffffffff
xori t3, t3, 0xffffffff
pv.shuffle.b t4, t1, t0
pv.shuffle.b t5, t2, t3
sw t4, 4(sp)
sw t5, 4(sp)
